// 500 Most Frequently Used Words in 10 Languages
// Languages: English, Spanish, French, German, Japanese, Korean, Chinese, Portuguese, Italian, Arabic

const LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Spanish', flag: '🇪🇸' },
  { code: 'fr', name: 'French', flag: '🇫🇷' },
  { code: 'de', name: 'German', flag: '🇩🇪' },
  { code: 'ja', name: 'Japanese', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', flag: '🇰🇷' },
  { code: 'zh', name: 'Chinese', flag: '🇨🇳' },
  { code: 'pt', name: 'Portuguese', flag: '🇧🇷' },
  { code: 'it', name: 'Italian', flag: '🇮🇹' },
  { code: 'ar', name: 'Arabic', flag: '🇸🇦' }
];

const CATEGORIES = [
  {
    name: "Greetings & Basics",
    icon: "👋",
    words: [
      { en: "hello", es: "hola", fr: "bonjour", de: "hallo", ja: "こんにちは", ko: "안녕하세요", zh: "你好", pt: "olá", it: "ciao", ar: "مرحبا" },
      { en: "goodbye", es: "adiós", fr: "au revoir", de: "auf Wiedersehen", ja: "さようなら", ko: "안녕히 가세요", zh: "再见", pt: "adeus", it: "arrivederci", ar: "مع السلامة" },
      { en: "please", es: "por favor", fr: "s'il vous plaît", de: "bitte", ja: "お願いします", ko: "제발", zh: "请", pt: "por favor", it: "per favore", ar: "من فضلك" },
      { en: "thank you", es: "gracias", fr: "merci", de: "danke", ja: "ありがとう", ko: "감사합니다", zh: "谢谢", pt: "obrigado", it: "grazie", ar: "شكرا" },
      { en: "yes", es: "sí", fr: "oui", de: "ja", ja: "はい", ko: "네", zh: "是", pt: "sim", it: "sì", ar: "نعم" },
      { en: "no", es: "no", fr: "non", de: "nein", ja: "いいえ", ko: "아니요", zh: "不", pt: "não", it: "no", ar: "لا" },
      { en: "sorry", es: "lo siento", fr: "désolé", de: "Entschuldigung", ja: "すみません", ko: "미안합니다", zh: "对不起", pt: "desculpe", it: "scusa", ar: "آسف" },
      { en: "excuse me", es: "disculpe", fr: "excusez-moi", de: "Entschuldigen Sie", ja: "すみません", ko: "실례합니다", zh: "打扰一下", pt: "com licença", it: "scusi", ar: "عفوا" },
      { en: "good morning", es: "buenos días", fr: "bonjour", de: "guten Morgen", ja: "おはようございます", ko: "좋은 아침", zh: "早上好", pt: "bom dia", it: "buongiorno", ar: "صباح الخير" },
      { en: "good night", es: "buenas noches", fr: "bonne nuit", de: "gute Nacht", ja: "おやすみなさい", ko: "안녕히 주무세요", zh: "晚安", pt: "boa noite", it: "buonanotte", ar: "تصبح على خير" },
      { en: "how are you", es: "¿cómo estás?", fr: "comment allez-vous?", de: "wie geht es Ihnen?", ja: "お元気ですか", ko: "어떻게 지내세요?", zh: "你好吗", pt: "como vai?", it: "come stai?", ar: "كيف حالك" },
      { en: "nice to meet you", es: "mucho gusto", fr: "enchanté", de: "freut mich", ja: "はじめまして", ko: "만나서 반갑습니다", zh: "很高兴认识你", pt: "prazer em conhecê-lo", it: "piacere di conoscerti", ar: "سعيد بلقائك" },
      { en: "see you later", es: "hasta luego", fr: "à bientôt", de: "bis später", ja: "また後で", ko: "나중에 봐요", zh: "回头见", pt: "até logo", it: "a dopo", ar: "أراك لاحقا" },
      { en: "welcome", es: "bienvenido", fr: "bienvenue", de: "willkommen", ja: "ようこそ", ko: "환영합니다", zh: "欢迎", pt: "bem-vindo", it: "benvenuto", ar: "أهلا وسهلا" },
      { en: "I", es: "yo", fr: "je", de: "ich", ja: "私", ko: "나", zh: "我", pt: "eu", it: "io", ar: "أنا" },
      { en: "you", es: "tú", fr: "tu / vous", de: "du / Sie", ja: "あなた", ko: "당신", zh: "你", pt: "você", it: "tu / Lei", ar: "أنت" },
      { en: "he", es: "él", fr: "il", de: "er", ja: "彼", ko: "그", zh: "他", pt: "ele", it: "lui", ar: "هو" },
      { en: "she", es: "ella", fr: "elle", de: "sie", ja: "彼女", ko: "그녀", zh: "她", pt: "ela", it: "lei", ar: "هي" },
      { en: "we", es: "nosotros", fr: "nous", de: "wir", ja: "私たち", ko: "우리", zh: "我们", pt: "nós", it: "noi", ar: "نحن" },
      { en: "they", es: "ellos", fr: "ils / elles", de: "sie", ja: "彼ら", ko: "그들", zh: "他们", pt: "eles", it: "loro", ar: "هم" },
      { en: "this", es: "esto", fr: "ceci", de: "dies", ja: "これ", ko: "이것", zh: "这", pt: "isto", it: "questo", ar: "هذا" },
      { en: "that", es: "eso", fr: "cela", de: "das", ja: "それ", ko: "저것", zh: "那", pt: "isso", it: "quello", ar: "ذلك" },
      { en: "what", es: "qué", fr: "quoi", de: "was", ja: "何", ko: "무엇", zh: "什么", pt: "o quê", it: "che cosa", ar: "ماذا" },
      { en: "where", es: "dónde", fr: "où", de: "wo", ja: "どこ", ko: "어디", zh: "哪里", pt: "onde", it: "dove", ar: "أين" },
      { en: "when", es: "cuándo", fr: "quand", de: "wann", ja: "いつ", ko: "언제", zh: "什么时候", pt: "quando", it: "quando", ar: "متى" },
      { en: "why", es: "por qué", fr: "pourquoi", de: "warum", ja: "なぜ", ko: "왜", zh: "为什么", pt: "por quê", it: "perché", ar: "لماذا" },
      { en: "how", es: "cómo", fr: "comment", de: "wie", ja: "どう", ko: "어떻게", zh: "怎么", pt: "como", it: "come", ar: "كيف" },
      { en: "who", es: "quién", fr: "qui", de: "wer", ja: "誰", ko: "누구", zh: "谁", pt: "quem", it: "chi", ar: "من" }
    ]
  },
  {
    name: "Numbers",
    icon: "🔢",
    words: [
      { en: "zero", es: "cero", fr: "zéro", de: "null", ja: "零 (れい)", ko: "영", zh: "零", pt: "zero", it: "zero", ar: "صفر" },
      { en: "one", es: "uno", fr: "un", de: "eins", ja: "一 (いち)", ko: "일 / 하나", zh: "一", pt: "um", it: "uno", ar: "واحد" },
      { en: "two", es: "dos", fr: "deux", de: "zwei", ja: "二 (に)", ko: "이 / 둘", zh: "二", pt: "dois", it: "due", ar: "اثنان" },
      { en: "three", es: "tres", fr: "trois", de: "drei", ja: "三 (さん)", ko: "삼 / 셋", zh: "三", pt: "três", it: "tre", ar: "ثلاثة" },
      { en: "four", es: "cuatro", fr: "quatre", de: "vier", ja: "四 (し/よん)", ko: "사 / 넷", zh: "四", pt: "quatro", it: "quattro", ar: "أربعة" },
      { en: "five", es: "cinco", fr: "cinq", de: "fünf", ja: "五 (ご)", ko: "오 / 다섯", zh: "五", pt: "cinco", it: "cinque", ar: "خمسة" },
      { en: "six", es: "seis", fr: "six", de: "sechs", ja: "六 (ろく)", ko: "육 / 여섯", zh: "六", pt: "seis", it: "sei", ar: "ستة" },
      { en: "seven", es: "siete", fr: "sept", de: "sieben", ja: "七 (しち/なな)", ko: "칠 / 일곱", zh: "七", pt: "sete", it: "sette", ar: "سبعة" },
      { en: "eight", es: "ocho", fr: "huit", de: "acht", ja: "八 (はち)", ko: "팔 / 여덟", zh: "八", pt: "oito", it: "otto", ar: "ثمانية" },
      { en: "nine", es: "nueve", fr: "neuf", de: "neun", ja: "九 (きゅう)", ko: "구 / 아홉", zh: "九", pt: "nove", it: "nove", ar: "تسعة" },
      { en: "ten", es: "diez", fr: "dix", de: "zehn", ja: "十 (じゅう)", ko: "십 / 열", zh: "十", pt: "dez", it: "dieci", ar: "عشرة" },
      { en: "eleven", es: "once", fr: "onze", de: "elf", ja: "十一", ko: "십일 / 열하나", zh: "十一", pt: "onze", it: "undici", ar: "أحد عشر" },
      { en: "twelve", es: "doce", fr: "douze", de: "zwölf", ja: "十二", ko: "십이 / 열둘", zh: "十二", pt: "doze", it: "dodici", ar: "اثنا عشر" },
      { en: "twenty", es: "veinte", fr: "vingt", de: "zwanzig", ja: "二十", ko: "이십 / 스물", zh: "二十", pt: "vinte", it: "venti", ar: "عشرون" },
      { en: "thirty", es: "treinta", fr: "trente", de: "dreißig", ja: "三十", ko: "삼십 / 서른", zh: "三十", pt: "trinta", it: "trenta", ar: "ثلاثون" },
      { en: "forty", es: "cuarenta", fr: "quarante", de: "vierzig", ja: "四十", ko: "사십 / 마흔", zh: "四十", pt: "quarenta", it: "quaranta", ar: "أربعون" },
      { en: "fifty", es: "cincuenta", fr: "cinquante", de: "fünfzig", ja: "五十", ko: "오십 / 쉰", zh: "五十", pt: "cinquenta", it: "cinquanta", ar: "خمسون" },
      { en: "hundred", es: "cien", fr: "cent", de: "hundert", ja: "百 (ひゃく)", ko: "백", zh: "百", pt: "cem", it: "cento", ar: "مائة" },
      { en: "thousand", es: "mil", fr: "mille", de: "tausend", ja: "千 (せん)", ko: "천", zh: "千", pt: "mil", it: "mille", ar: "ألف" },
      { en: "million", es: "millón", fr: "million", de: "Million", ja: "百万", ko: "백만", zh: "百万", pt: "milhão", it: "milione", ar: "مليون" },
      { en: "first", es: "primero", fr: "premier", de: "erster", ja: "最初", ko: "첫 번째", zh: "第一", pt: "primeiro", it: "primo", ar: "أول" },
      { en: "second", es: "segundo", fr: "deuxième", de: "zweiter", ja: "二番目", ko: "두 번째", zh: "第二", pt: "segundo", it: "secondo", ar: "ثاني" },
      { en: "third", es: "tercero", fr: "troisième", de: "dritter", ja: "三番目", ko: "세 번째", zh: "第三", pt: "terceiro", it: "terzo", ar: "ثالث" },
      { en: "half", es: "mitad", fr: "moitié", de: "Hälfte", ja: "半分", ko: "반", zh: "一半", pt: "metade", it: "metà", ar: "نصف" },
      { en: "pair", es: "par", fr: "paire", de: "Paar", ja: "一組", ko: "한 쌍", zh: "一对", pt: "par", it: "paio", ar: "زوج" }
    ]
  },
  {
    name: "Colors",
    icon: "🎨",
    words: [
      { en: "red", es: "rojo", fr: "rouge", de: "rot", ja: "赤 (あか)", ko: "빨간색", zh: "红色", pt: "vermelho", it: "rosso", ar: "أحمر" },
      { en: "blue", es: "azul", fr: "bleu", de: "blau", ja: "青 (あお)", ko: "파란색", zh: "蓝色", pt: "azul", it: "blu", ar: "أزرق" },
      { en: "green", es: "verde", fr: "vert", de: "grün", ja: "緑 (みどり)", ko: "초록색", zh: "绿色", pt: "verde", it: "verde", ar: "أخضر" },
      { en: "yellow", es: "amarillo", fr: "jaune", de: "gelb", ja: "黄色 (きいろ)", ko: "노란색", zh: "黄色", pt: "amarelo", it: "giallo", ar: "أصفر" },
      { en: "orange", es: "naranja", fr: "orange", de: "orange", ja: "オレンジ", ko: "주황색", zh: "橙色", pt: "laranja", it: "arancione", ar: "برتقالي" },
      { en: "purple", es: "morado", fr: "violet", de: "lila", ja: "紫 (むらさき)", ko: "보라색", zh: "紫色", pt: "roxo", it: "viola", ar: "بنفسجي" },
      { en: "pink", es: "rosa", fr: "rose", de: "rosa", ja: "ピンク", ko: "분홍색", zh: "粉色", pt: "rosa", it: "rosa", ar: "وردي" },
      { en: "black", es: "negro", fr: "noir", de: "schwarz", ja: "黒 (くろ)", ko: "검은색", zh: "黑色", pt: "preto", it: "nero", ar: "أسود" },
      { en: "white", es: "blanco", fr: "blanc", de: "weiß", ja: "白 (しろ)", ko: "흰색", zh: "白色", pt: "branco", it: "bianco", ar: "أبيض" },
      { en: "brown", es: "marrón", fr: "marron", de: "braun", ja: "茶色 (ちゃいろ)", ko: "갈색", zh: "棕色", pt: "marrom", it: "marrone", ar: "بني" },
      { en: "gray", es: "gris", fr: "gris", de: "grau", ja: "灰色 (はいいろ)", ko: "회색", zh: "灰色", pt: "cinza", it: "grigio", ar: "رمادي" },
      { en: "gold", es: "dorado", fr: "doré", de: "gold", ja: "金色 (きんいろ)", ko: "금색", zh: "金色", pt: "dourado", it: "dorato", ar: "ذهبي" },
      { en: "silver", es: "plateado", fr: "argenté", de: "silber", ja: "銀色 (ぎんいろ)", ko: "은색", zh: "银色", pt: "prateado", it: "argentato", ar: "فضي" },
      { en: "light", es: "claro", fr: "clair", de: "hell", ja: "明るい", ko: "밝은", zh: "浅", pt: "claro", it: "chiaro", ar: "فاتح" },
      { en: "dark", es: "oscuro", fr: "foncé", de: "dunkel", ja: "暗い", ko: "어두운", zh: "深", pt: "escuro", it: "scuro", ar: "غامق" }
    ]
  },
  {
    name: "Animals",
    icon: "🐾",
    words: [
      { en: "dog", es: "perro", fr: "chien", de: "Hund", ja: "犬 (いぬ)", ko: "개", zh: "狗", pt: "cachorro", it: "cane", ar: "كلب" },
      { en: "cat", es: "gato", fr: "chat", de: "Katze", ja: "猫 (ねこ)", ko: "고양이", zh: "猫", pt: "gato", it: "gatto", ar: "قطة" },
      { en: "bird", es: "pájaro", fr: "oiseau", de: "Vogel", ja: "鳥 (とり)", ko: "새", zh: "鸟", pt: "pássaro", it: "uccello", ar: "طائر" },
      { en: "fish", es: "pez", fr: "poisson", de: "Fisch", ja: "魚 (さかな)", ko: "물고기", zh: "鱼", pt: "peixe", it: "pesce", ar: "سمكة" },
      { en: "horse", es: "caballo", fr: "cheval", de: "Pferd", ja: "馬 (うま)", ko: "말", zh: "马", pt: "cavalo", it: "cavallo", ar: "حصان" },
      { en: "cow", es: "vaca", fr: "vache", de: "Kuh", ja: "牛 (うし)", ko: "소", zh: "牛", pt: "vaca", it: "mucca", ar: "بقرة" },
      { en: "pig", es: "cerdo", fr: "cochon", de: "Schwein", ja: "豚 (ぶた)", ko: "돼지", zh: "猪", pt: "porco", it: "maiale", ar: "خنزير" },
      { en: "sheep", es: "oveja", fr: "mouton", de: "Schaf", ja: "羊 (ひつじ)", ko: "양", zh: "羊", pt: "ovelha", it: "pecora", ar: "خروف" },
      { en: "chicken", es: "pollo", fr: "poulet", de: "Huhn", ja: "鶏 (にわとり)", ko: "닭", zh: "鸡", pt: "frango", it: "pollo", ar: "دجاجة" },
      { en: "duck", es: "pato", fr: "canard", de: "Ente", ja: "アヒル", ko: "오리", zh: "鸭", pt: "pato", it: "anatra", ar: "بطة" },
      { en: "rabbit", es: "conejo", fr: "lapin", de: "Kaninchen", ja: "うさぎ", ko: "토끼", zh: "兔子", pt: "coelho", it: "coniglio", ar: "أرنب" },
      { en: "mouse", es: "ratón", fr: "souris", de: "Maus", ja: "ネズミ", ko: "쥐", zh: "老鼠", pt: "rato", it: "topo", ar: "فأر" },
      { en: "elephant", es: "elefante", fr: "éléphant", de: "Elefant", ja: "象 (ぞう)", ko: "코끼리", zh: "大象", pt: "elefante", it: "elefante", ar: "فيل" },
      { en: "lion", es: "león", fr: "lion", de: "Löwe", ja: "ライオン", ko: "사자", zh: "狮子", pt: "leão", it: "leone", ar: "أسد" },
      { en: "tiger", es: "tigre", fr: "tigre", de: "Tiger", ja: "虎 (とら)", ko: "호랑이", zh: "老虎", pt: "tigre", it: "tigre", ar: "نمر" },
      { en: "bear", es: "oso", fr: "ours", de: "Bär", ja: "熊 (くま)", ko: "곰", zh: "熊", pt: "urso", it: "orso", ar: "دب" },
      { en: "monkey", es: "mono", fr: "singe", de: "Affe", ja: "猿 (さる)", ko: "원숭이", zh: "猴子", pt: "macaco", it: "scimmia", ar: "قرد" },
      { en: "snake", es: "serpiente", fr: "serpent", de: "Schlange", ja: "蛇 (へび)", ko: "뱀", zh: "蛇", pt: "cobra", it: "serpente", ar: "ثعبان" },
      { en: "frog", es: "rana", fr: "grenouille", de: "Frosch", ja: "カエル", ko: "개구리", zh: "青蛙", pt: "sapo", it: "rana", ar: "ضفدع" },
      { en: "turtle", es: "tortuga", fr: "tortue", de: "Schildkröte", ja: "亀 (かめ)", ko: "거북이", zh: "乌龟", pt: "tartaruga", it: "tartaruga", ar: "سلحفاة" },
      { en: "whale", es: "ballena", fr: "baleine", de: "Wal", ja: "クジラ", ko: "고래", zh: "鲸鱼", pt: "baleia", it: "balena", ar: "حوت" },
      { en: "dolphin", es: "delfín", fr: "dauphin", de: "Delfin", ja: "イルカ", ko: "돌고래", zh: "海豚", pt: "golfinho", it: "delfino", ar: "دلفين" },
      { en: "butterfly", es: "mariposa", fr: "papillon", de: "Schmetterling", ja: "蝶 (ちょう)", ko: "나비", zh: "蝴蝶", pt: "borboleta", it: "farfalla", ar: "فراشة" },
      { en: "bee", es: "abeja", fr: "abeille", de: "Biene", ja: "蜂 (はち)", ko: "벌", zh: "蜜蜂", pt: "abelha", it: "ape", ar: "نحلة" },
      { en: "ant", es: "hormiga", fr: "fourmi", de: "Ameise", ja: "アリ", ko: "개미", zh: "蚂蚁", pt: "formiga", it: "formica", ar: "نملة" },
      { en: "spider", es: "araña", fr: "araignée", de: "Spinne", ja: "クモ", ko: "거미", zh: "蜘蛛", pt: "aranha", it: "ragno", ar: "عنكبوت" },
      { en: "wolf", es: "lobo", fr: "loup", de: "Wolf", ja: "オオカミ", ko: "늑대", zh: "狼", pt: "lobo", it: "lupo", ar: "ذئب" },
      { en: "fox", es: "zorro", fr: "renard", de: "Fuchs", ja: "キツネ", ko: "여우", zh: "狐狸", pt: "raposa", it: "volpe", ar: "ثعلب" },
      { en: "deer", es: "ciervo", fr: "cerf", de: "Hirsch", ja: "鹿 (しか)", ko: "사슴", zh: "鹿", pt: "cervo", it: "cervo", ar: "غزال" },
      { en: "eagle", es: "águila", fr: "aigle", de: "Adler", ja: "ワシ", ko: "독수리", zh: "鹰", pt: "águia", it: "aquila", ar: "نسر" }
    ]
  },
  {
    name: "Food & Drinks",
    icon: "🍔",
    words: [
      { en: "water", es: "agua", fr: "eau", de: "Wasser", ja: "水 (みず)", ko: "물", zh: "水", pt: "água", it: "acqua", ar: "ماء" },
      { en: "bread", es: "pan", fr: "pain", de: "Brot", ja: "パン", ko: "빵", zh: "面包", pt: "pão", it: "pane", ar: "خبز" },
      { en: "rice", es: "arroz", fr: "riz", de: "Reis", ja: "ご飯 (ごはん)", ko: "밥", zh: "米饭", pt: "arroz", it: "riso", ar: "أرز" },
      { en: "meat", es: "carne", fr: "viande", de: "Fleisch", ja: "肉 (にく)", ko: "고기", zh: "肉", pt: "carne", it: "carne", ar: "لحم" },
      { en: "egg", es: "huevo", fr: "œuf", de: "Ei", ja: "卵 (たまご)", ko: "달걀", zh: "鸡蛋", pt: "ovo", it: "uovo", ar: "بيضة" },
      { en: "milk", es: "leche", fr: "lait", de: "Milch", ja: "牛乳 (ぎゅうにゅう)", ko: "우유", zh: "牛奶", pt: "leite", it: "latte", ar: "حليب" },
      { en: "cheese", es: "queso", fr: "fromage", de: "Käse", ja: "チーズ", ko: "치즈", zh: "奶酪", pt: "queijo", it: "formaggio", ar: "جبن" },
      { en: "butter", es: "mantequilla", fr: "beurre", de: "Butter", ja: "バター", ko: "버터", zh: "黄油", pt: "manteiga", it: "burro", ar: "زبدة" },
      { en: "sugar", es: "azúcar", fr: "sucre", de: "Zucker", ja: "砂糖 (さとう)", ko: "설탕", zh: "糖", pt: "açúcar", it: "zucchero", ar: "سكر" },
      { en: "salt", es: "sal", fr: "sel", de: "Salz", ja: "塩 (しお)", ko: "소금", zh: "盐", pt: "sal", it: "sale", ar: "ملح" },
      { en: "apple", es: "manzana", fr: "pomme", de: "Apfel", ja: "りんご", ko: "사과", zh: "苹果", pt: "maçã", it: "mela", ar: "تفاحة" },
      { en: "banana", es: "plátano", fr: "banane", de: "Banane", ja: "バナナ", ko: "바나나", zh: "香蕉", pt: "banana", it: "banana", ar: "موز" },
      { en: "orange (fruit)", es: "naranja", fr: "orange", de: "Orange", ja: "オレンジ", ko: "오렌지", zh: "橙子", pt: "laranja", it: "arancia", ar: "برتقال" },
      { en: "grape", es: "uva", fr: "raisin", de: "Traube", ja: "ぶどう", ko: "포도", zh: "葡萄", pt: "uva", it: "uva", ar: "عنب" },
      { en: "strawberry", es: "fresa", fr: "fraise", de: "Erdbeere", ja: "いちご", ko: "딸기", zh: "草莓", pt: "morango", it: "fragola", ar: "فراولة" },
      { en: "tomato", es: "tomate", fr: "tomate", de: "Tomate", ja: "トマト", ko: "토마토", zh: "番茄", pt: "tomate", it: "pomodoro", ar: "طماطم" },
      { en: "potato", es: "patata", fr: "pomme de terre", de: "Kartoffel", ja: "じゃがいも", ko: "감자", zh: "土豆", pt: "batata", it: "patata", ar: "بطاطا" },
      { en: "onion", es: "cebolla", fr: "oignon", de: "Zwiebel", ja: "玉ねぎ", ko: "양파", zh: "洋葱", pt: "cebola", it: "cipolla", ar: "بصل" },
      { en: "carrot", es: "zanahoria", fr: "carotte", de: "Karotte", ja: "にんじん", ko: "당근", zh: "胡萝卜", pt: "cenoura", it: "carota", ar: "جزر" },
      { en: "pepper", es: "pimiento", fr: "poivron", de: "Paprika", ja: "ピーマン", ko: "고추", zh: "辣椒", pt: "pimentão", it: "peperone", ar: "فلفل" },
      { en: "coffee", es: "café", fr: "café", de: "Kaffee", ja: "コーヒー", ko: "커피", zh: "咖啡", pt: "café", it: "caffè", ar: "قهوة" },
      { en: "tea", es: "té", fr: "thé", de: "Tee", ja: "お茶 (おちゃ)", ko: "차", zh: "茶", pt: "chá", it: "tè", ar: "شاي" },
      { en: "juice", es: "jugo", fr: "jus", de: "Saft", ja: "ジュース", ko: "주스", zh: "果汁", pt: "suco", it: "succo", ar: "عصير" },
      { en: "soup", es: "sopa", fr: "soupe", de: "Suppe", ja: "スープ", ko: "수프", zh: "汤", pt: "sopa", it: "zuppa", ar: "حساء" },
      { en: "salad", es: "ensalada", fr: "salade", de: "Salat", ja: "サラダ", ko: "샐러드", zh: "沙拉", pt: "salada", it: "insalata", ar: "سلطة" },
      { en: "cake", es: "pastel", fr: "gâteau", de: "Kuchen", ja: "ケーキ", ko: "케이크", zh: "蛋糕", pt: "bolo", it: "torta", ar: "كعكة" },
      { en: "chocolate", es: "chocolate", fr: "chocolat", de: "Schokolade", ja: "チョコレート", ko: "초콜릿", zh: "巧克力", pt: "chocolate", it: "cioccolato", ar: "شوكولاتة" },
      { en: "ice cream", es: "helado", fr: "glace", de: "Eis", ja: "アイスクリーム", ko: "아이스크림", zh: "冰淇淋", pt: "sorvete", it: "gelato", ar: "آيس كريم" },
      { en: "oil", es: "aceite", fr: "huile", de: "Öl", ja: "油 (あぶら)", ko: "기름", zh: "油", pt: "óleo", it: "olio", ar: "زيت" },
      { en: "flour", es: "harina", fr: "farine", de: "Mehl", ja: "小麦粉", ko: "밀가루", zh: "面粉", pt: "farinha", it: "farina", ar: "دقيق" },
      { en: "noodle", es: "fideo", fr: "nouille", de: "Nudel", ja: "麺 (めん)", ko: "국수", zh: "面条", pt: "macarrão", it: "pasta", ar: "معكرونة" },
      { en: "bean", es: "frijol", fr: "haricot", de: "Bohne", ja: "豆 (まめ)", ko: "콩", zh: "豆", pt: "feijão", it: "fagiolo", ar: "فاصوليا" },
      { en: "mushroom", es: "champiñón", fr: "champignon", de: "Pilz", ja: "きのこ", ko: "버섯", zh: "蘑菇", pt: "cogumelo", it: "fungo", ar: "فطر" },
      { en: "garlic", es: "ajo", fr: "ail", de: "Knoblauch", ja: "にんにく", ko: "마늘", zh: "大蒜", pt: "alho", it: "aglio", ar: "ثوم" },
      { en: "lemon", es: "limón", fr: "citron", de: "Zitrone", ja: "レモン", ko: "레몬", zh: "柠檬", pt: "limão", it: "limone", ar: "ليمون" }
    ]
  },
  {
    name: "Family",
    icon: "👨‍👩‍👧‍👦",
    words: [
      { en: "mother", es: "madre", fr: "mère", de: "Mutter", ja: "母 (はは)", ko: "어머니", zh: "母亲", pt: "mãe", it: "madre", ar: "أم" },
      { en: "father", es: "padre", fr: "père", de: "Vater", ja: "父 (ちち)", ko: "아버지", zh: "父亲", pt: "pai", it: "padre", ar: "أب" },
      { en: "sister", es: "hermana", fr: "sœur", de: "Schwester", ja: "姉妹 (しまい)", ko: "자매", zh: "姐妹", pt: "irmã", it: "sorella", ar: "أخت" },
      { en: "brother", es: "hermano", fr: "frère", de: "Bruder", ja: "兄弟 (きょうだい)", ko: "형제", zh: "兄弟", pt: "irmão", it: "fratello", ar: "أخ" },
      { en: "son", es: "hijo", fr: "fils", de: "Sohn", ja: "息子 (むすこ)", ko: "아들", zh: "儿子", pt: "filho", it: "figlio", ar: "ابن" },
      { en: "daughter", es: "hija", fr: "fille", de: "Tochter", ja: "娘 (むすめ)", ko: "딸", zh: "女儿", pt: "filha", it: "figlia", ar: "ابنة" },
      { en: "grandmother", es: "abuela", fr: "grand-mère", de: "Großmutter", ja: "祖母 (そぼ)", ko: "할머니", zh: "祖母", pt: "avó", it: "nonna", ar: "جدة" },
      { en: "grandfather", es: "abuelo", fr: "grand-père", de: "Großvater", ja: "祖父 (そふ)", ko: "할아버지", zh: "祖父", pt: "avô", it: "nonno", ar: "جد" },
      { en: "baby", es: "bebé", fr: "bébé", de: "Baby", ja: "赤ちゃん", ko: "아기", zh: "婴儿", pt: "bebê", it: "bambino", ar: "طفل رضيع" },
      { en: "child", es: "niño", fr: "enfant", de: "Kind", ja: "子供 (こども)", ko: "아이", zh: "孩子", pt: "criança", it: "bambino", ar: "طفل" },
      { en: "husband", es: "esposo", fr: "mari", de: "Ehemann", ja: "夫 (おっと)", ko: "남편", zh: "丈夫", pt: "marido", it: "marito", ar: "زوج" },
      { en: "wife", es: "esposa", fr: "femme", de: "Ehefrau", ja: "妻 (つま)", ko: "아내", zh: "妻子", pt: "esposa", it: "moglie", ar: "زوجة" },
      { en: "uncle", es: "tío", fr: "oncle", de: "Onkel", ja: "おじ", ko: "삼촌", zh: "叔叔", pt: "tio", it: "zio", ar: "عم" },
      { en: "aunt", es: "tía", fr: "tante", de: "Tante", ja: "おば", ko: "이모 / 고모", zh: "阿姨", pt: "tia", it: "zia", ar: "عمة" },
      { en: "cousin", es: "primo", fr: "cousin", de: "Cousin", ja: "いとこ", ko: "사촌", zh: "表兄弟", pt: "primo", it: "cugino", ar: "ابن عم" },
      { en: "friend", es: "amigo", fr: "ami", de: "Freund", ja: "友達 (ともだち)", ko: "친구", zh: "朋友", pt: "amigo", it: "amico", ar: "صديق" },
      { en: "neighbor", es: "vecino", fr: "voisin", de: "Nachbar", ja: "隣人 (りんじん)", ko: "이웃", zh: "邻居", pt: "vizinho", it: "vicino", ar: "جار" },
      { en: "family", es: "familia", fr: "famille", de: "Familie", ja: "家族 (かぞく)", ko: "가족", zh: "家庭", pt: "família", it: "famiglia", ar: "عائلة" },
      { en: "person", es: "persona", fr: "personne", de: "Person", ja: "人 (ひと)", ko: "사람", zh: "人", pt: "pessoa", it: "persona", ar: "شخص" },
      { en: "man", es: "hombre", fr: "homme", de: "Mann", ja: "男 (おとこ)", ko: "남자", zh: "男人", pt: "homem", it: "uomo", ar: "رجل" },
      { en: "woman", es: "mujer", fr: "femme", de: "Frau", ja: "女 (おんな)", ko: "여자", zh: "女人", pt: "mulher", it: "donna", ar: "امرأة" }
    ]
  },
  {
    name: "Body Parts",
    icon: "🫀",
    words: [
      { en: "head", es: "cabeza", fr: "tête", de: "Kopf", ja: "頭 (あたま)", ko: "머리", zh: "头", pt: "cabeça", it: "testa", ar: "رأس" },
      { en: "hair", es: "cabello", fr: "cheveux", de: "Haar", ja: "髪 (かみ)", ko: "머리카락", zh: "头发", pt: "cabelo", it: "capelli", ar: "شعر" },
      { en: "face", es: "cara", fr: "visage", de: "Gesicht", ja: "顔 (かお)", ko: "얼굴", zh: "脸", pt: "rosto", it: "faccia", ar: "وجه" },
      { en: "eye", es: "ojo", fr: "œil", de: "Auge", ja: "目 (め)", ko: "눈", zh: "眼睛", pt: "olho", it: "occhio", ar: "عين" },
      { en: "ear", es: "oreja", fr: "oreille", de: "Ohr", ja: "耳 (みみ)", ko: "귀", zh: "耳朵", pt: "orelha", it: "orecchio", ar: "أذن" },
      { en: "nose", es: "nariz", fr: "nez", de: "Nase", ja: "鼻 (はな)", ko: "코", zh: "鼻子", pt: "nariz", it: "naso", ar: "أنف" },
      { en: "mouth", es: "boca", fr: "bouche", de: "Mund", ja: "口 (くち)", ko: "입", zh: "嘴", pt: "boca", it: "bocca", ar: "فم" },
      { en: "tooth", es: "diente", fr: "dent", de: "Zahn", ja: "歯 (は)", ko: "이", zh: "牙齿", pt: "dente", it: "dente", ar: "سن" },
      { en: "tongue", es: "lengua", fr: "langue", de: "Zunge", ja: "舌 (した)", ko: "혀", zh: "舌头", pt: "língua", it: "lingua", ar: "لسان" },
      { en: "neck", es: "cuello", fr: "cou", de: "Hals", ja: "首 (くび)", ko: "목", zh: "脖子", pt: "pescoço", it: "collo", ar: "رقبة" },
      { en: "shoulder", es: "hombro", fr: "épaule", de: "Schulter", ja: "肩 (かた)", ko: "어깨", zh: "肩膀", pt: "ombro", it: "spalla", ar: "كتف" },
      { en: "arm", es: "brazo", fr: "bras", de: "Arm", ja: "腕 (うで)", ko: "팔", zh: "手臂", pt: "braço", it: "braccio", ar: "ذراع" },
      { en: "hand", es: "mano", fr: "main", de: "Hand", ja: "手 (て)", ko: "손", zh: "手", pt: "mão", it: "mano", ar: "يد" },
      { en: "finger", es: "dedo", fr: "doigt", de: "Finger", ja: "指 (ゆび)", ko: "손가락", zh: "手指", pt: "dedo", it: "dito", ar: "إصبع" },
      { en: "chest", es: "pecho", fr: "poitrine", de: "Brust", ja: "胸 (むね)", ko: "가슴", zh: "胸", pt: "peito", it: "petto", ar: "صدر" },
      { en: "back", es: "espalda", fr: "dos", de: "Rücken", ja: "背中 (せなか)", ko: "등", zh: "背", pt: "costas", it: "schiena", ar: "ظهر" },
      { en: "stomach", es: "estómago", fr: "estomac", de: "Magen", ja: "お腹 (おなか)", ko: "배", zh: "胃", pt: "estômago", it: "stomaco", ar: "معدة" },
      { en: "leg", es: "pierna", fr: "jambe", de: "Bein", ja: "脚 (あし)", ko: "다리", zh: "腿", pt: "perna", it: "gamba", ar: "ساق" },
      { en: "knee", es: "rodilla", fr: "genou", de: "Knie", ja: "膝 (ひざ)", ko: "무릎", zh: "膝盖", pt: "joelho", it: "ginocchio", ar: "ركبة" },
      { en: "foot", es: "pie", fr: "pied", de: "Fuß", ja: "足 (あし)", ko: "발", zh: "脚", pt: "pé", it: "piede", ar: "قدم" },
      { en: "heart", es: "corazón", fr: "cœur", de: "Herz", ja: "心臓 (しんぞう)", ko: "심장", zh: "心脏", pt: "coração", it: "cuore", ar: "قلب" },
      { en: "blood", es: "sangre", fr: "sang", de: "Blut", ja: "血 (ち)", ko: "피", zh: "血", pt: "sangue", it: "sangue", ar: "دم" },
      { en: "bone", es: "hueso", fr: "os", de: "Knochen", ja: "骨 (ほね)", ko: "뼈", zh: "骨头", pt: "osso", it: "osso", ar: "عظم" },
      { en: "skin", es: "piel", fr: "peau", de: "Haut", ja: "肌 (はだ)", ko: "피부", zh: "皮肤", pt: "pele", it: "pelle", ar: "جلد" }
    ]
  },
  {
    name: "Clothing",
    icon: "👕",
    words: [
      { en: "shirt", es: "camisa", fr: "chemise", de: "Hemd", ja: "シャツ", ko: "셔츠", zh: "衬衫", pt: "camisa", it: "camicia", ar: "قميص" },
      { en: "pants", es: "pantalones", fr: "pantalon", de: "Hose", ja: "ズボン", ko: "바지", zh: "裤子", pt: "calça", it: "pantaloni", ar: "بنطلون" },
      { en: "dress", es: "vestido", fr: "robe", de: "Kleid", ja: "ドレス", ko: "드레스", zh: "裙子", pt: "vestido", it: "vestito", ar: "فستان" },
      { en: "skirt", es: "falda", fr: "jupe", de: "Rock", ja: "スカート", ko: "치마", zh: "短裙", pt: "saia", it: "gonna", ar: "تنورة" },
      { en: "jacket", es: "chaqueta", fr: "veste", de: "Jacke", ja: "ジャケット", ko: "재킷", zh: "夹克", pt: "jaqueta", it: "giacca", ar: "سترة" },
      { en: "coat", es: "abrigo", fr: "manteau", de: "Mantel", ja: "コート", ko: "코트", zh: "大衣", pt: "casaco", it: "cappotto", ar: "معطف" },
      { en: "shoes", es: "zapatos", fr: "chaussures", de: "Schuhe", ja: "靴 (くつ)", ko: "신발", zh: "鞋子", pt: "sapatos", it: "scarpe", ar: "أحذية" },
      { en: "boots", es: "botas", fr: "bottes", de: "Stiefel", ja: "ブーツ", ko: "부츠", zh: "靴子", pt: "botas", it: "stivali", ar: "جزمة" },
      { en: "hat", es: "sombrero", fr: "chapeau", de: "Hut", ja: "帽子 (ぼうし)", ko: "모자", zh: "帽子", pt: "chapéu", it: "cappello", ar: "قبعة" },
      { en: "socks", es: "calcetines", fr: "chaussettes", de: "Socken", ja: "靴下 (くつした)", ko: "양말", zh: "袜子", pt: "meias", it: "calzini", ar: "جوارب" },
      { en: "gloves", es: "guantes", fr: "gants", de: "Handschuhe", ja: "手袋 (てぶくろ)", ko: "장갑", zh: "手套", pt: "luvas", it: "guanti", ar: "قفازات" },
      { en: "scarf", es: "bufanda", fr: "écharpe", de: "Schal", ja: "マフラー", ko: "스카프", zh: "围巾", pt: "cachecol", it: "sciarpa", ar: "وشاح" },
      { en: "belt", es: "cinturón", fr: "ceinture", de: "Gürtel", ja: "ベルト", ko: "벨트", zh: "腰带", pt: "cinto", it: "cintura", ar: "حزام" },
      { en: "bag", es: "bolsa", fr: "sac", de: "Tasche", ja: "かばん", ko: "가방", zh: "包", pt: "bolsa", it: "borsa", ar: "حقيبة" },
      { en: "umbrella", es: "paraguas", fr: "parapluie", de: "Regenschirm", ja: "傘 (かさ)", ko: "우산", zh: "雨伞", pt: "guarda-chuva", it: "ombrello", ar: "مظلة" }
    ]
  },
  {
    name: "Time & Calendar",
    icon: "📅",
    words: [
      { en: "today", es: "hoy", fr: "aujourd'hui", de: "heute", ja: "今日 (きょう)", ko: "오늘", zh: "今天", pt: "hoje", it: "oggi", ar: "اليوم" },
      { en: "tomorrow", es: "mañana", fr: "demain", de: "morgen", ja: "明日 (あした)", ko: "내일", zh: "明天", pt: "amanhã", it: "domani", ar: "غدا" },
      { en: "yesterday", es: "ayer", fr: "hier", de: "gestern", ja: "昨日 (きのう)", ko: "어제", zh: "昨天", pt: "ontem", it: "ieri", ar: "أمس" },
      { en: "morning", es: "mañana", fr: "matin", de: "Morgen", ja: "朝 (あさ)", ko: "아침", zh: "早上", pt: "manhã", it: "mattina", ar: "صباح" },
      { en: "afternoon", es: "tarde", fr: "après-midi", de: "Nachmittag", ja: "午後 (ごご)", ko: "오후", zh: "下午", pt: "tarde", it: "pomeriggio", ar: "بعد الظهر" },
      { en: "evening", es: "noche", fr: "soir", de: "Abend", ja: "夕方 (ゆうがた)", ko: "저녁", zh: "傍晚", pt: "noite", it: "sera", ar: "مساء" },
      { en: "night", es: "noche", fr: "nuit", de: "Nacht", ja: "夜 (よる)", ko: "밤", zh: "夜晚", pt: "noite", it: "notte", ar: "ليل" },
      { en: "Monday", es: "lunes", fr: "lundi", de: "Montag", ja: "月曜日", ko: "월요일", zh: "星期一", pt: "segunda-feira", it: "lunedì", ar: "الإثنين" },
      { en: "Tuesday", es: "martes", fr: "mardi", de: "Dienstag", ja: "火曜日", ko: "화요일", zh: "星期二", pt: "terça-feira", it: "martedì", ar: "الثلاثاء" },
      { en: "Wednesday", es: "miércoles", fr: "mercredi", de: "Mittwoch", ja: "水曜日", ko: "수요일", zh: "星期三", pt: "quarta-feira", it: "mercoledì", ar: "الأربعاء" },
      { en: "Thursday", es: "jueves", fr: "jeudi", de: "Donnerstag", ja: "木曜日", ko: "목요일", zh: "星期四", pt: "quinta-feira", it: "giovedì", ar: "الخميس" },
      { en: "Friday", es: "viernes", fr: "vendredi", de: "Freitag", ja: "金曜日", ko: "금요일", zh: "星期五", pt: "sexta-feira", it: "venerdì", ar: "الجمعة" },
      { en: "Saturday", es: "sábado", fr: "samedi", de: "Samstag", ja: "土曜日", ko: "토요일", zh: "星期六", pt: "sábado", it: "sabato", ar: "السبت" },
      { en: "Sunday", es: "domingo", fr: "dimanche", de: "Sonntag", ja: "日曜日", ko: "일요일", zh: "星期日", pt: "domingo", it: "domenica", ar: "الأحد" },
      { en: "January", es: "enero", fr: "janvier", de: "Januar", ja: "一月", ko: "일월", zh: "一月", pt: "janeiro", it: "gennaio", ar: "يناير" },
      { en: "February", es: "febrero", fr: "février", de: "Februar", ja: "二月", ko: "이월", zh: "二月", pt: "fevereiro", it: "febbraio", ar: "فبراير" },
      { en: "March", es: "marzo", fr: "mars", de: "März", ja: "三月", ko: "삼월", zh: "三月", pt: "março", it: "marzo", ar: "مارس" },
      { en: "April", es: "abril", fr: "avril", de: "April", ja: "四月", ko: "사월", zh: "四月", pt: "abril", it: "aprile", ar: "أبريل" },
      { en: "May", es: "mayo", fr: "mai", de: "Mai", ja: "五月", ko: "오월", zh: "五月", pt: "maio", it: "maggio", ar: "مايو" },
      { en: "June", es: "junio", fr: "juin", de: "Juni", ja: "六月", ko: "유월", zh: "六月", pt: "junho", it: "giugno", ar: "يونيو" },
      { en: "year", es: "año", fr: "an / année", de: "Jahr", ja: "年 (ねん)", ko: "년", zh: "年", pt: "ano", it: "anno", ar: "سنة" },
      { en: "month", es: "mes", fr: "mois", de: "Monat", ja: "月 (つき)", ko: "달", zh: "月", pt: "mês", it: "mese", ar: "شهر" },
      { en: "week", es: "semana", fr: "semaine", de: "Woche", ja: "週 (しゅう)", ko: "주", zh: "周", pt: "semana", it: "settimana", ar: "أسبوع" },
      { en: "day", es: "día", fr: "jour", de: "Tag", ja: "日 (ひ)", ko: "일", zh: "天", pt: "dia", it: "giorno", ar: "يوم" },
      { en: "hour", es: "hora", fr: "heure", de: "Stunde", ja: "時間 (じかん)", ko: "시간", zh: "小时", pt: "hora", it: "ora", ar: "ساعة" },
      { en: "minute", es: "minuto", fr: "minute", de: "Minute", ja: "分 (ふん)", ko: "분", zh: "分钟", pt: "minuto", it: "minuto", ar: "دقيقة" },
      { en: "now", es: "ahora", fr: "maintenant", de: "jetzt", ja: "今 (いま)", ko: "지금", zh: "现在", pt: "agora", it: "adesso", ar: "الآن" },
      { en: "always", es: "siempre", fr: "toujours", de: "immer", ja: "いつも", ko: "항상", zh: "总是", pt: "sempre", it: "sempre", ar: "دائما" },
      { en: "never", es: "nunca", fr: "jamais", de: "nie", ja: "決して", ko: "절대", zh: "从不", pt: "nunca", it: "mai", ar: "أبدا" }
    ]
  },
  {
    name: "Weather & Nature",
    icon: "🌤️",
    words: [
      { en: "sun", es: "sol", fr: "soleil", de: "Sonne", ja: "太陽 (たいよう)", ko: "태양", zh: "太阳", pt: "sol", it: "sole", ar: "شمس" },
      { en: "moon", es: "luna", fr: "lune", de: "Mond", ja: "月 (つき)", ko: "달", zh: "月亮", pt: "lua", it: "luna", ar: "قمر" },
      { en: "star", es: "estrella", fr: "étoile", de: "Stern", ja: "星 (ほし)", ko: "별", zh: "星星", pt: "estrela", it: "stella", ar: "نجمة" },
      { en: "sky", es: "cielo", fr: "ciel", de: "Himmel", ja: "空 (そら)", ko: "하늘", zh: "天空", pt: "céu", it: "cielo", ar: "سماء" },
      { en: "cloud", es: "nube", fr: "nuage", de: "Wolke", ja: "雲 (くも)", ko: "구름", zh: "云", pt: "nuvem", it: "nuvola", ar: "سحابة" },
      { en: "rain", es: "lluvia", fr: "pluie", de: "Regen", ja: "雨 (あめ)", ko: "비", zh: "雨", pt: "chuva", it: "pioggia", ar: "مطر" },
      { en: "snow", es: "nieve", fr: "neige", de: "Schnee", ja: "雪 (ゆき)", ko: "눈", zh: "雪", pt: "neve", it: "neve", ar: "ثلج" },
      { en: "wind", es: "viento", fr: "vent", de: "Wind", ja: "風 (かぜ)", ko: "바람", zh: "风", pt: "vento", it: "vento", ar: "رياح" },
      { en: "storm", es: "tormenta", fr: "tempête", de: "Sturm", ja: "嵐 (あらし)", ko: "폭풍", zh: "暴风雨", pt: "tempestade", it: "tempesta", ar: "عاصفة" },
      { en: "hot", es: "caliente", fr: "chaud", de: "heiß", ja: "暑い (あつい)", ko: "더운", zh: "热", pt: "quente", it: "caldo", ar: "حار" },
      { en: "cold", es: "frío", fr: "froid", de: "kalt", ja: "寒い (さむい)", ko: "추운", zh: "冷", pt: "frio", it: "freddo", ar: "بارد" },
      { en: "tree", es: "árbol", fr: "arbre", de: "Baum", ja: "木 (き)", ko: "나무", zh: "树", pt: "árvore", it: "albero", ar: "شجرة" },
      { en: "flower", es: "flor", fr: "fleur", de: "Blume", ja: "花 (はな)", ko: "꽃", zh: "花", pt: "flor", it: "fiore", ar: "زهرة" },
      { en: "grass", es: "hierba", fr: "herbe", de: "Gras", ja: "草 (くさ)", ko: "풀", zh: "草", pt: "grama", it: "erba", ar: "عشب" },
      { en: "mountain", es: "montaña", fr: "montagne", de: "Berg", ja: "山 (やま)", ko: "산", zh: "山", pt: "montanha", it: "montagna", ar: "جبل" },
      { en: "river", es: "río", fr: "rivière", de: "Fluss", ja: "川 (かわ)", ko: "강", zh: "河", pt: "rio", it: "fiume", ar: "نهر" },
      { en: "sea", es: "mar", fr: "mer", de: "Meer", ja: "海 (うみ)", ko: "바다", zh: "海", pt: "mar", it: "mare", ar: "بحر" },
      { en: "lake", es: "lago", fr: "lac", de: "See", ja: "湖 (みずうみ)", ko: "호수", zh: "湖", pt: "lago", it: "lago", ar: "بحيرة" },
      { en: "forest", es: "bosque", fr: "forêt", de: "Wald", ja: "森 (もり)", ko: "숲", zh: "森林", pt: "floresta", it: "foresta", ar: "غابة" },
      { en: "island", es: "isla", fr: "île", de: "Insel", ja: "島 (しま)", ko: "섬", zh: "岛", pt: "ilha", it: "isola", ar: "جزيرة" },
      { en: "earth", es: "tierra", fr: "terre", de: "Erde", ja: "地球 (ちきゅう)", ko: "지구", zh: "地球", pt: "terra", it: "terra", ar: "أرض" },
      { en: "fire", es: "fuego", fr: "feu", de: "Feuer", ja: "火 (ひ)", ko: "불", zh: "火", pt: "fogo", it: "fuoco", ar: "نار" },
      { en: "ice", es: "hielo", fr: "glace", de: "Eis", ja: "氷 (こおり)", ko: "얼음", zh: "冰", pt: "gelo", it: "ghiaccio", ar: "جليد" },
      { en: "stone", es: "piedra", fr: "pierre", de: "Stein", ja: "石 (いし)", ko: "돌", zh: "石头", pt: "pedra", it: "pietra", ar: "حجر" },
      { en: "sand", es: "arena", fr: "sable", de: "Sand", ja: "砂 (すな)", ko: "모래", zh: "沙", pt: "areia", it: "sabbia", ar: "رمل" }
    ]
  },
  {
    name: "House & Home",
    icon: "🏠",
    words: [
      { en: "house", es: "casa", fr: "maison", de: "Haus", ja: "家 (いえ)", ko: "집", zh: "房子", pt: "casa", it: "casa", ar: "منزل" },
      { en: "door", es: "puerta", fr: "porte", de: "Tür", ja: "ドア", ko: "문", zh: "门", pt: "porta", it: "porta", ar: "باب" },
      { en: "window", es: "ventana", fr: "fenêtre", de: "Fenster", ja: "窓 (まど)", ko: "창문", zh: "窗户", pt: "janela", it: "finestra", ar: "نافذة" },
      { en: "room", es: "habitación", fr: "chambre", de: "Zimmer", ja: "部屋 (へや)", ko: "방", zh: "房间", pt: "quarto", it: "stanza", ar: "غرفة" },
      { en: "kitchen", es: "cocina", fr: "cuisine", de: "Küche", ja: "台所 (だいどころ)", ko: "부엌", zh: "厨房", pt: "cozinha", it: "cucina", ar: "مطبخ" },
      { en: "bathroom", es: "baño", fr: "salle de bain", de: "Badezimmer", ja: "浴室 (よくしつ)", ko: "욕실", zh: "浴室", pt: "banheiro", it: "bagno", ar: "حمام" },
      { en: "bedroom", es: "dormitorio", fr: "chambre à coucher", de: "Schlafzimmer", ja: "寝室 (しんしつ)", ko: "침실", zh: "卧室", pt: "quarto", it: "camera da letto", ar: "غرفة نوم" },
      { en: "table", es: "mesa", fr: "table", de: "Tisch", ja: "テーブル", ko: "탁자", zh: "桌子", pt: "mesa", it: "tavolo", ar: "طاولة" },
      { en: "chair", es: "silla", fr: "chaise", de: "Stuhl", ja: "椅子 (いす)", ko: "의자", zh: "椅子", pt: "cadeira", it: "sedia", ar: "كرسي" },
      { en: "bed", es: "cama", fr: "lit", de: "Bett", ja: "ベッド", ko: "침대", zh: "床", pt: "cama", it: "letto", ar: "سرير" },
      { en: "mirror", es: "espejo", fr: "miroir", de: "Spiegel", ja: "鏡 (かがみ)", ko: "거울", zh: "镜子", pt: "espelho", it: "specchio", ar: "مرآة" },
      { en: "lamp", es: "lámpara", fr: "lampe", de: "Lampe", ja: "ランプ", ko: "램프", zh: "灯", pt: "lâmpada", it: "lampada", ar: "مصباح" },
      { en: "stairs", es: "escaleras", fr: "escalier", de: "Treppe", ja: "階段 (かいだん)", ko: "계단", zh: "楼梯", pt: "escada", it: "scale", ar: "درج" },
      { en: "wall", es: "pared", fr: "mur", de: "Wand", ja: "壁 (かべ)", ko: "벽", zh: "墙", pt: "parede", it: "muro", ar: "جدار" },
      { en: "floor", es: "suelo", fr: "sol", de: "Boden", ja: "床 (ゆか)", ko: "바닥", zh: "地板", pt: "chão", it: "pavimento", ar: "أرضية" },
      { en: "roof", es: "techo", fr: "toit", de: "Dach", ja: "屋根 (やね)", ko: "지붕", zh: "屋顶", pt: "telhado", it: "tetto", ar: "سقف" },
      { en: "garden", es: "jardín", fr: "jardin", de: "Garten", ja: "庭 (にわ)", ko: "정원", zh: "花园", pt: "jardim", it: "giardino", ar: "حديقة" },
      { en: "key", es: "llave", fr: "clé", de: "Schlüssel", ja: "鍵 (かぎ)", ko: "열쇠", zh: "钥匙", pt: "chave", it: "chiave", ar: "مفتاح" },
      { en: "clock", es: "reloj", fr: "horloge", de: "Uhr", ja: "時計 (とけい)", ko: "시계", zh: "时钟", pt: "relógio", it: "orologio", ar: "ساعة حائط" },
      { en: "telephone", es: "teléfono", fr: "téléphone", de: "Telefon", ja: "電話 (でんわ)", ko: "전화", zh: "电话", pt: "telefone", it: "telefono", ar: "هاتف" }
    ]
  },
  {
    name: "Transportation",
    icon: "🚗",
    words: [
      { en: "car", es: "coche", fr: "voiture", de: "Auto", ja: "車 (くるま)", ko: "자동차", zh: "汽车", pt: "carro", it: "macchina", ar: "سيارة" },
      { en: "bus", es: "autobús", fr: "bus", de: "Bus", ja: "バス", ko: "버스", zh: "公共汽车", pt: "ônibus", it: "autobus", ar: "حافلة" },
      { en: "train", es: "tren", fr: "train", de: "Zug", ja: "電車 (でんしゃ)", ko: "기차", zh: "火车", pt: "trem", it: "treno", ar: "قطار" },
      { en: "airplane", es: "avión", fr: "avion", de: "Flugzeug", ja: "飛行機 (ひこうき)", ko: "비행기", zh: "飞机", pt: "avião", it: "aereo", ar: "طائرة" },
      { en: "bicycle", es: "bicicleta", fr: "vélo", de: "Fahrrad", ja: "自転車 (じてんしゃ)", ko: "자전거", zh: "自行车", pt: "bicicleta", it: "bicicletta", ar: "دراجة" },
      { en: "boat", es: "barco", fr: "bateau", de: "Boot", ja: "船 (ふね)", ko: "배", zh: "船", pt: "barco", it: "barca", ar: "قارب" },
      { en: "ship", es: "buque", fr: "navire", de: "Schiff", ja: "船 (ふね)", ko: "배", zh: "船", pt: "navio", it: "nave", ar: "سفينة" },
      { en: "taxi", es: "taxi", fr: "taxi", de: "Taxi", ja: "タクシー", ko: "택시", zh: "出租车", pt: "táxi", it: "taxi", ar: "سيارة أجرة" },
      { en: "motorcycle", es: "motocicleta", fr: "moto", de: "Motorrad", ja: "バイク", ko: "오토바이", zh: "摩托车", pt: "motocicleta", it: "moto", ar: "دراجة نارية" },
      { en: "truck", es: "camión", fr: "camion", de: "Lastwagen", ja: "トラック", ko: "트럭", zh: "卡车", pt: "caminhão", it: "camion", ar: "شاحنة" },
      { en: "subway", es: "metro", fr: "métro", de: "U-Bahn", ja: "地下鉄 (ちかてつ)", ko: "지하철", zh: "地铁", pt: "metrô", it: "metropolitana", ar: "مترو" },
      { en: "road", es: "camino", fr: "route", de: "Straße", ja: "道 (みち)", ko: "길", zh: "路", pt: "estrada", it: "strada", ar: "طريق" },
      { en: "bridge", es: "puente", fr: "pont", de: "Brücke", ja: "橋 (はし)", ko: "다리", zh: "桥", pt: "ponte", it: "ponte", ar: "جسر" },
      { en: "ticket", es: "billete", fr: "billet", de: "Fahrkarte", ja: "切符 (きっぷ)", ko: "표", zh: "票", pt: "bilhete", it: "biglietto", ar: "تذكرة" },
      { en: "map", es: "mapa", fr: "carte", de: "Karte", ja: "地図 (ちず)", ko: "지도", zh: "地图", pt: "mapa", it: "mappa", ar: "خريطة" }
    ]
  },
  {
    name: "Occupations",
    icon: "👨‍💼",
    words: [
      { en: "teacher", es: "profesor", fr: "professeur", de: "Lehrer", ja: "先生 (せんせい)", ko: "선생님", zh: "老师", pt: "professor", it: "insegnante", ar: "معلم" },
      { en: "doctor", es: "doctor", fr: "médecin", de: "Arzt", ja: "医者 (いしゃ)", ko: "의사", zh: "医生", pt: "médico", it: "dottore", ar: "طبيب" },
      { en: "nurse", es: "enfermera", fr: "infirmière", de: "Krankenschwester", ja: "看護師 (かんごし)", ko: "간호사", zh: "护士", pt: "enfermeira", it: "infermiere", ar: "ممرض" },
      { en: "engineer", es: "ingeniero", fr: "ingénieur", de: "Ingenieur", ja: "エンジニア", ko: "엔지니어", zh: "工程师", pt: "engenheiro", it: "ingegnere", ar: "مهندس" },
      { en: "student", es: "estudiante", fr: "étudiant", de: "Student", ja: "学生 (がくせい)", ko: "학생", zh: "学生", pt: "estudante", it: "studente", ar: "طالب" },
      { en: "police", es: "policía", fr: "police", de: "Polizei", ja: "警察 (けいさつ)", ko: "경찰", zh: "警察", pt: "polícia", it: "polizia", ar: "شرطة" },
      { en: "farmer", es: "agricultor", fr: "agriculteur", de: "Bauer", ja: "農家 (のうか)", ko: "농부", zh: "农民", pt: "agricultor", it: "agricoltore", ar: "مزارع" },
      { en: "cook", es: "cocinero", fr: "cuisinier", de: "Koch", ja: "料理人 (りょうりにん)", ko: "요리사", zh: "厨师", pt: "cozinheiro", it: "cuoco", ar: "طباخ" },
      { en: "driver", es: "conductor", fr: "chauffeur", de: "Fahrer", ja: "運転手 (うんてんしゅ)", ko: "운전사", zh: "司机", pt: "motorista", it: "autista", ar: "سائق" },
      { en: "lawyer", es: "abogado", fr: "avocat", de: "Anwalt", ja: "弁護士 (べんごし)", ko: "변호사", zh: "律师", pt: "advogado", it: "avvocato", ar: "محامي" },
      { en: "artist", es: "artista", fr: "artiste", de: "Künstler", ja: "芸術家 (げいじゅつか)", ko: "예술가", zh: "艺术家", pt: "artista", it: "artista", ar: "فنان" },
      { en: "musician", es: "músico", fr: "musicien", de: "Musiker", ja: "音楽家 (おんがくか)", ko: "음악가", zh: "音乐家", pt: "músico", it: "musicista", ar: "موسيقي" },
      { en: "writer", es: "escritor", fr: "écrivain", de: "Schriftsteller", ja: "作家 (さっか)", ko: "작가", zh: "作家", pt: "escritor", it: "scrittore", ar: "كاتب" },
      { en: "pilot", es: "piloto", fr: "pilote", de: "Pilot", ja: "パイロット", ko: "조종사", zh: "飞行员", pt: "piloto", it: "pilota", ar: "طيار" },
      { en: "soldier", es: "soldado", fr: "soldat", de: "Soldat", ja: "兵士 (へいし)", ko: "군인", zh: "士兵", pt: "soldado", it: "soldato", ar: "جندي" }
    ]
  },
  {
    name: "Common Verbs",
    icon: "🏃",
    words: [
      { en: "to be", es: "ser / estar", fr: "être", de: "sein", ja: "です / いる", ko: "이다 / 있다", zh: "是", pt: "ser / estar", it: "essere", ar: "يكون" },
      { en: "to have", es: "tener", fr: "avoir", de: "haben", ja: "持つ (もつ)", ko: "가지다", zh: "有", pt: "ter", it: "avere", ar: "يملك" },
      { en: "to do", es: "hacer", fr: "faire", de: "tun / machen", ja: "する", ko: "하다", zh: "做", pt: "fazer", it: "fare", ar: "يفعل" },
      { en: "to go", es: "ir", fr: "aller", de: "gehen", ja: "行く (いく)", ko: "가다", zh: "去", pt: "ir", it: "andare", ar: "يذهب" },
      { en: "to come", es: "venir", fr: "venir", de: "kommen", ja: "来る (くる)", ko: "오다", zh: "来", pt: "vir", it: "venire", ar: "يأتي" },
      { en: "to say", es: "decir", fr: "dire", de: "sagen", ja: "言う (いう)", ko: "말하다", zh: "说", pt: "dizer", it: "dire", ar: "يقول" },
      { en: "to see", es: "ver", fr: "voir", de: "sehen", ja: "見る (みる)", ko: "보다", zh: "看", pt: "ver", it: "vedere", ar: "يرى" },
      { en: "to know", es: "saber / conocer", fr: "savoir / connaître", de: "wissen / kennen", ja: "知る (しる)", ko: "알다", zh: "知道", pt: "saber / conhecer", it: "sapere / conoscere", ar: "يعرف" },
      { en: "to think", es: "pensar", fr: "penser", de: "denken", ja: "思う (おもう)", ko: "생각하다", zh: "想", pt: "pensar", it: "pensare", ar: "يفكر" },
      { en: "to want", es: "querer", fr: "vouloir", de: "wollen", ja: "欲しい (ほしい)", ko: "원하다", zh: "想要", pt: "querer", it: "volere", ar: "يريد" },
      { en: "to eat", es: "comer", fr: "manger", de: "essen", ja: "食べる (たべる)", ko: "먹다", zh: "吃", pt: "comer", it: "mangiare", ar: "يأكل" },
      { en: "to drink", es: "beber", fr: "boire", de: "trinken", ja: "飲む (のむ)", ko: "마시다", zh: "喝", pt: "beber", it: "bere", ar: "يشرب" },
      { en: "to sleep", es: "dormir", fr: "dormir", de: "schlafen", ja: "寝る (ねる)", ko: "자다", zh: "睡觉", pt: "dormir", it: "dormire", ar: "ينام" },
      { en: "to walk", es: "caminar", fr: "marcher", de: "gehen", ja: "歩く (あるく)", ko: "걷다", zh: "走", pt: "andar", it: "camminare", ar: "يمشي" },
      { en: "to run", es: "correr", fr: "courir", de: "laufen", ja: "走る (はしる)", ko: "달리다", zh: "跑", pt: "correr", it: "correre", ar: "يركض" },
      { en: "to read", es: "leer", fr: "lire", de: "lesen", ja: "読む (よむ)", ko: "읽다", zh: "读", pt: "ler", it: "leggere", ar: "يقرأ" },
      { en: "to write", es: "escribir", fr: "écrire", de: "schreiben", ja: "書く (かく)", ko: "쓰다", zh: "写", pt: "escrever", it: "scrivere", ar: "يكتب" },
      { en: "to speak", es: "hablar", fr: "parler", de: "sprechen", ja: "話す (はなす)", ko: "말하다", zh: "说", pt: "falar", it: "parlare", ar: "يتكلم" },
      { en: "to listen", es: "escuchar", fr: "écouter", de: "zuhören", ja: "聞く (きく)", ko: "듣다", zh: "听", pt: "ouvir", it: "ascoltare", ar: "يستمع" },
      { en: "to understand", es: "entender", fr: "comprendre", de: "verstehen", ja: "分かる (わかる)", ko: "이해하다", zh: "理解", pt: "entender", it: "capire", ar: "يفهم" },
      { en: "to give", es: "dar", fr: "donner", de: "geben", ja: "あげる", ko: "주다", zh: "给", pt: "dar", it: "dare", ar: "يعطي" },
      { en: "to take", es: "tomar", fr: "prendre", de: "nehmen", ja: "取る (とる)", ko: "가져가다", zh: "拿", pt: "pegar", it: "prendere", ar: "يأخذ" },
      { en: "to buy", es: "comprar", fr: "acheter", de: "kaufen", ja: "買う (かう)", ko: "사다", zh: "买", pt: "comprar", it: "comprare", ar: "يشتري" },
      { en: "to sell", es: "vender", fr: "vendre", de: "verkaufen", ja: "売る (うる)", ko: "팔다", zh: "卖", pt: "vender", it: "vendere", ar: "يبيع" },
      { en: "to open", es: "abrir", fr: "ouvrir", de: "öffnen", ja: "開ける (あける)", ko: "열다", zh: "开", pt: "abrir", it: "aprire", ar: "يفتح" },
      { en: "to close", es: "cerrar", fr: "fermer", de: "schließen", ja: "閉める (しめる)", ko: "닫다", zh: "关", pt: "fechar", it: "chiudere", ar: "يغلق" },
      { en: "to sit", es: "sentarse", fr: "s'asseoir", de: "sitzen", ja: "座る (すわる)", ko: "앉다", zh: "坐", pt: "sentar", it: "sedersi", ar: "يجلس" },
      { en: "to stand", es: "estar de pie", fr: "se lever", de: "stehen", ja: "立つ (たつ)", ko: "서다", zh: "站", pt: "ficar de pé", it: "stare in piedi", ar: "يقف" },
      { en: "to love", es: "amar", fr: "aimer", de: "lieben", ja: "愛する (あいする)", ko: "사랑하다", zh: "爱", pt: "amar", it: "amare", ar: "يحب" },
      { en: "to like", es: "gustar", fr: "aimer", de: "mögen", ja: "好き (すき)", ko: "좋아하다", zh: "喜欢", pt: "gostar", it: "piacere", ar: "يعجب" },
      { en: "to help", es: "ayudar", fr: "aider", de: "helfen", ja: "助ける (たすける)", ko: "돕다", zh: "帮助", pt: "ajudar", it: "aiutare", ar: "يساعد" },
      { en: "to learn", es: "aprender", fr: "apprendre", de: "lernen", ja: "学ぶ (まなぶ)", ko: "배우다", zh: "学习", pt: "aprender", it: "imparare", ar: "يتعلم" },
      { en: "to teach", es: "enseñar", fr: "enseigner", de: "lehren", ja: "教える (おしえる)", ko: "가르치다", zh: "教", pt: "ensinar", it: "insegnare", ar: "يعلم" },
      { en: "to work", es: "trabajar", fr: "travailler", de: "arbeiten", ja: "働く (はたらく)", ko: "일하다", zh: "工作", pt: "trabalhar", it: "lavorare", ar: "يعمل" },
      { en: "to play", es: "jugar", fr: "jouer", de: "spielen", ja: "遊ぶ (あそぶ)", ko: "놀다", zh: "玩", pt: "brincar", it: "giocare", ar: "يلعب" },
      { en: "to sing", es: "cantar", fr: "chanter", de: "singen", ja: "歌う (うたう)", ko: "노래하다", zh: "唱", pt: "cantar", it: "cantare", ar: "يغني" },
      { en: "to dance", es: "bailar", fr: "danser", de: "tanzen", ja: "踊る (おどる)", ko: "춤추다", zh: "跳舞", pt: "dançar", it: "ballare", ar: "يرقص" },
      { en: "to swim", es: "nadar", fr: "nager", de: "schwimmen", ja: "泳ぐ (およぐ)", ko: "수영하다", zh: "游泳", pt: "nadar", it: "nuotare", ar: "يسبح" },
      { en: "to fly", es: "volar", fr: "voler", de: "fliegen", ja: "飛ぶ (とぶ)", ko: "날다", zh: "飞", pt: "voar", it: "volare", ar: "يطير" },
      { en: "to wait", es: "esperar", fr: "attendre", de: "warten", ja: "待つ (まつ)", ko: "기다리다", zh: "等", pt: "esperar", it: "aspettare", ar: "ينتظر" },
      { en: "to find", es: "encontrar", fr: "trouver", de: "finden", ja: "見つける (みつける)", ko: "찾다", zh: "找到", pt: "encontrar", it: "trovare", ar: "يجد" },
      { en: "to make", es: "hacer", fr: "faire", de: "machen", ja: "作る (つくる)", ko: "만들다", zh: "做", pt: "fazer", it: "fare", ar: "يصنع" },
      { en: "to put", es: "poner", fr: "mettre", de: "setzen / stellen", ja: "置く (おく)", ko: "놓다", zh: "放", pt: "pôr", it: "mettere", ar: "يضع" },
      { en: "to use", es: "usar", fr: "utiliser", de: "benutzen", ja: "使う (つかう)", ko: "사용하다", zh: "用", pt: "usar", it: "usare", ar: "يستخدم" },
      { en: "to try", es: "intentar", fr: "essayer", de: "versuchen", ja: "試す (ためす)", ko: "시도하다", zh: "试", pt: "tentar", it: "provare", ar: "يحاول" },
      { en: "to begin", es: "comenzar", fr: "commencer", de: "beginnen", ja: "始める (はじめる)", ko: "시작하다", zh: "开始", pt: "começar", it: "cominciare", ar: "يبدأ" },
      { en: "to finish", es: "terminar", fr: "finir", de: "beenden", ja: "終わる (おわる)", ko: "끝내다", zh: "结束", pt: "terminar", it: "finire", ar: "ينهي" },
      { en: "to send", es: "enviar", fr: "envoyer", de: "senden", ja: "送る (おくる)", ko: "보내다", zh: "发送", pt: "enviar", it: "mandare", ar: "يرسل" },
      { en: "to receive", es: "recibir", fr: "recevoir", de: "empfangen", ja: "受け取る (うけとる)", ko: "받다", zh: "收到", pt: "receber", it: "ricevere", ar: "يستلم" },
      { en: "to remember", es: "recordar", fr: "se souvenir", de: "sich erinnern", ja: "覚える (おぼえる)", ko: "기억하다", zh: "记住", pt: "lembrar", it: "ricordare", ar: "يتذكر" }
    ]
  },
  {
    name: "Common Adjectives",
    icon: "✨",
    words: [
      { en: "big", es: "grande", fr: "grand", de: "groß", ja: "大きい (おおきい)", ko: "큰", zh: "大", pt: "grande", it: "grande", ar: "كبير" },
      { en: "small", es: "pequeño", fr: "petit", de: "klein", ja: "小さい (ちいさい)", ko: "작은", zh: "小", pt: "pequeno", it: "piccolo", ar: "صغير" },
      { en: "long", es: "largo", fr: "long", de: "lang", ja: "長い (ながい)", ko: "긴", zh: "长", pt: "longo", it: "lungo", ar: "طويل" },
      { en: "short", es: "corto", fr: "court", de: "kurz", ja: "短い (みじかい)", ko: "짧은", zh: "短", pt: "curto", it: "corto", ar: "قصير" },
      { en: "tall", es: "alto", fr: "grand", de: "groß", ja: "高い (たかい)", ko: "키가 큰", zh: "高", pt: "alto", it: "alto", ar: "طويل القامة" },
      { en: "new", es: "nuevo", fr: "nouveau", de: "neu", ja: "新しい (あたらしい)", ko: "새로운", zh: "新", pt: "novo", it: "nuovo", ar: "جديد" },
      { en: "old", es: "viejo", fr: "vieux", de: "alt", ja: "古い (ふるい)", ko: "오래된", zh: "旧", pt: "velho", it: "vecchio", ar: "قديم" },
      { en: "good", es: "bueno", fr: "bon", de: "gut", ja: "良い (よい)", ko: "좋은", zh: "好", pt: "bom", it: "buono", ar: "جيد" },
      { en: "bad", es: "malo", fr: "mauvais", de: "schlecht", ja: "悪い (わるい)", ko: "나쁜", zh: "坏", pt: "mau", it: "cattivo", ar: "سيء" },
      { en: "beautiful", es: "hermoso", fr: "beau", de: "schön", ja: "美しい (うつくしい)", ko: "아름다운", zh: "美丽", pt: "bonito", it: "bello", ar: "جميل" },
      { en: "ugly", es: "feo", fr: "laid", de: "hässlich", ja: "醜い (みにくい)", ko: "못생긴", zh: "丑", pt: "feio", it: "brutto", ar: "قبيح" },
      { en: "fast", es: "rápido", fr: "rapide", de: "schnell", ja: "速い (はやい)", ko: "빠른", zh: "快", pt: "rápido", it: "veloce", ar: "سريع" },
      { en: "slow", es: "lento", fr: "lent", de: "langsam", ja: "遅い (おそい)", ko: "느린", zh: "慢", pt: "lento", it: "lento", ar: "بطيء" },
      { en: "heavy", es: "pesado", fr: "lourd", de: "schwer", ja: "重い (おもい)", ko: "무거운", zh: "重", pt: "pesado", it: "pesante", ar: "ثقيل" },
      { en: "easy", es: "fácil", fr: "facile", de: "einfach", ja: "簡単 (かんたん)", ko: "쉬운", zh: "容易", pt: "fácil", it: "facile", ar: "سهل" },
      { en: "difficult", es: "difícil", fr: "difficile", de: "schwierig", ja: "難しい (むずかしい)", ko: "어려운", zh: "难", pt: "difícil", it: "difficile", ar: "صعب" },
      { en: "clean", es: "limpio", fr: "propre", de: "sauber", ja: "きれい", ko: "깨끗한", zh: "干净", pt: "limpo", it: "pulito", ar: "نظيف" },
      { en: "dirty", es: "sucio", fr: "sale", de: "schmutzig", ja: "汚い (きたない)", ko: "더러운", zh: "脏", pt: "sujo", it: "sporco", ar: "قذر" },
      { en: "rich", es: "rico", fr: "riche", de: "reich", ja: "金持ち (かねもち)", ko: "부유한", zh: "富有", pt: "rico", it: "ricco", ar: "غني" },
      { en: "poor", es: "pobre", fr: "pauvre", de: "arm", ja: "貧しい (まずしい)", ko: "가난한", zh: "穷", pt: "pobre", it: "povero", ar: "فقير" },
      { en: "full", es: "lleno", fr: "plein", de: "voll", ja: "いっぱい", ko: "가득 찬", zh: "满", pt: "cheio", it: "pieno", ar: "ممتلئ" },
      { en: "empty", es: "vacío", fr: "vide", de: "leer", ja: "空 (から)", ko: "빈", zh: "空", pt: "vazio", it: "vuoto", ar: "فارغ" },
      { en: "strong", es: "fuerte", fr: "fort", de: "stark", ja: "強い (つよい)", ko: "강한", zh: "强", pt: "forte", it: "forte", ar: "قوي" },
      { en: "weak", es: "débil", fr: "faible", de: "schwach", ja: "弱い (よわい)", ko: "약한", zh: "弱", pt: "fraco", it: "debole", ar: "ضعيف" },
      { en: "young", es: "joven", fr: "jeune", de: "jung", ja: "若い (わかい)", ko: "젊은", zh: "年轻", pt: "jovem", it: "giovane", ar: "شاب" },
      { en: "right", es: "correcto", fr: "correct", de: "richtig", ja: "正しい (ただしい)", ko: "올바른", zh: "对", pt: "certo", it: "giusto", ar: "صحيح" },
      { en: "wrong", es: "incorrecto", fr: "faux", de: "falsch", ja: "間違い (まちがい)", ko: "틀린", zh: "错", pt: "errado", it: "sbagliato", ar: "خاطئ" },
      { en: "happy", es: "feliz", fr: "heureux", de: "glücklich", ja: "幸せ (しあわせ)", ko: "행복한", zh: "快乐", pt: "feliz", it: "felice", ar: "سعيد" },
      { en: "sad", es: "triste", fr: "triste", de: "traurig", ja: "悲しい (かなしい)", ko: "슬픈", zh: "伤心", pt: "triste", it: "triste", ar: "حزين" },
      { en: "important", es: "importante", fr: "important", de: "wichtig", ja: "大切 (たいせつ)", ko: "중요한", zh: "重要", pt: "importante", it: "importante", ar: "مهم" }
    ]
  },
  {
    name: "Emotions & Feelings",
    icon: "💭",
    words: [
      { en: "angry", es: "enojado", fr: "en colère", de: "wütend", ja: "怒っている", ko: "화난", zh: "生气", pt: "com raiva", it: "arrabbiato", ar: "غاضب" },
      { en: "scared", es: "asustado", fr: "effrayé", de: "ängstlich", ja: "怖い (こわい)", ko: "무서운", zh: "害怕", pt: "assustado", it: "spaventato", ar: "خائف" },
      { en: "tired", es: "cansado", fr: "fatigué", de: "müde", ja: "疲れた (つかれた)", ko: "피곤한", zh: "累", pt: "cansado", it: "stanco", ar: "متعب" },
      { en: "hungry", es: "hambriento", fr: "affamé", de: "hungrig", ja: "お腹が空いた", ko: "배고픈", zh: "饿", pt: "com fome", it: "affamato", ar: "جائع" },
      { en: "thirsty", es: "sediento", fr: "assoiffé", de: "durstig", ja: "喉が渇いた", ko: "목마른", zh: "渴", pt: "com sede", it: "assetato", ar: "عطشان" },
      { en: "surprised", es: "sorprendido", fr: "surpris", de: "überrascht", ja: "驚いた (おどろいた)", ko: "놀란", zh: "惊讶", pt: "surpreso", it: "sorpreso", ar: "مندهش" },
      { en: "excited", es: "emocionado", fr: "excité", de: "aufgeregt", ja: "わくわくした", ko: "신나는", zh: "兴奋", pt: "animado", it: "eccitato", ar: "متحمس" },
      { en: "bored", es: "aburrido", fr: "ennuyé", de: "gelangweilt", ja: "退屈 (たいくつ)", ko: "지루한", zh: "无聊", pt: "entediado", it: "annoiato", ar: "ملل" },
      { en: "nervous", es: "nervioso", fr: "nerveux", de: "nervös", ja: "緊張した (きんちょう)", ko: "긴장한", zh: "紧张", pt: "nervoso", it: "nervoso", ar: "متوتر" },
      { en: "proud", es: "orgulloso", fr: "fier", de: "stolz", ja: "誇りに思う", ko: "자랑스러운", zh: "骄傲", pt: "orgulhoso", it: "orgoglioso", ar: "فخور" },
      { en: "lonely", es: "solitario", fr: "seul", de: "einsam", ja: "寂しい (さびしい)", ko: "외로운", zh: "孤独", pt: "solitário", it: "solo", ar: "وحيد" },
      { en: "jealous", es: "celoso", fr: "jaloux", de: "eifersüchtig", ja: "嫉妬した", ko: "질투하는", zh: "嫉妒", pt: "ciumento", it: "geloso", ar: "غيور" },
      { en: "calm", es: "tranquilo", fr: "calme", de: "ruhig", ja: "穏やか (おだやか)", ko: "차분한", zh: "平静", pt: "calmo", it: "calmo", ar: "هادئ" },
      { en: "confident", es: "seguro", fr: "confiant", de: "selbstbewusst", ja: "自信がある", ko: "자신감 있는", zh: "自信", pt: "confiante", it: "sicuro", ar: "واثق" },
      { en: "grateful", es: "agradecido", fr: "reconnaissant", de: "dankbar", ja: "感謝している", ko: "감사하는", zh: "感激", pt: "grato", it: "grato", ar: "ممتن" }
    ]
  },
  {
    name: "Places",
    icon: "📍",
    words: [
      { en: "city", es: "ciudad", fr: "ville", de: "Stadt", ja: "都市 (とし)", ko: "도시", zh: "城市", pt: "cidade", it: "città", ar: "مدينة" },
      { en: "country", es: "país", fr: "pays", de: "Land", ja: "国 (くに)", ko: "나라", zh: "国家", pt: "país", it: "paese", ar: "بلد" },
      { en: "school", es: "escuela", fr: "école", de: "Schule", ja: "学校 (がっこう)", ko: "학교", zh: "学校", pt: "escola", it: "scuola", ar: "مدرسة" },
      { en: "hospital", es: "hospital", fr: "hôpital", de: "Krankenhaus", ja: "病院 (びょういん)", ko: "병원", zh: "医院", pt: "hospital", it: "ospedale", ar: "مستشفى" },
      { en: "church", es: "iglesia", fr: "église", de: "Kirche", ja: "教会 (きょうかい)", ko: "교회", zh: "教堂", pt: "igreja", it: "chiesa", ar: "كنيسة" },
      { en: "store", es: "tienda", fr: "magasin", de: "Geschäft", ja: "店 (みせ)", ko: "가게", zh: "商店", pt: "loja", it: "negozio", ar: "متجر" },
      { en: "restaurant", es: "restaurante", fr: "restaurant", de: "Restaurant", ja: "レストラン", ko: "식당", zh: "餐厅", pt: "restaurante", it: "ristorante", ar: "مطعم" },
      { en: "park", es: "parque", fr: "parc", de: "Park", ja: "公園 (こうえん)", ko: "공원", zh: "公园", pt: "parque", it: "parco", ar: "حديقة عامة" },
      { en: "library", es: "biblioteca", fr: "bibliothèque", de: "Bibliothek", ja: "図書館 (としょかん)", ko: "도서관", zh: "图书馆", pt: "biblioteca", it: "biblioteca", ar: "مكتبة" },
      { en: "museum", es: "museo", fr: "musée", de: "Museum", ja: "博物館 (はくぶつかん)", ko: "박물관", zh: "博物馆", pt: "museu", it: "museo", ar: "متحف" },
      { en: "bank", es: "banco", fr: "banque", de: "Bank", ja: "銀行 (ぎんこう)", ko: "은행", zh: "银行", pt: "banco", it: "banca", ar: "بنك" },
      { en: "airport", es: "aeropuerto", fr: "aéroport", de: "Flughafen", ja: "空港 (くうこう)", ko: "공항", zh: "机场", pt: "aeroporto", it: "aeroporto", ar: "مطار" },
      { en: "station", es: "estación", fr: "gare", de: "Bahnhof", ja: "駅 (えき)", ko: "역", zh: "站", pt: "estação", it: "stazione", ar: "محطة" },
      { en: "market", es: "mercado", fr: "marché", de: "Markt", ja: "市場 (いちば)", ko: "시장", zh: "市场", pt: "mercado", it: "mercato", ar: "سوق" },
      { en: "hotel", es: "hotel", fr: "hôtel", de: "Hotel", ja: "ホテル", ko: "호텔", zh: "酒店", pt: "hotel", it: "albergo", ar: "فندق" },
      { en: "beach", es: "playa", fr: "plage", de: "Strand", ja: "ビーチ", ko: "해변", zh: "海滩", pt: "praia", it: "spiaggia", ar: "شاطئ" },
      { en: "office", es: "oficina", fr: "bureau", de: "Büro", ja: "事務所 (じむしょ)", ko: "사무실", zh: "办公室", pt: "escritório", it: "ufficio", ar: "مكتب" },
      { en: "street", es: "calle", fr: "rue", de: "Straße", ja: "通り (とおり)", ko: "거리", zh: "街道", pt: "rua", it: "via", ar: "شارع" }
    ]
  },
  {
    name: "School & Work",
    icon: "📚",
    words: [
      { en: "book", es: "libro", fr: "livre", de: "Buch", ja: "本 (ほん)", ko: "책", zh: "书", pt: "livro", it: "libro", ar: "كتاب" },
      { en: "pen", es: "bolígrafo", fr: "stylo", de: "Kugelschreiber", ja: "ペン", ko: "펜", zh: "笔", pt: "caneta", it: "penna", ar: "قلم" },
      { en: "paper", es: "papel", fr: "papier", de: "Papier", ja: "紙 (かみ)", ko: "종이", zh: "纸", pt: "papel", it: "carta", ar: "ورقة" },
      { en: "pencil", es: "lápiz", fr: "crayon", de: "Bleistift", ja: "鉛筆 (えんぴつ)", ko: "연필", zh: "铅笔", pt: "lápis", it: "matita", ar: "قلم رصاص" },
      { en: "computer", es: "computadora", fr: "ordinateur", de: "Computer", ja: "コンピュータ", ko: "컴퓨터", zh: "电脑", pt: "computador", it: "computer", ar: "حاسوب" },
      { en: "class", es: "clase", fr: "classe", de: "Klasse", ja: "授業 (じゅぎょう)", ko: "수업", zh: "课", pt: "aula", it: "classe", ar: "صف" },
      { en: "exam", es: "examen", fr: "examen", de: "Prüfung", ja: "試験 (しけん)", ko: "시험", zh: "考试", pt: "exame", it: "esame", ar: "امتحان" },
      { en: "homework", es: "tarea", fr: "devoirs", de: "Hausaufgabe", ja: "宿題 (しゅくだい)", ko: "숙제", zh: "作业", pt: "dever de casa", it: "compiti", ar: "واجب منزلي" },
      { en: "question", es: "pregunta", fr: "question", de: "Frage", ja: "質問 (しつもん)", ko: "질문", zh: "问题", pt: "pergunta", it: "domanda", ar: "سؤال" },
      { en: "answer", es: "respuesta", fr: "réponse", de: "Antwort", ja: "答え (こたえ)", ko: "대답", zh: "回答", pt: "resposta", it: "risposta", ar: "جواب" },
      { en: "money", es: "dinero", fr: "argent", de: "Geld", ja: "お金 (おかね)", ko: "돈", zh: "钱", pt: "dinheiro", it: "soldi", ar: "مال" },
      { en: "job", es: "trabajo", fr: "emploi", de: "Arbeit", ja: "仕事 (しごと)", ko: "직업", zh: "工作", pt: "emprego", it: "lavoro", ar: "وظيفة" },
      { en: "meeting", es: "reunión", fr: "réunion", de: "Besprechung", ja: "会議 (かいぎ)", ko: "회의", zh: "会议", pt: "reunião", it: "riunione", ar: "اجتماع" },
      { en: "idea", es: "idea", fr: "idée", de: "Idee", ja: "アイデア", ko: "아이디어", zh: "主意", pt: "ideia", it: "idea", ar: "فكرة" },
      { en: "problem", es: "problema", fr: "problème", de: "Problem", ja: "問題 (もんだい)", ko: "문제", zh: "问题", pt: "problema", it: "problema", ar: "مشكلة" },
      { en: "language", es: "idioma", fr: "langue", de: "Sprache", ja: "言語 (げんご)", ko: "언어", zh: "语言", pt: "idioma", it: "lingua", ar: "لغة" },
      { en: "word", es: "palabra", fr: "mot", de: "Wort", ja: "言葉 (ことば)", ko: "단어", zh: "词", pt: "palavra", it: "parola", ar: "كلمة" },
      { en: "letter", es: "carta", fr: "lettre", de: "Brief", ja: "手紙 (てがみ)", ko: "편지", zh: "信", pt: "carta", it: "lettera", ar: "رسالة" },
      { en: "number", es: "número", fr: "numéro", de: "Nummer", ja: "番号 (ばんごう)", ko: "번호", zh: "号码", pt: "número", it: "numero", ar: "رقم" },
      { en: "name", es: "nombre", fr: "nom", de: "Name", ja: "名前 (なまえ)", ko: "이름", zh: "名字", pt: "nome", it: "nome", ar: "اسم" }
    ]
  },
  {
    name: "Health & Body",
    icon: "🏥",
    words: [
      { en: "sick", es: "enfermo", fr: "malade", de: "krank", ja: "病気 (びょうき)", ko: "아픈", zh: "生病", pt: "doente", it: "malato", ar: "مريض" },
      { en: "healthy", es: "sano", fr: "en bonne santé", de: "gesund", ja: "健康 (けんこう)", ko: "건강한", zh: "健康", pt: "saudável", it: "sano", ar: "صحي" },
      { en: "medicine", es: "medicina", fr: "médicament", de: "Medizin", ja: "薬 (くすり)", ko: "약", zh: "药", pt: "remédio", it: "medicina", ar: "دواء" },
      { en: "pain", es: "dolor", fr: "douleur", de: "Schmerz", ja: "痛み (いたみ)", ko: "통증", zh: "疼痛", pt: "dor", it: "dolore", ar: "ألم" },
      { en: "fever", es: "fiebre", fr: "fièvre", de: "Fieber", ja: "熱 (ねつ)", ko: "열", zh: "发烧", pt: "febre", it: "febbre", ar: "حمى" },
      { en: "cough", es: "tos", fr: "toux", de: "Husten", ja: "咳 (せき)", ko: "기침", zh: "咳嗽", pt: "tosse", it: "tosse", ar: "سعال" },
      { en: "cold (illness)", es: "resfriado", fr: "rhume", de: "Erkältung", ja: "風邪 (かぜ)", ko: "감기", zh: "感冒", pt: "resfriado", it: "raffreddore", ar: "زكام" },
      { en: "headache", es: "dolor de cabeza", fr: "mal de tête", de: "Kopfschmerzen", ja: "頭痛 (ずつう)", ko: "두통", zh: "头痛", pt: "dor de cabeça", it: "mal di testa", ar: "صداع" },
      { en: "hospital", es: "hospital", fr: "hôpital", de: "Krankenhaus", ja: "病院 (びょういん)", ko: "병원", zh: "医院", pt: "hospital", it: "ospedale", ar: "مستشفى" },
      { en: "exercise", es: "ejercicio", fr: "exercice", de: "Übung", ja: "運動 (うんどう)", ko: "운동", zh: "运动", pt: "exercício", it: "esercizio", ar: "تمرين" },
      { en: "rest", es: "descanso", fr: "repos", de: "Ruhe", ja: "休み (やすみ)", ko: "휴식", zh: "休息", pt: "descanso", it: "riposo", ar: "راحة" },
      { en: "breath", es: "respiración", fr: "souffle", de: "Atem", ja: "息 (いき)", ko: "숨", zh: "呼吸", pt: "respiração", it: "respiro", ar: "نفس" },
      { en: "life", es: "vida", fr: "vie", de: "Leben", ja: "命 (いのち)", ko: "생명", zh: "生命", pt: "vida", it: "vita", ar: "حياة" },
      { en: "death", es: "muerte", fr: "mort", de: "Tod", ja: "死 (し)", ko: "죽음", zh: "死亡", pt: "morte", it: "morte", ar: "موت" },
      { en: "alive", es: "vivo", fr: "vivant", de: "lebendig", ja: "生きている", ko: "살아있는", zh: "活着", pt: "vivo", it: "vivo", ar: "حي" }
    ]
  },
  {
    name: "Common Phrases",
    icon: "💬",
    words: [
      { en: "I don't understand", es: "no entiendo", fr: "je ne comprends pas", de: "ich verstehe nicht", ja: "わかりません", ko: "이해 못해요", zh: "我不明白", pt: "não entendo", it: "non capisco", ar: "لا أفهم" },
      { en: "I don't know", es: "no sé", fr: "je ne sais pas", de: "ich weiß nicht", ja: "知りません", ko: "모르겠어요", zh: "我不知道", pt: "não sei", it: "non lo so", ar: "لا أعرف" },
      { en: "I need help", es: "necesito ayuda", fr: "j'ai besoin d'aide", de: "ich brauche Hilfe", ja: "助けてください", ko: "도와주세요", zh: "我需要帮助", pt: "preciso de ajuda", it: "ho bisogno di aiuto", ar: "أحتاج مساعدة" },
      { en: "how much?", es: "¿cuánto cuesta?", fr: "combien?", de: "wie viel?", ja: "いくらですか", ko: "얼마예요?", zh: "多少钱?", pt: "quanto custa?", it: "quanto costa?", ar: "بكم؟" },
      { en: "I like it", es: "me gusta", fr: "j'aime ça", de: "es gefällt mir", ja: "好きです", ko: "좋아해요", zh: "我喜欢", pt: "eu gosto", it: "mi piace", ar: "أنا أحبه" },
      { en: "I'm lost", es: "estoy perdido", fr: "je suis perdu", de: "ich bin verloren", ja: "迷っています", ko: "길을 잃었어요", zh: "我迷路了", pt: "estou perdido", it: "mi sono perso", ar: "أنا ضائع" },
      { en: "wait a moment", es: "espera un momento", fr: "attendez un moment", de: "einen Moment bitte", ja: "ちょっと待って", ko: "잠깐만요", zh: "等一下", pt: "espere um momento", it: "aspetta un momento", ar: "انتظر لحظة" },
      { en: "let's go", es: "vamos", fr: "allons-y", de: "los geht's", ja: "行きましょう", ko: "가자", zh: "走吧", pt: "vamos", it: "andiamo", ar: "هيا بنا" },
      { en: "of course", es: "por supuesto", fr: "bien sûr", de: "natürlich", ja: "もちろん", ko: "물론이죠", zh: "当然", pt: "claro", it: "certo", ar: "بالطبع" },
      { en: "no problem", es: "no hay problema", fr: "pas de problème", de: "kein Problem", ja: "問題ないです", ko: "문제없어요", zh: "没问题", pt: "sem problema", it: "nessun problema", ar: "لا مشكلة" },
      { en: "congratulations", es: "felicidades", fr: "félicitations", de: "Herzlichen Glückwunsch", ja: "おめでとうございます", ko: "축하합니다", zh: "恭喜", pt: "parabéns", it: "congratulazioni", ar: "مبروك" },
      { en: "happy birthday", es: "feliz cumpleaños", fr: "joyeux anniversaire", de: "alles Gute zum Geburtstag", ja: "お誕生日おめでとう", ko: "생일 축하합니다", zh: "生日快乐", pt: "feliz aniversário", it: "buon compleanno", ar: "عيد ميلاد سعيد" },
      { en: "I'm sorry", es: "lo siento", fr: "je suis désolé", de: "es tut mir leid", ja: "ごめんなさい", ko: "죄송합니다", zh: "对不起", pt: "me desculpe", it: "mi dispiace", ar: "أنا آسف" },
      { en: "cheers", es: "salud", fr: "santé", de: "Prost", ja: "乾杯 (かんぱい)", ko: "건배", zh: "干杯", pt: "saúde", it: "cin cin", ar: "في صحتك" },
      { en: "good luck", es: "buena suerte", fr: "bonne chance", de: "viel Glück", ja: "頑張って", ko: "행운을 빕니다", zh: "祝你好运", pt: "boa sorte", it: "buona fortuna", ar: "حظ سعيد" },
      { en: "I agree", es: "estoy de acuerdo", fr: "je suis d'accord", de: "ich stimme zu", ja: "同意します", ko: "동의해요", zh: "我同意", pt: "eu concordo", it: "sono d'accordo", ar: "أنا موافق" },
      { en: "maybe", es: "quizás", fr: "peut-être", de: "vielleicht", ja: "たぶん", ko: "아마도", zh: "也许", pt: "talvez", it: "forse", ar: "ربما" },
      { en: "very", es: "muy", fr: "très", de: "sehr", ja: "とても", ko: "매우", zh: "很", pt: "muito", it: "molto", ar: "جدا" },
      { en: "also", es: "también", fr: "aussi", de: "auch", ja: "も", ko: "또한", zh: "也", pt: "também", it: "anche", ar: "أيضا" },
      { en: "already", es: "ya", fr: "déjà", de: "schon", ja: "もう", ko: "이미", zh: "已经", pt: "já", it: "già", ar: "بالفعل" }
    ]
  },
  {
    name: "Everyday Objects",
    icon: "🔧",
    words: [
      { en: "phone", es: "teléfono", fr: "téléphone", de: "Handy", ja: "携帯 (けいたい)", ko: "핸드폰", zh: "手机", pt: "celular", it: "cellulare", ar: "هاتف محمول" },
      { en: "camera", es: "cámara", fr: "appareil photo", de: "Kamera", ja: "カメラ", ko: "카메라", zh: "相机", pt: "câmera", it: "fotocamera", ar: "كاميرا" },
      { en: "television", es: "televisión", fr: "télévision", de: "Fernseher", ja: "テレビ", ko: "텔레비전", zh: "电视", pt: "televisão", it: "televisione", ar: "تلفزيون" },
      { en: "bottle", es: "botella", fr: "bouteille", de: "Flasche", ja: "ボトル", ko: "병", zh: "瓶子", pt: "garrafa", it: "bottiglia", ar: "زجاجة" },
      { en: "cup", es: "taza", fr: "tasse", de: "Tasse", ja: "カップ", ko: "컵", zh: "杯子", pt: "xícara", it: "tazza", ar: "كوب" },
      { en: "plate", es: "plato", fr: "assiette", de: "Teller", ja: "皿 (さら)", ko: "접시", zh: "盘子", pt: "prato", it: "piatto", ar: "طبق" },
      { en: "knife", es: "cuchillo", fr: "couteau", de: "Messer", ja: "ナイフ", ko: "칼", zh: "刀", pt: "faca", it: "coltello", ar: "سكين" },
      { en: "fork", es: "tenedor", fr: "fourchette", de: "Gabel", ja: "フォーク", ko: "포크", zh: "叉子", pt: "garfo", it: "forchetta", ar: "شوكة" },
      { en: "spoon", es: "cuchara", fr: "cuillère", de: "Löffel", ja: "スプーン", ko: "숟가락", zh: "勺子", pt: "colher", it: "cucchiaio", ar: "ملعقة" },
      { en: "box", es: "caja", fr: "boîte", de: "Kiste", ja: "箱 (はこ)", ko: "상자", zh: "盒子", pt: "caixa", it: "scatola", ar: "صندوق" },
      { en: "scissors", es: "tijeras", fr: "ciseaux", de: "Schere", ja: "はさみ", ko: "가위", zh: "剪刀", pt: "tesoura", it: "forbici", ar: "مقص" },
      { en: "needle", es: "aguja", fr: "aiguille", de: "Nadel", ja: "針 (はり)", ko: "바늘", zh: "针", pt: "agulha", it: "ago", ar: "إبرة" },
      { en: "rope", es: "cuerda", fr: "corde", de: "Seil", ja: "ロープ", ko: "밧줄", zh: "绳子", pt: "corda", it: "corda", ar: "حبل" },
      { en: "candle", es: "vela", fr: "bougie", de: "Kerze", ja: "ろうそく", ko: "양초", zh: "蜡烛", pt: "vela", it: "candela", ar: "شمعة" },
      { en: "soap", es: "jabón", fr: "savon", de: "Seife", ja: "石鹸 (せっけん)", ko: "비누", zh: "肥皂", pt: "sabão", it: "sapone", ar: "صابون" },
      { en: "towel", es: "toalla", fr: "serviette", de: "Handtuch", ja: "タオル", ko: "수건", zh: "毛巾", pt: "toalha", it: "asciugamano", ar: "منشفة" },
      { en: "brush", es: "cepillo", fr: "brosse", de: "Bürste", ja: "ブラシ", ko: "브러시", zh: "刷子", pt: "escova", it: "spazzola", ar: "فرشاة" },
      { en: "gift", es: "regalo", fr: "cadeau", de: "Geschenk", ja: "プレゼント", ko: "선물", zh: "礼物", pt: "presente", it: "regalo", ar: "هدية" },
      { en: "toy", es: "juguete", fr: "jouet", de: "Spielzeug", ja: "おもちゃ", ko: "장난감", zh: "玩具", pt: "brinquedo", it: "giocattolo", ar: "لعبة" },
      { en: "picture", es: "foto", fr: "photo", de: "Bild", ja: "写真 (しゃしん)", ko: "사진", zh: "照片", pt: "foto", it: "foto", ar: "صورة" },
      { en: "coin", es: "moneda", fr: "pièce", de: "Münze", ja: "コイン", ko: "동전", zh: "硬币", pt: "moeda", it: "moneta", ar: "عملة" },
      { en: "ring", es: "anillo", fr: "bague", de: "Ring", ja: "指輪 (ゆびわ)", ko: "반지", zh: "戒指", pt: "anel", it: "anello", ar: "خاتم" },
      { en: "watch", es: "reloj", fr: "montre", de: "Armbanduhr", ja: "腕時計 (うでどけい)", ko: "시계", zh: "手表", pt: "relógio", it: "orologio", ar: "ساعة يد" },
      { en: "glasses", es: "gafas", fr: "lunettes", de: "Brille", ja: "メガネ", ko: "안경", zh: "眼镜", pt: "óculos", it: "occhiali", ar: "نظارات" },
      { en: "wheel", es: "rueda", fr: "roue", de: "Rad", ja: "車輪 (しゃりん)", ko: "바퀴", zh: "轮子", pt: "roda", it: "ruota", ar: "عجلة" },
      { en: "flag", es: "bandera", fr: "drapeau", de: "Flagge", ja: "旗 (はた)", ko: "깃발", zh: "旗帜", pt: "bandeira", it: "bandiera", ar: "علم" },
      { en: "ball", es: "pelota", fr: "balle", de: "Ball", ja: "ボール", ko: "공", zh: "球", pt: "bola", it: "palla", ar: "كرة" },
      { en: "music", es: "música", fr: "musique", de: "Musik", ja: "音楽 (おんがく)", ko: "음악", zh: "音乐", pt: "música", it: "musica", ar: "موسيقى" },
      { en: "game", es: "juego", fr: "jeu", de: "Spiel", ja: "ゲーム", ko: "게임", zh: "游戏", pt: "jogo", it: "gioco", ar: "لعبة" },
      { en: "movie", es: "película", fr: "film", de: "Film", ja: "映画 (えいが)", ko: "영화", zh: "电影", pt: "filme", it: "film", ar: "فيلم" },
      { en: "song", es: "canción", fr: "chanson", de: "Lied", ja: "歌 (うた)", ko: "노래", zh: "歌曲", pt: "canção", it: "canzone", ar: "أغنية" },
      { en: "story", es: "historia", fr: "histoire", de: "Geschichte", ja: "物語 (ものがたり)", ko: "이야기", zh: "故事", pt: "história", it: "storia", ar: "قصة" },
      { en: "news", es: "noticias", fr: "nouvelles", de: "Nachrichten", ja: "ニュース", ko: "뉴스", zh: "新闻", pt: "notícias", it: "notizie", ar: "أخبار" },
      { en: "dream", es: "sueño", fr: "rêve", de: "Traum", ja: "夢 (ゆめ)", ko: "꿈", zh: "梦", pt: "sonho", it: "sogno", ar: "حلم" },
      { en: "truth", es: "verdad", fr: "vérité", de: "Wahrheit", ja: "真実 (しんじつ)", ko: "진실", zh: "真相", pt: "verdade", it: "verità", ar: "حقيقة" }
    ]
  }
];
