// Batch 1: Russian, Turkish, Dutch, Swedish, Polish, Vietnamese, Indonesian, Finnish, Norwegian

LANGUAGES.push(
  { code: 'ru', name: 'Russian', flag: '🇷🇺' },
  { code: 'tr', name: 'Turkish', flag: '🇹🇷' },
  { code: 'nl', name: 'Dutch', flag: '🇳🇱' },
  { code: 'sv', name: 'Swedish', flag: '🇸🇪' },
  { code: 'pl', name: 'Polish', flag: '🇵🇱' },
  { code: 'vi', name: 'Vietnamese', flag: '🇻🇳' },
  { code: 'id', name: 'Indonesian', flag: '🇮🇩' },
  { code: 'fi', name: 'Finnish', flag: '🇫🇮' },
  { code: 'no', name: 'Norwegian', flag: '🇳🇴' }
);

var BATCH1 = {
  "hello": { ru: "привет", tr: "merhaba", nl: "hallo", sv: "hej", pl: "cześć", vi: "xin chào", id: "halo", fi: "hei", no: "hei" },
  "goodbye": { ru: "до свидания", tr: "hoşça kal", nl: "tot ziens", sv: "hejdå", pl: "do widzenia", vi: "tạm biệt", id: "selamat tinggal", fi: "näkemiin", no: "ha det" },
  "please": { ru: "пожалуйста", tr: "lütfen", nl: "alstublieft", sv: "snälla", pl: "proszę", vi: "làm ơn", id: "tolong", fi: "ole hyvä", no: "vær så snill" },
  "thank you": { ru: "спасибо", tr: "teşekkür ederim", nl: "dank u", sv: "tack", pl: "dziękuję", vi: "cảm ơn", id: "terima kasih", fi: "kiitos", no: "takk" },
  "yes": { ru: "да", tr: "evet", nl: "ja", sv: "ja", pl: "tak", vi: "vâng", id: "ya", fi: "kyllä", no: "ja" },
  "no": { ru: "нет", tr: "hayır", nl: "nee", sv: "nej", pl: "nie", vi: "không", id: "tidak", fi: "ei", no: "nei" },
  "sorry": { ru: "извините", tr: "özür dilerim", nl: "sorry", sv: "förlåt", pl: "przepraszam", vi: "xin lỗi", id: "maaf", fi: "anteeksi", no: "beklager" },
  "excuse me": { ru: "простите", tr: "affedersiniz", nl: "pardon", sv: "ursäkta", pl: "przepraszam", vi: "xin lỗi", id: "permisi", fi: "anteeksi", no: "unnskyld" },
  "good morning": { ru: "доброе утро", tr: "günaydın", nl: "goedemorgen", sv: "god morgon", pl: "dzień dobry", vi: "chào buổi sáng", id: "selamat pagi", fi: "hyvää huomenta", no: "god morgen" },
  "good night": { ru: "спокойной ночи", tr: "iyi geceler", nl: "goedenacht", sv: "god natt", pl: "dobranoc", vi: "chúc ngủ ngon", id: "selamat malam", fi: "hyvää yötä", no: "god natt" },
  "how are you": { ru: "как дела", tr: "nasılsın", nl: "hoe gaat het", sv: "hur mår du", pl: "jak się masz", vi: "bạn khỏe không", id: "apa kabar", fi: "mitä kuuluu", no: "hvordan har du det" },
  "nice to meet you": { ru: "приятно познакомиться", tr: "tanıştığıma memnun oldum", nl: "aangenaam kennis te maken", sv: "trevligt att träffas", pl: "miło cię poznać", vi: "rất vui được gặp bạn", id: "senang bertemu Anda", fi: "hauska tavata", no: "hyggelig å møte deg" },
  "see you later": { ru: "увидимся позже", tr: "sonra görüşürüz", nl: "tot later", sv: "vi ses senare", pl: "do zobaczenia", vi: "hẹn gặp lại", id: "sampai jumpa", fi: "nähdään myöhemmin", no: "ses senere" },
  "welcome": { ru: "добро пожаловать", tr: "hoş geldiniz", nl: "welkom", sv: "välkommen", pl: "witamy", vi: "chào mừng", id: "selamat datang", fi: "tervetuloa", no: "velkommen" },
  "i": { ru: "я", tr: "ben", nl: "ik", sv: "jag", pl: "ja", vi: "tôi", id: "saya", fi: "minä", no: "jeg" },
  "you": { ru: "ты", tr: "sen", nl: "jij", sv: "du", pl: "ty", vi: "bạn", id: "kamu", fi: "sinä", no: "du" },
  "he": { ru: "он", tr: "o", nl: "hij", sv: "han", pl: "on", vi: "anh ấy", id: "dia", fi: "hän", no: "han" },
  "she": { ru: "она", tr: "o", nl: "zij", sv: "hon", pl: "ona", vi: "cô ấy", id: "dia", fi: "hän", no: "hun" },
  "we": { ru: "мы", tr: "biz", nl: "wij", sv: "vi", pl: "my", vi: "chúng tôi", id: "kami", fi: "me", no: "vi" },
  "they": { ru: "они", tr: "onlar", nl: "zij", sv: "de", pl: "oni", vi: "họ", id: "mereka", fi: "he", no: "de" },
  "this": { ru: "это", tr: "bu", nl: "dit", sv: "detta", pl: "to", vi: "cái này", id: "ini", fi: "tämä", no: "dette" },
  "that": { ru: "то", tr: "şu", nl: "dat", sv: "det där", pl: "tamto", vi: "cái đó", id: "itu", fi: "tuo", no: "det" },
  "what": { ru: "что", tr: "ne", nl: "wat", sv: "vad", pl: "co", vi: "cái gì", id: "apa", fi: "mitä", no: "hva" },
  "where": { ru: "где", tr: "nerede", nl: "waar", sv: "var", pl: "gdzie", vi: "ở đâu", id: "di mana", fi: "missä", no: "hvor" },
  "when": { ru: "когда", tr: "ne zaman", nl: "wanneer", sv: "när", pl: "kiedy", vi: "khi nào", id: "kapan", fi: "milloin", no: "når" },
  "why": { ru: "почему", tr: "neden", nl: "waarom", sv: "varför", pl: "dlaczego", vi: "tại sao", id: "mengapa", fi: "miksi", no: "hvorfor" },
  "how": { ru: "как", tr: "nasıl", nl: "hoe", sv: "hur", pl: "jak", vi: "như thế nào", id: "bagaimana", fi: "miten", no: "hvordan" },
  "who": { ru: "кто", tr: "kim", nl: "wie", sv: "vem", pl: "kto", vi: "ai", id: "siapa", fi: "kuka", no: "hvem" },
  "zero": { ru: "ноль", tr: "sıfır", nl: "nul", sv: "noll", pl: "zero", vi: "không", id: "nol", fi: "nolla", no: "null" },
  "one": { ru: "один", tr: "bir", nl: "een", sv: "en", pl: "jeden", vi: "một", id: "satu", fi: "yksi", no: "en" },
  "two": { ru: "два", tr: "iki", nl: "twee", sv: "två", pl: "dwa", vi: "hai", id: "dua", fi: "kaksi", no: "to" },
  "three": { ru: "три", tr: "üç", nl: "drie", sv: "tre", pl: "trzy", vi: "ba", id: "tiga", fi: "kolme", no: "tre" },
  "four": { ru: "четыре", tr: "dört", nl: "vier", sv: "fyra", pl: "cztery", vi: "bốn", id: "empat", fi: "neljä", no: "fire" },
  "five": { ru: "пять", tr: "beş", nl: "vijf", sv: "fem", pl: "pięć", vi: "năm", id: "lima", fi: "viisi", no: "fem" },
  "six": { ru: "шесть", tr: "altı", nl: "zes", sv: "sex", pl: "sześć", vi: "sáu", id: "enam", fi: "kuusi", no: "seks" },
  "seven": { ru: "семь", tr: "yedi", nl: "zeven", sv: "sju", pl: "siedem", vi: "bảy", id: "tujuh", fi: "seitsemän", no: "syv" },
  "eight": { ru: "восемь", tr: "sekiz", nl: "acht", sv: "åtta", pl: "osiem", vi: "tám", id: "delapan", fi: "kahdeksan", no: "åtte" },
  "nine": { ru: "девять", tr: "dokuz", nl: "negen", sv: "nio", pl: "dziewięć", vi: "chín", id: "sembilan", fi: "yhdeksän", no: "ni" },
  "ten": { ru: "десять", tr: "on", nl: "tien", sv: "tio", pl: "dziesięć", vi: "mười", id: "sepuluh", fi: "kymmenen", no: "ti" },
  "eleven": { ru: "одиннадцать", tr: "on bir", nl: "elf", sv: "elva", pl: "jedenaście", vi: "mười một", id: "sebelas", fi: "yksitoista", no: "elleve" },
  "twelve": { ru: "двенадцать", tr: "on iki", nl: "twaalf", sv: "tolv", pl: "dwanaście", vi: "mười hai", id: "dua belas", fi: "kaksitoista", no: "tolv" },
  "twenty": { ru: "двадцать", tr: "yirmi", nl: "twintig", sv: "tjugo", pl: "dwadzieścia", vi: "hai mươi", id: "dua puluh", fi: "kaksikymmentä", no: "tjue" },
  "thirty": { ru: "тридцать", tr: "otuz", nl: "dertig", sv: "trettio", pl: "trzydzieści", vi: "ba mươi", id: "tiga puluh", fi: "kolmekymmentä", no: "tretti" },
  "forty": { ru: "сорок", tr: "kırk", nl: "veertig", sv: "fyrtio", pl: "czterdzieści", vi: "bốn mươi", id: "empat puluh", fi: "neljäkymmentä", no: "førti" },
  "fifty": { ru: "пятьдесят", tr: "elli", nl: "vijftig", sv: "femtio", pl: "pięćdziesiąt", vi: "năm mươi", id: "lima puluh", fi: "viisikymmentä", no: "femti" },
  "hundred": { ru: "сто", tr: "yüz", nl: "honderd", sv: "hundra", pl: "sto", vi: "một trăm", id: "seratus", fi: "sata", no: "hundre" },
  "thousand": { ru: "тысяча", tr: "bin", nl: "duizend", sv: "tusen", pl: "tysiąc", vi: "một nghìn", id: "seribu", fi: "tuhat", no: "tusen" },
  "million": { ru: "миллион", tr: "milyon", nl: "miljoen", sv: "miljon", pl: "milion", vi: "triệu", id: "juta", fi: "miljoona", no: "million" },
  "first": { ru: "первый", tr: "birinci", nl: "eerste", sv: "första", pl: "pierwszy", vi: "thứ nhất", id: "pertama", fi: "ensimmäinen", no: "første" },
  "second": { ru: "второй", tr: "ikinci", nl: "tweede", sv: "andra", pl: "drugi", vi: "thứ hai", id: "kedua", fi: "toinen", no: "andre" },
  "third": { ru: "третий", tr: "üçüncü", nl: "derde", sv: "tredje", pl: "trzeci", vi: "thứ ba", id: "ketiga", fi: "kolmas", no: "tredje" },
  "half": { ru: "половина", tr: "yarım", nl: "helft", sv: "halv", pl: "połowa", vi: "một nửa", id: "setengah", fi: "puoli", no: "halv" },
  "pair": { ru: "пара", tr: "çift", nl: "paar", sv: "par", pl: "para", vi: "cặp", id: "pasangan", fi: "pari", no: "par" },
  "red": { ru: "красный", tr: "kırmızı", nl: "rood", sv: "röd", pl: "czerwony", vi: "đỏ", id: "merah", fi: "punainen", no: "rød" },
  "blue": { ru: "синий", tr: "mavi", nl: "blauw", sv: "blå", pl: "niebieski", vi: "xanh dương", id: "biru", fi: "sininen", no: "blå" },
  "green": { ru: "зелёный", tr: "yeşil", nl: "groen", sv: "grön", pl: "zielony", vi: "xanh lá", id: "hijau", fi: "vihreä", no: "grønn" },
  "yellow": { ru: "жёлтый", tr: "sarı", nl: "geel", sv: "gul", pl: "żółty", vi: "vàng", id: "kuning", fi: "keltainen", no: "gul" },
  "orange": { ru: "оранжевый", tr: "turuncu", nl: "oranje", sv: "orange", pl: "pomarańczowy", vi: "cam", id: "oranye", fi: "oranssi", no: "oransje" },
  "purple": { ru: "фиолетовый", tr: "mor", nl: "paars", sv: "lila", pl: "fioletowy", vi: "tím", id: "ungu", fi: "violetti", no: "lilla" },
  "pink": { ru: "розовый", tr: "pembe", nl: "roze", sv: "rosa", pl: "różowy", vi: "hồng", id: "merah muda", fi: "vaaleanpunainen", no: "rosa" },
  "black": { ru: "чёрный", tr: "siyah", nl: "zwart", sv: "svart", pl: "czarny", vi: "đen", id: "hitam", fi: "musta", no: "svart" },
  "white": { ru: "белый", tr: "beyaz", nl: "wit", sv: "vit", pl: "biały", vi: "trắng", id: "putih", fi: "valkoinen", no: "hvit" },
  "brown": { ru: "коричневый", tr: "kahverengi", nl: "bruin", sv: "brun", pl: "brązowy", vi: "nâu", id: "cokelat", fi: "ruskea", no: "brun" },
  "gray": { ru: "серый", tr: "gri", nl: "grijs", sv: "grå", pl: "szary", vi: "xám", id: "abu-abu", fi: "harmaa", no: "grå" },
  "gold": { ru: "золотой", tr: "altın", nl: "goud", sv: "guld", pl: "złoty", vi: "vàng kim", id: "emas", fi: "kulta", no: "gull" },
  "silver": { ru: "серебряный", tr: "gümüş", nl: "zilver", sv: "silver", pl: "srebrny", vi: "bạc", id: "perak", fi: "hopea", no: "sølv" },
  "light": { ru: "светлый", tr: "açık", nl: "licht", sv: "ljus", pl: "jasny", vi: "sáng", id: "terang", fi: "vaalea", no: "lys" },
  "dark": { ru: "тёмный", tr: "koyu", nl: "donker", sv: "mörk", pl: "ciemny", vi: "tối", id: "gelap", fi: "tumma", no: "mørk" },
  "dog": { ru: "собака", tr: "köpek", nl: "hond", sv: "hund", pl: "pies", vi: "con chó", id: "anjing", fi: "koira", no: "hund" },
  "cat": { ru: "кошка", tr: "kedi", nl: "kat", sv: "katt", pl: "kot", vi: "con mèo", id: "kucing", fi: "kissa", no: "katt" },
  "bird": { ru: "птица", tr: "kuş", nl: "vogel", sv: "fågel", pl: "ptak", vi: "con chim", id: "burung", fi: "lintu", no: "fugl" },
  "fish": { ru: "рыба", tr: "balık", nl: "vis", sv: "fisk", pl: "ryba", vi: "con cá", id: "ikan", fi: "kala", no: "fisk" },
  "horse": { ru: "лошадь", tr: "at", nl: "paard", sv: "häst", pl: "koń", vi: "con ngựa", id: "kuda", fi: "hevonen", no: "hest" },
  "cow": { ru: "корова", tr: "inek", nl: "koe", sv: "ko", pl: "krowa", vi: "con bò", id: "sapi", fi: "lehmä", no: "ku" },
  "pig": { ru: "свинья", tr: "domuz", nl: "varken", sv: "gris", pl: "świnia", vi: "con lợn", id: "babi", fi: "sika", no: "gris" },
  "sheep": { ru: "овца", tr: "koyun", nl: "schaap", sv: "får", pl: "owca", vi: "con cừu", id: "domba", fi: "lammas", no: "sau" },
  "chicken": { ru: "курица", tr: "tavuk", nl: "kip", sv: "kyckling", pl: "kurczak", vi: "con gà", id: "ayam", fi: "kana", no: "kylling" },
  "duck": { ru: "утка", tr: "ördek", nl: "eend", sv: "anka", pl: "kaczka", vi: "con vịt", id: "bebek", fi: "ankka", no: "and" },
  "rabbit": { ru: "кролик", tr: "tavşan", nl: "konijn", sv: "kanin", pl: "królik", vi: "con thỏ", id: "kelinci", fi: "kani", no: "kanin" },
  "mouse": { ru: "мышь", tr: "fare", nl: "muis", sv: "mus", pl: "mysz", vi: "con chuột", id: "tikus", fi: "hiiri", no: "mus" },
  "elephant": { ru: "слон", tr: "fil", nl: "olifant", sv: "elefant", pl: "słoń", vi: "con voi", id: "gajah", fi: "norsu", no: "elefant" },
  "lion": { ru: "лев", tr: "aslan", nl: "leeuw", sv: "lejon", pl: "lew", vi: "sư tử", id: "singa", fi: "leijona", no: "løve" },
  "tiger": { ru: "тигр", tr: "kaplan", nl: "tijger", sv: "tiger", pl: "tygrys", vi: "con hổ", id: "harimau", fi: "tiikeri", no: "tiger" },
  "bear": { ru: "медведь", tr: "ayı", nl: "beer", sv: "björn", pl: "niedźwiedź", vi: "con gấu", id: "beruang", fi: "karhu", no: "bjørn" },
  "monkey": { ru: "обезьяна", tr: "maymun", nl: "aap", sv: "apa", pl: "małpa", vi: "con khỉ", id: "monyet", fi: "apina", no: "ape" },
  "snake": { ru: "змея", tr: "yılan", nl: "slang", sv: "orm", pl: "wąż", vi: "con rắn", id: "ular", fi: "käärme", no: "slange" },
  "frog": { ru: "лягушка", tr: "kurbağa", nl: "kikker", sv: "groda", pl: "żaba", vi: "con ếch", id: "katak", fi: "sammakko", no: "frosk" },
  "turtle": { ru: "черепаха", tr: "kaplumbağa", nl: "schildpad", sv: "sköldpadda", pl: "żółw", vi: "con rùa", id: "kura-kura", fi: "kilpikonna", no: "skilpadde" },
  "whale": { ru: "кит", tr: "balina", nl: "walvis", sv: "val", pl: "wieloryb", vi: "cá voi", id: "paus", fi: "valas", no: "hval" },
  "dolphin": { ru: "дельфин", tr: "yunus", nl: "dolfijn", sv: "delfin", pl: "delfin", vi: "cá heo", id: "lumba-lumba", fi: "delfiini", no: "delfin" },
  "butterfly": { ru: "бабочка", tr: "kelebek", nl: "vlinder", sv: "fjäril", pl: "motyl", vi: "con bướm", id: "kupu-kupu", fi: "perhonen", no: "sommerfugl" },
  "bee": { ru: "пчела", tr: "arı", nl: "bij", sv: "bi", pl: "pszczoła", vi: "con ong", id: "lebah", fi: "mehiläinen", no: "bie" },
  "ant": { ru: "муравей", tr: "karınca", nl: "mier", sv: "myra", pl: "mrówka", vi: "con kiến", id: "semut", fi: "muurahainen", no: "maur" },
  "spider": { ru: "паук", tr: "örümcek", nl: "spin", sv: "spindel", pl: "pająk", vi: "con nhện", id: "laba-laba", fi: "hämähäkki", no: "edderkopp" },
  "wolf": { ru: "волк", tr: "kurt", nl: "wolf", sv: "varg", pl: "wilk", vi: "con sói", id: "serigala", fi: "susi", no: "ulv" },
  "fox": { ru: "лиса", tr: "tilki", nl: "vos", sv: "räv", pl: "lis", vi: "con cáo", id: "rubah", fi: "kettu", no: "rev" },
  "deer": { ru: "олень", tr: "geyik", nl: "hert", sv: "hjort", pl: "jeleń", vi: "con hươu", id: "rusa", fi: "peura", no: "hjort" },
  "eagle": { ru: "орёл", tr: "kartal", nl: "arend", sv: "örn", pl: "orzeł", vi: "đại bàng", id: "elang", fi: "kotka", no: "ørn" },
  "water": { ru: "вода", tr: "su", nl: "water", sv: "vatten", pl: "woda", vi: "nước", id: "air", fi: "vesi", no: "vann" },
  "bread": { ru: "хлеб", tr: "ekmek", nl: "brood", sv: "bröd", pl: "chleb", vi: "bánh mì", id: "roti", fi: "leipä", no: "brød" },
  "rice": { ru: "рис", tr: "pirinç", nl: "rijst", sv: "ris", pl: "ryż", vi: "cơm", id: "nasi", fi: "riisi", no: "ris" },
  "meat": { ru: "мясо", tr: "et", nl: "vlees", sv: "kött", pl: "mięso", vi: "thịt", id: "daging", fi: "liha", no: "kjøtt" },
  "egg": { ru: "яйцо", tr: "yumurta", nl: "ei", sv: "ägg", pl: "jajko", vi: "trứng", id: "telur", fi: "muna", no: "egg" },
  "milk": { ru: "молоко", tr: "süt", nl: "melk", sv: "mjölk", pl: "mleko", vi: "sữa", id: "susu", fi: "maito", no: "melk" },
  "cheese": { ru: "сыр", tr: "peynir", nl: "kaas", sv: "ost", pl: "ser", vi: "phô mai", id: "keju", fi: "juusto", no: "ost" },
  "butter": { ru: "масло", tr: "tereyağı", nl: "boter", sv: "smör", pl: "masło", vi: "bơ", id: "mentega", fi: "voi", no: "smør" },
  "sugar": { ru: "сахар", tr: "şeker", nl: "suiker", sv: "socker", pl: "cukier", vi: "đường", id: "gula", fi: "sokeri", no: "sukker" },
  "salt": { ru: "соль", tr: "tuz", nl: "zout", sv: "salt", pl: "sól", vi: "muối", id: "garam", fi: "suola", no: "salt" },
  "apple": { ru: "яблоко", tr: "elma", nl: "appel", sv: "äpple", pl: "jabłko", vi: "quả táo", id: "apel", fi: "omena", no: "eple" },
  "banana": { ru: "банан", tr: "muz", nl: "banaan", sv: "banan", pl: "banan", vi: "quả chuối", id: "pisang", fi: "banaani", no: "banan" },
  "orange (fruit)": { ru: "апельсин", tr: "portakal", nl: "sinaasappel", sv: "apelsin", pl: "pomarańcza", vi: "quả cam", id: "jeruk", fi: "appelsiini", no: "appelsin" },
  "grape": { ru: "виноград", tr: "üzüm", nl: "druif", sv: "druva", pl: "winogrono", vi: "quả nho", id: "anggur", fi: "viinirypäle", no: "drue" },
  "strawberry": { ru: "клубника", tr: "çilek", nl: "aardbei", sv: "jordgubbe", pl: "truskawka", vi: "quả dâu tây", id: "stroberi", fi: "mansikka", no: "jordbær" },
  "tomato": { ru: "помидор", tr: "domates", nl: "tomaat", sv: "tomat", pl: "pomidor", vi: "cà chua", id: "tomat", fi: "tomaatti", no: "tomat" },
  "potato": { ru: "картофель", tr: "patates", nl: "aardappel", sv: "potatis", pl: "ziemniak", vi: "khoai tây", id: "kentang", fi: "peruna", no: "potet" },
  "onion": { ru: "лук", tr: "soğan", nl: "ui", sv: "lök", pl: "cebula", vi: "hành tây", id: "bawang", fi: "sipuli", no: "løk" },
  "carrot": { ru: "морковь", tr: "havuç", nl: "wortel", sv: "morot", pl: "marchewka", vi: "cà rốt", id: "wortel", fi: "porkkana", no: "gulrot" },
  "pepper": { ru: "перец", tr: "biber", nl: "paprika", sv: "paprika", pl: "papryka", vi: "ớt", id: "cabai", fi: "paprika", no: "paprika" },
  "coffee": { ru: "кофе", tr: "kahve", nl: "koffie", sv: "kaffe", pl: "kawa", vi: "cà phê", id: "kopi", fi: "kahvi", no: "kaffe" },
  "tea": { ru: "чай", tr: "çay", nl: "thee", sv: "te", pl: "herbata", vi: "trà", id: "teh", fi: "tee", no: "te" },
  "juice": { ru: "сок", tr: "meyve suyu", nl: "sap", sv: "juice", pl: "sok", vi: "nước ép", id: "jus", fi: "mehu", no: "juice" },
  "soup": { ru: "суп", tr: "çorba", nl: "soep", sv: "soppa", pl: "zupa", vi: "súp", id: "sup", fi: "keitto", no: "suppe" },
  "salad": { ru: "салат", tr: "salata", nl: "salade", sv: "sallad", pl: "sałatka", vi: "salad", id: "salad", fi: "salaatti", no: "salat" },
  "cake": { ru: "торт", tr: "pasta", nl: "taart", sv: "tårta", pl: "ciasto", vi: "bánh ngọt", id: "kue", fi: "kakku", no: "kake" },
  "chocolate": { ru: "шоколад", tr: "çikolata", nl: "chocolade", sv: "choklad", pl: "czekolada", vi: "sô cô la", id: "cokelat", fi: "suklaa", no: "sjokolade" },
  "ice cream": { ru: "мороженое", tr: "dondurma", nl: "ijs", sv: "glass", pl: "lody", vi: "kem", id: "es krim", fi: "jäätelö", no: "iskrem" },
  "oil": { ru: "масло", tr: "yağ", nl: "olie", sv: "olja", pl: "olej", vi: "dầu", id: "minyak", fi: "öljy", no: "olje" },
  "flour": { ru: "мука", tr: "un", nl: "meel", sv: "mjöl", pl: "mąka", vi: "bột mì", id: "tepung", fi: "jauhot", no: "mel" },
  "noodle": { ru: "лапша", tr: "erişte", nl: "noedel", sv: "nudel", pl: "makaron", vi: "mì", id: "mie", fi: "nuudeli", no: "nudel" },
  "bean": { ru: "фасоль", tr: "fasulye", nl: "boon", sv: "böna", pl: "fasola", vi: "đậu", id: "kacang", fi: "papu", no: "bønne" },
  "mushroom": { ru: "гриб", tr: "mantar", nl: "paddenstoel", sv: "svamp", pl: "grzyb", vi: "nấm", id: "jamur", fi: "sieni", no: "sopp" },
  "garlic": { ru: "чеснок", tr: "sarımsak", nl: "knoflook", sv: "vitlök", pl: "czosnek", vi: "tỏi", id: "bawang putih", fi: "valkosipuli", no: "hvitløk" },
  "lemon": { ru: "лимон", tr: "limon", nl: "citroen", sv: "citron", pl: "cytryna", vi: "chanh", id: "lemon", fi: "sitruuna", no: "sitron" },
  "mother": { ru: "мать", tr: "anne", nl: "moeder", sv: "mamma", pl: "matka", vi: "mẹ", id: "ibu", fi: "äiti", no: "mor" },
  "father": { ru: "отец", tr: "baba", nl: "vader", sv: "pappa", pl: "ojciec", vi: "bố", id: "ayah", fi: "isä", no: "far" },
  "sister": { ru: "сестра", tr: "kız kardeş", nl: "zus", sv: "syster", pl: "siostra", vi: "chị gái", id: "saudara perempuan", fi: "sisko", no: "søster" },
  "brother": { ru: "брат", tr: "erkek kardeş", nl: "broer", sv: "bror", pl: "brat", vi: "anh trai", id: "saudara laki-laki", fi: "veli", no: "bror" },
  "son": { ru: "сын", tr: "oğul", nl: "zoon", sv: "son", pl: "syn", vi: "con trai", id: "anak laki-laki", fi: "poika", no: "sønn" },
  "daughter": { ru: "дочь", tr: "kız", nl: "dochter", sv: "dotter", pl: "córka", vi: "con gái", id: "anak perempuan", fi: "tytär", no: "datter" },
  "grandmother": { ru: "бабушка", tr: "büyükanne", nl: "grootmoeder", sv: "mormor", pl: "babcia", vi: "bà", id: "nenek", fi: "isoäiti", no: "bestemor" },
  "grandfather": { ru: "дедушка", tr: "büyükbaba", nl: "grootvader", sv: "morfar", pl: "dziadek", vi: "ông", id: "kakek", fi: "isoisä", no: "bestefar" },
  "baby": { ru: "ребёнок", tr: "bebek", nl: "baby", sv: "bebis", pl: "niemowlę", vi: "em bé", id: "bayi", fi: "vauva", no: "baby" },
  "child": { ru: "ребёнок", tr: "çocuk", nl: "kind", sv: "barn", pl: "dziecko", vi: "trẻ em", id: "anak", fi: "lapsi", no: "barn" },
  "husband": { ru: "муж", tr: "koca", nl: "echtgenoot", sv: "make", pl: "mąż", vi: "chồng", id: "suami", fi: "aviomies", no: "ektemann" },
  "wife": { ru: "жена", tr: "karı", nl: "echtgenote", sv: "fru", pl: "żona", vi: "vợ", id: "istri", fi: "vaimo", no: "kone" },
  "uncle": { ru: "дядя", tr: "amca", nl: "oom", sv: "farbror", pl: "wujek", vi: "chú", id: "paman", fi: "setä", no: "onkel" },
  "aunt": { ru: "тётя", tr: "teyze", nl: "tante", sv: "moster", pl: "ciotka", vi: "dì", id: "bibi", fi: "täti", no: "tante" },
  "cousin": { ru: "двоюродный брат", tr: "kuzen", nl: "neef", sv: "kusin", pl: "kuzyn", vi: "anh họ", id: "sepupu", fi: "serkku", no: "fetter" },
  "friend": { ru: "друг", tr: "arkadaş", nl: "vriend", sv: "vän", pl: "przyjaciel", vi: "bạn bè", id: "teman", fi: "ystävä", no: "venn" },
  "neighbor": { ru: "сосед", tr: "komşu", nl: "buurman", sv: "granne", pl: "sąsiad", vi: "hàng xóm", id: "tetangga", fi: "naapuri", no: "nabo" },
  "family": { ru: "семья", tr: "aile", nl: "familie", sv: "familj", pl: "rodzina", vi: "gia đình", id: "keluarga", fi: "perhe", no: "familie" },
  "person": { ru: "человек", tr: "kişi", nl: "persoon", sv: "person", pl: "osoba", vi: "người", id: "orang", fi: "henkilö", no: "person" },
  "man": { ru: "мужчина", tr: "adam", nl: "man", sv: "man", pl: "mężczyzna", vi: "đàn ông", id: "pria", fi: "mies", no: "mann" },
  "woman": { ru: "женщина", tr: "kadın", nl: "vrouw", sv: "kvinna", pl: "kobieta", vi: "phụ nữ", id: "wanita", fi: "nainen", no: "kvinne" },
  "head": { ru: "голова", tr: "baş", nl: "hoofd", sv: "huvud", pl: "głowa", vi: "đầu", id: "kepala", fi: "pää", no: "hode" },
  "hair": { ru: "волосы", tr: "saç", nl: "haar", sv: "hår", pl: "włosy", vi: "tóc", id: "rambut", fi: "hiukset", no: "hår" },
  "face": { ru: "лицо", tr: "yüz", nl: "gezicht", sv: "ansikte", pl: "twarz", vi: "mặt", id: "wajah", fi: "kasvot", no: "ansikt" },
  "eye": { ru: "глаз", tr: "göz", nl: "oog", sv: "öga", pl: "oko", vi: "mắt", id: "mata", fi: "silmä", no: "øye" },
  "ear": { ru: "ухо", tr: "kulak", nl: "oor", sv: "öra", pl: "ucho", vi: "tai", id: "telinga", fi: "korva", no: "øre" },
  "nose": { ru: "нос", tr: "burun", nl: "neus", sv: "näsa", pl: "nos", vi: "mũi", id: "hidung", fi: "nenä", no: "nese" },
  "mouth": { ru: "рот", tr: "ağız", nl: "mond", sv: "mun", pl: "usta", vi: "miệng", id: "mulut", fi: "suu", no: "munn" },
  "tooth": { ru: "зуб", tr: "diş", nl: "tand", sv: "tand", pl: "ząb", vi: "răng", id: "gigi", fi: "hammas", no: "tann" },
  "tongue": { ru: "язык", tr: "dil", nl: "tong", sv: "tunga", pl: "język", vi: "lưỡi", id: "lidah", fi: "kieli", no: "tunge" },
  "neck": { ru: "шея", tr: "boyun", nl: "nek", sv: "hals", pl: "szyja", vi: "cổ", id: "leher", fi: "kaula", no: "nakke" },
  "shoulder": { ru: "плечо", tr: "omuz", nl: "schouder", sv: "axel", pl: "ramię", vi: "vai", id: "bahu", fi: "olkapää", no: "skulder" },
  "arm": { ru: "рука", tr: "kol", nl: "arm", sv: "arm", pl: "ramię", vi: "cánh tay", id: "lengan", fi: "käsivarsi", no: "arm" },
  "hand": { ru: "рука", tr: "el", nl: "hand", sv: "hand", pl: "ręka", vi: "bàn tay", id: "tangan", fi: "käsi", no: "hånd" },
  "finger": { ru: "палец", tr: "parmak", nl: "vinger", sv: "finger", pl: "palec", vi: "ngón tay", id: "jari", fi: "sormi", no: "finger" },
  "chest": { ru: "грудь", tr: "göğüs", nl: "borst", sv: "bröst", pl: "klatka piersiowa", vi: "ngực", id: "dada", fi: "rinta", no: "bryst" },
  "back": { ru: "спина", tr: "sırt", nl: "rug", sv: "rygg", pl: "plecy", vi: "lưng", id: "punggung", fi: "selkä", no: "rygg" },
  "stomach": { ru: "живот", tr: "mide", nl: "maag", sv: "mage", pl: "żołądek", vi: "bụng", id: "perut", fi: "vatsa", no: "mage" },
  "leg": { ru: "нога", tr: "bacak", nl: "been", sv: "ben", pl: "noga", vi: "chân", id: "kaki", fi: "jalka", no: "bein" },
  "knee": { ru: "колено", tr: "diz", nl: "knie", sv: "knä", pl: "kolano", vi: "đầu gối", id: "lutut", fi: "polvi", no: "kne" },
  "foot": { ru: "стопа", tr: "ayak", nl: "voet", sv: "fot", pl: "stopa", vi: "bàn chân", id: "kaki", fi: "jalka", no: "fot" },
  "heart": { ru: "сердце", tr: "kalp", nl: "hart", sv: "hjärta", pl: "serce", vi: "trái tim", id: "jantung", fi: "sydän", no: "hjerte" },
  "blood": { ru: "кровь", tr: "kan", nl: "bloed", sv: "blod", pl: "krew", vi: "máu", id: "darah", fi: "veri", no: "blod" },
  "bone": { ru: "кость", tr: "kemik", nl: "bot", sv: "ben", pl: "kość", vi: "xương", id: "tulang", fi: "luu", no: "bein" },
  "skin": { ru: "кожа", tr: "deri", nl: "huid", sv: "hud", pl: "skóra", vi: "da", id: "kulit", fi: "iho", no: "hud" },
  "shirt": { ru: "рубашка", tr: "gömlek", nl: "overhemd", sv: "skjorta", pl: "koszula", vi: "áo sơ mi", id: "kemeja", fi: "paita", no: "skjorte" },
  "pants": { ru: "брюки", tr: "pantolon", nl: "broek", sv: "byxor", pl: "spodnie", vi: "quần", id: "celana", fi: "housut", no: "bukser" },
  "dress": { ru: "платье", tr: "elbise", nl: "jurk", sv: "klänning", pl: "sukienka", vi: "váy", id: "gaun", fi: "mekko", no: "kjole" },
  "skirt": { ru: "юбка", tr: "etek", nl: "rok", sv: "kjol", pl: "spódnica", vi: "chân váy", id: "rok", fi: "hame", no: "skjørt" },
  "jacket": { ru: "куртка", tr: "ceket", nl: "jas", sv: "jacka", pl: "kurtka", vi: "áo khoác", id: "jaket", fi: "takki", no: "jakke" },
  "coat": { ru: "пальто", tr: "palto", nl: "jas", sv: "kappa", pl: "płaszcz", vi: "áo choàng", id: "mantel", fi: "takki", no: "frakk" },
  "shoes": { ru: "обувь", tr: "ayakkabı", nl: "schoenen", sv: "skor", pl: "buty", vi: "giày", id: "sepatu", fi: "kengät", no: "sko" },
  "boots": { ru: "сапоги", tr: "çizme", nl: "laarzen", sv: "stövlar", pl: "kozaki", vi: "ủng", id: "sepatu bot", fi: "saappaat", no: "støvler" },
  "hat": { ru: "шляпа", tr: "şapka", nl: "hoed", sv: "hatt", pl: "kapelusz", vi: "mũ", id: "topi", fi: "hattu", no: "hatt" },
  "socks": { ru: "носки", tr: "çorap", nl: "sokken", sv: "strumpor", pl: "skarpetki", vi: "tất", id: "kaus kaki", fi: "sukat", no: "sokker" },
  "gloves": { ru: "перчатки", tr: "eldiven", nl: "handschoenen", sv: "handskar", pl: "rękawiczki", vi: "găng tay", id: "sarung tangan", fi: "käsineet", no: "hansker" },
  "scarf": { ru: "шарф", tr: "eşarp", nl: "sjaal", sv: "halsduk", pl: "szalik", vi: "khăn quàng", id: "syal", fi: "huivi", no: "skjerf" },
  "belt": { ru: "ремень", tr: "kemer", nl: "riem", sv: "bälte", pl: "pasek", vi: "thắt lưng", id: "sabuk", fi: "vyö", no: "belte" },
  "bag": { ru: "сумка", tr: "çanta", nl: "tas", sv: "väska", pl: "torba", vi: "túi", id: "tas", fi: "laukku", no: "veske" },
  "umbrella": { ru: "зонт", tr: "şemsiye", nl: "paraplu", sv: "paraply", pl: "parasol", vi: "ô", id: "payung", fi: "sateenvarjo", no: "paraply" },
  "today": { ru: "сегодня", tr: "bugün", nl: "vandaag", sv: "idag", pl: "dzisiaj", vi: "hôm nay", id: "hari ini", fi: "tänään", no: "i dag" },
  "tomorrow": { ru: "завтра", tr: "yarın", nl: "morgen", sv: "imorgon", pl: "jutro", vi: "ngày mai", id: "besok", fi: "huomenna", no: "i morgen" },
  "yesterday": { ru: "вчера", tr: "dün", nl: "gisteren", sv: "igår", pl: "wczoraj", vi: "hôm qua", id: "kemarin", fi: "eilen", no: "i går" },
  "morning": { ru: "утро", tr: "sabah", nl: "ochtend", sv: "morgon", pl: "rano", vi: "buổi sáng", id: "pagi", fi: "aamu", no: "morgen" },
  "afternoon": { ru: "день", tr: "öğleden sonra", nl: "middag", sv: "eftermiddag", pl: "popołudnie", vi: "buổi chiều", id: "sore", fi: "iltapäivä", no: "ettermiddag" },
  "evening": { ru: "вечер", tr: "akşam", nl: "avond", sv: "kväll", pl: "wieczór", vi: "buổi tối", id: "malam", fi: "ilta", no: "kveld" },
  "night": { ru: "ночь", tr: "gece", nl: "nacht", sv: "natt", pl: "noc", vi: "đêm", id: "malam", fi: "yö", no: "natt" },
  "monday": { ru: "понедельник", tr: "pazartesi", nl: "maandag", sv: "måndag", pl: "poniedziałek", vi: "thứ hai", id: "Senin", fi: "maanantai", no: "mandag" },
  "tuesday": { ru: "вторник", tr: "salı", nl: "dinsdag", sv: "tisdag", pl: "wtorek", vi: "thứ ba", id: "Selasa", fi: "tiistai", no: "tirsdag" },
  "wednesday": { ru: "среда", tr: "çarşamba", nl: "woensdag", sv: "onsdag", pl: "środa", vi: "thứ tư", id: "Rabu", fi: "keskiviikko", no: "onsdag" },
  "thursday": { ru: "четверг", tr: "perşembe", nl: "donderdag", sv: "torsdag", pl: "czwartek", vi: "thứ năm", id: "Kamis", fi: "torstai", no: "torsdag" },
  "friday": { ru: "пятница", tr: "cuma", nl: "vrijdag", sv: "fredag", pl: "piątek", vi: "thứ sáu", id: "Jumat", fi: "perjantai", no: "fredag" },
  "saturday": { ru: "суббота", tr: "cumartesi", nl: "zaterdag", sv: "lördag", pl: "sobota", vi: "thứ bảy", id: "Sabtu", fi: "lauantai", no: "lørdag" },
  "sunday": { ru: "воскресенье", tr: "pazar", nl: "zondag", sv: "söndag", pl: "niedziela", vi: "chủ nhật", id: "Minggu", fi: "sunnuntai", no: "søndag" },
  "january": { ru: "январь", tr: "ocak", nl: "januari", sv: "januari", pl: "styczeń", vi: "tháng một", id: "Januari", fi: "tammikuu", no: "januar" },
  "february": { ru: "февраль", tr: "şubat", nl: "februari", sv: "februari", pl: "luty", vi: "tháng hai", id: "Februari", fi: "helmikuu", no: "februar" },
  "march": { ru: "март", tr: "mart", nl: "maart", sv: "mars", pl: "marzec", vi: "tháng ba", id: "Maret", fi: "maaliskuu", no: "mars" },
  "april": { ru: "апрель", tr: "nisan", nl: "april", sv: "april", pl: "kwiecień", vi: "tháng tư", id: "April", fi: "huhtikuu", no: "april" },
  "may": { ru: "май", tr: "mayıs", nl: "mei", sv: "maj", pl: "maj", vi: "tháng năm", id: "Mei", fi: "toukokuu", no: "mai" },
  "june": { ru: "июнь", tr: "haziran", nl: "juni", sv: "juni", pl: "czerwiec", vi: "tháng sáu", id: "Juni", fi: "kesäkuu", no: "juni" },
  "year": { ru: "год", tr: "yıl", nl: "jaar", sv: "år", pl: "rok", vi: "năm", id: "tahun", fi: "vuosi", no: "år" },
  "month": { ru: "месяц", tr: "ay", nl: "maand", sv: "månad", pl: "miesiąc", vi: "tháng", id: "bulan", fi: "kuukausi", no: "måned" },
  "week": { ru: "неделя", tr: "hafta", nl: "week", sv: "vecka", pl: "tydzień", vi: "tuần", id: "minggu", fi: "viikko", no: "uke" },
  "day": { ru: "день", tr: "gün", nl: "dag", sv: "dag", pl: "dzień", vi: "ngày", id: "hari", fi: "päivä", no: "dag" },
  "hour": { ru: "час", tr: "saat", nl: "uur", sv: "timme", pl: "godzina", vi: "giờ", id: "jam", fi: "tunti", no: "time" },
  "minute": { ru: "минута", tr: "dakika", nl: "minuut", sv: "minut", pl: "minuta", vi: "phút", id: "menit", fi: "minuutti", no: "minutt" },
  "now": { ru: "сейчас", tr: "şimdi", nl: "nu", sv: "nu", pl: "teraz", vi: "bây giờ", id: "sekarang", fi: "nyt", no: "nå" },
  "always": { ru: "всегда", tr: "her zaman", nl: "altijd", sv: "alltid", pl: "zawsze", vi: "luôn luôn", id: "selalu", fi: "aina", no: "alltid" },
  "never": { ru: "никогда", tr: "asla", nl: "nooit", sv: "aldrig", pl: "nigdy", vi: "không bao giờ", id: "tidak pernah", fi: "ei koskaan", no: "aldri" },
  "sun": { ru: "солнце", tr: "güneş", nl: "zon", sv: "sol", pl: "słońce", vi: "mặt trời", id: "matahari", fi: "aurinko", no: "sol" },
  "moon": { ru: "луна", tr: "ay", nl: "maan", sv: "måne", pl: "księżyc", vi: "mặt trăng", id: "bulan", fi: "kuu", no: "måne" },
  "star": { ru: "звезда", tr: "yıldız", nl: "ster", sv: "stjärna", pl: "gwiazda", vi: "ngôi sao", id: "bintang", fi: "tähti", no: "stjerne" },
  "sky": { ru: "небо", tr: "gökyüzü", nl: "lucht", sv: "himmel", pl: "niebo", vi: "bầu trời", id: "langit", fi: "taivas", no: "himmel" },
  "cloud": { ru: "облако", tr: "bulut", nl: "wolk", sv: "moln", pl: "chmura", vi: "đám mây", id: "awan", fi: "pilvi", no: "sky" },
  "rain": { ru: "дождь", tr: "yağmur", nl: "regen", sv: "regn", pl: "deszcz", vi: "mưa", id: "hujan", fi: "sade", no: "regn" },
  "snow": { ru: "снег", tr: "kar", nl: "sneeuw", sv: "snö", pl: "śnieg", vi: "tuyết", id: "salju", fi: "lumi", no: "snø" },
  "wind": { ru: "ветер", tr: "rüzgâr", nl: "wind", sv: "vind", pl: "wiatr", vi: "gió", id: "angin", fi: "tuuli", no: "vind" },
  "storm": { ru: "буря", tr: "fırtına", nl: "storm", sv: "storm", pl: "burza", vi: "bão", id: "badai", fi: "myrsky", no: "storm" },
  "hot": { ru: "жарко", tr: "sıcak", nl: "heet", sv: "het", pl: "gorący", vi: "nóng", id: "panas", fi: "kuuma", no: "varm" },
  "cold": { ru: "холодно", tr: "soğuk", nl: "koud", sv: "kall", pl: "zimny", vi: "lạnh", id: "dingin", fi: "kylmä", no: "kald" },
  "tree": { ru: "дерево", tr: "ağaç", nl: "boom", sv: "träd", pl: "drzewo", vi: "cây", id: "pohon", fi: "puu", no: "tre" },
  "flower": { ru: "цветок", tr: "çiçek", nl: "bloem", sv: "blomma", pl: "kwiat", vi: "hoa", id: "bunga", fi: "kukka", no: "blomst" },
  "grass": { ru: "трава", tr: "çimen", nl: "gras", sv: "gräs", pl: "trawa", vi: "cỏ", id: "rumput", fi: "ruoho", no: "gress" },
  "mountain": { ru: "гора", tr: "dağ", nl: "berg", sv: "berg", pl: "góra", vi: "núi", id: "gunung", fi: "vuori", no: "fjell" },
  "river": { ru: "река", tr: "nehir", nl: "rivier", sv: "flod", pl: "rzeka", vi: "sông", id: "sungai", fi: "joki", no: "elv" },
  "sea": { ru: "море", tr: "deniz", nl: "zee", sv: "hav", pl: "morze", vi: "biển", id: "laut", fi: "meri", no: "hav" },
  "lake": { ru: "озеро", tr: "göl", nl: "meer", sv: "sjö", pl: "jezioro", vi: "hồ", id: "danau", fi: "järvi", no: "innsjø" },
  "forest": { ru: "лес", tr: "orman", nl: "bos", sv: "skog", pl: "las", vi: "rừng", id: "hutan", fi: "metsä", no: "skog" },
  "island": { ru: "остров", tr: "ada", nl: "eiland", sv: "ö", pl: "wyspa", vi: "đảo", id: "pulau", fi: "saari", no: "øy" },
  "earth": { ru: "земля", tr: "dünya", nl: "aarde", sv: "jord", pl: "ziemia", vi: "trái đất", id: "bumi", fi: "maa", no: "jord" },
  "fire": { ru: "огонь", tr: "ateş", nl: "vuur", sv: "eld", pl: "ogień", vi: "lửa", id: "api", fi: "tuli", no: "ild" },
  "ice": { ru: "лёд", tr: "buz", nl: "ijs", sv: "is", pl: "lód", vi: "đá", id: "es", fi: "jää", no: "is" },
  "stone": { ru: "камень", tr: "taş", nl: "steen", sv: "sten", pl: "kamień", vi: "đá", id: "batu", fi: "kivi", no: "stein" },
  "sand": { ru: "песок", tr: "kum", nl: "zand", sv: "sand", pl: "piasek", vi: "cát", id: "pasir", fi: "hiekka", no: "sand" },
  "house": { ru: "дом", tr: "ev", nl: "huis", sv: "hus", pl: "dom", vi: "nhà", id: "rumah", fi: "talo", no: "hus" },
  "door": { ru: "дверь", tr: "kapı", nl: "deur", sv: "dörr", pl: "drzwi", vi: "cửa", id: "pintu", fi: "ovi", no: "dør" },
  "window": { ru: "окно", tr: "pencere", nl: "raam", sv: "fönster", pl: "okno", vi: "cửa sổ", id: "jendela", fi: "ikkuna", no: "vindu" },
  "room": { ru: "комната", tr: "oda", nl: "kamer", sv: "rum", pl: "pokój", vi: "phòng", id: "kamar", fi: "huone", no: "rom" },
  "kitchen": { ru: "кухня", tr: "mutfak", nl: "keuken", sv: "kök", pl: "kuchnia", vi: "nhà bếp", id: "dapur", fi: "keittiö", no: "kjøkken" },
  "bathroom": { ru: "ванная", tr: "banyo", nl: "badkamer", sv: "badrum", pl: "łazienka", vi: "phòng tắm", id: "kamar mandi", fi: "kylpyhuone", no: "bad" },
  "bedroom": { ru: "спальня", tr: "yatak odası", nl: "slaapkamer", sv: "sovrum", pl: "sypialnia", vi: "phòng ngủ", id: "kamar tidur", fi: "makuuhuone", no: "soverom" },
  "table": { ru: "стол", tr: "masa", nl: "tafel", sv: "bord", pl: "stół", vi: "bàn", id: "meja", fi: "pöytä", no: "bord" },
  "chair": { ru: "стул", tr: "sandalye", nl: "stoel", sv: "stol", pl: "krzesło", vi: "ghế", id: "kursi", fi: "tuoli", no: "stol" },
  "bed": { ru: "кровать", tr: "yatak", nl: "bed", sv: "säng", pl: "łóżko", vi: "giường", id: "tempat tidur", fi: "sänky", no: "seng" },
  "mirror": { ru: "зеркало", tr: "ayna", nl: "spiegel", sv: "spegel", pl: "lustro", vi: "gương", id: "cermin", fi: "peili", no: "speil" },
  "lamp": { ru: "лампа", tr: "lamba", nl: "lamp", sv: "lampa", pl: "lampa", vi: "đèn", id: "lampu", fi: "lamppu", no: "lampe" },
  "stairs": { ru: "лестница", tr: "merdiven", nl: "trap", sv: "trappa", pl: "schody", vi: "cầu thang", id: "tangga", fi: "portaat", no: "trapp" },
  "wall": { ru: "стена", tr: "duvar", nl: "muur", sv: "vägg", pl: "ściana", vi: "tường", id: "dinding", fi: "seinä", no: "vegg" },
  "floor": { ru: "пол", tr: "zemin", nl: "vloer", sv: "golv", pl: "podłoga", vi: "sàn nhà", id: "lantai", fi: "lattia", no: "gulv" },
  "roof": { ru: "крыша", tr: "çatı", nl: "dak", sv: "tak", pl: "dach", vi: "mái nhà", id: "atap", fi: "katto", no: "tak" },
  "garden": { ru: "сад", tr: "bahçe", nl: "tuin", sv: "trädgård", pl: "ogród", vi: "vườn", id: "kebun", fi: "puutarha", no: "hage" },
  "key": { ru: "ключ", tr: "anahtar", nl: "sleutel", sv: "nyckel", pl: "klucz", vi: "chìa khóa", id: "kunci", fi: "avain", no: "nøkkel" },
  "clock": { ru: "часы", tr: "saat", nl: "klok", sv: "klocka", pl: "zegar", vi: "đồng hồ", id: "jam", fi: "kello", no: "klokke" },
  "telephone": { ru: "телефон", tr: "telefon", nl: "telefoon", sv: "telefon", pl: "telefon", vi: "điện thoại", id: "telepon", fi: "puhelin", no: "telefon" },
  "car": { ru: "машина", tr: "araba", nl: "auto", sv: "bil", pl: "samochód", vi: "xe hơi", id: "mobil", fi: "auto", no: "bil" },
  "bus": { ru: "автобус", tr: "otobüs", nl: "bus", sv: "buss", pl: "autobus", vi: "xe buýt", id: "bus", fi: "bussi", no: "buss" },
  "train": { ru: "поезд", tr: "tren", nl: "trein", sv: "tåg", pl: "pociąg", vi: "xe lửa", id: "kereta api", fi: "juna", no: "tog" },
  "airplane": { ru: "самолёт", tr: "uçak", nl: "vliegtuig", sv: "flygplan", pl: "samolot", vi: "máy bay", id: "pesawat", fi: "lentokone", no: "fly" },
  "bicycle": { ru: "велосипед", tr: "bisiklet", nl: "fiets", sv: "cykel", pl: "rower", vi: "xe đạp", id: "sepeda", fi: "polkupyörä", no: "sykkel" },
  "boat": { ru: "лодка", tr: "tekne", nl: "boot", sv: "båt", pl: "łódź", vi: "thuyền", id: "perahu", fi: "vene", no: "båt" },
  "ship": { ru: "корабль", tr: "gemi", nl: "schip", sv: "skepp", pl: "statek", vi: "tàu", id: "kapal", fi: "laiva", no: "skip" },
  "taxi": { ru: "такси", tr: "taksi", nl: "taxi", sv: "taxi", pl: "taksówka", vi: "xe taxi", id: "taksi", fi: "taksi", no: "taxi" },
  "motorcycle": { ru: "мотоцикл", tr: "motosiklet", nl: "motorfiets", sv: "motorcykel", pl: "motocykl", vi: "xe máy", id: "sepeda motor", fi: "moottoripyörä", no: "motorsykkel" },
  "truck": { ru: "грузовик", tr: "kamyon", nl: "vrachtwagen", sv: "lastbil", pl: "ciężarówka", vi: "xe tải", id: "truk", fi: "kuorma-auto", no: "lastebil" },
  "subway": { ru: "метро", tr: "metro", nl: "metro", sv: "tunnelbana", pl: "metro", vi: "tàu điện ngầm", id: "kereta bawah tanah", fi: "metro", no: "t-bane" },
  "road": { ru: "дорога", tr: "yol", nl: "weg", sv: "väg", pl: "droga", vi: "đường", id: "jalan", fi: "tie", no: "vei" },
  "bridge": { ru: "мост", tr: "köprü", nl: "brug", sv: "bro", pl: "most", vi: "cầu", id: "jembatan", fi: "silta", no: "bro" },
  "ticket": { ru: "билет", tr: "bilet", nl: "kaartje", sv: "biljett", pl: "bilet", vi: "vé", id: "tiket", fi: "lippu", no: "billett" },
  "map": { ru: "карта", tr: "harita", nl: "kaart", sv: "karta", pl: "mapa", vi: "bản đồ", id: "peta", fi: "kartta", no: "kart" },
  "teacher": { ru: "учитель", tr: "öğretmen", nl: "leraar", sv: "lärare", pl: "nauczyciel", vi: "giáo viên", id: "guru", fi: "opettaja", no: "lærer" },
  "doctor": { ru: "врач", tr: "doktor", nl: "dokter", sv: "läkare", pl: "lekarz", vi: "bác sĩ", id: "dokter", fi: "lääkäri", no: "lege" },
  "nurse": { ru: "медсестра", tr: "hemşire", nl: "verpleegster", sv: "sjuksköterska", pl: "pielęgniarka", vi: "y tá", id: "perawat", fi: "sairaanhoitaja", no: "sykepleier" },
  "engineer": { ru: "инженер", tr: "mühendis", nl: "ingenieur", sv: "ingenjör", pl: "inżynier", vi: "kỹ sư", id: "insinyur", fi: "insinööri", no: "ingeniør" },
  "student": { ru: "студент", tr: "öğrenci", nl: "student", sv: "student", pl: "student", vi: "học sinh", id: "siswa", fi: "opiskelija", no: "student" },
  "police": { ru: "полиция", tr: "polis", nl: "politie", sv: "polis", pl: "policja", vi: "cảnh sát", id: "polisi", fi: "poliisi", no: "politi" },
  "farmer": { ru: "фермер", tr: "çiftçi", nl: "boer", sv: "bonde", pl: "rolnik", vi: "nông dân", id: "petani", fi: "maanviljelijä", no: "bonde" },
  "cook": { ru: "повар", tr: "aşçı", nl: "kok", sv: "kock", pl: "kucharz", vi: "đầu bếp", id: "koki", fi: "kokki", no: "kokk" },
  "driver": { ru: "водитель", tr: "sürücü", nl: "chauffeur", sv: "förare", pl: "kierowca", vi: "tài xế", id: "sopir", fi: "kuljettaja", no: "sjåfør" },
  "lawyer": { ru: "адвокат", tr: "avukat", nl: "advocaat", sv: "advokat", pl: "prawnik", vi: "luật sư", id: "pengacara", fi: "lakimies", no: "advokat" },
  "artist": { ru: "художник", tr: "sanatçı", nl: "kunstenaar", sv: "konstnär", pl: "artysta", vi: "nghệ sĩ", id: "seniman", fi: "taiteilija", no: "kunstner" },
  "musician": { ru: "музыкант", tr: "müzisyen", nl: "muzikant", sv: "musiker", pl: "muzyk", vi: "nhạc sĩ", id: "musisi", fi: "muusikko", no: "musiker" },
  "writer": { ru: "писатель", tr: "yazar", nl: "schrijver", sv: "författare", pl: "pisarz", vi: "nhà văn", id: "penulis", fi: "kirjailija", no: "forfatter" },
  "pilot": { ru: "пилот", tr: "pilot", nl: "piloot", sv: "pilot", pl: "pilot", vi: "phi công", id: "pilot", fi: "lentäjä", no: "pilot" },
  "soldier": { ru: "солдат", tr: "asker", nl: "soldaat", sv: "soldat", pl: "żołnierz", vi: "lính", id: "tentara", fi: "sotilas", no: "soldat" },
  "to be": { ru: "быть", tr: "olmak", nl: "zijn", sv: "vara", pl: "być", vi: "là", id: "menjadi", fi: "olla", no: "være" },
  "to have": { ru: "иметь", tr: "sahip olmak", nl: "hebben", sv: "ha", pl: "mieć", vi: "có", id: "mempunyai", fi: "omistaa", no: "ha" },
  "to do": { ru: "делать", tr: "yapmak", nl: "doen", sv: "göra", pl: "robić", vi: "làm", id: "melakukan", fi: "tehdä", no: "gjøre" },
  "to go": { ru: "идти", tr: "gitmek", nl: "gaan", sv: "gå", pl: "iść", vi: "đi", id: "pergi", fi: "mennä", no: "gå" },
  "to come": { ru: "приходить", tr: "gelmek", nl: "komen", sv: "komma", pl: "przyjść", vi: "đến", id: "datang", fi: "tulla", no: "komme" },
  "to say": { ru: "говорить", tr: "demek", nl: "zeggen", sv: "säga", pl: "mówić", vi: "nói", id: "berkata", fi: "sanoa", no: "si" },
  "to see": { ru: "видеть", tr: "görmek", nl: "zien", sv: "se", pl: "widzieć", vi: "nhìn", id: "melihat", fi: "nähdä", no: "se" },
  "to know": { ru: "знать", tr: "bilmek", nl: "weten", sv: "veta", pl: "wiedzieć", vi: "biết", id: "tahu", fi: "tietää", no: "vite" },
  "to think": { ru: "думать", tr: "düşünmek", nl: "denken", sv: "tänka", pl: "myśleć", vi: "nghĩ", id: "berpikir", fi: "ajatella", no: "tenke" },
  "to want": { ru: "хотеть", tr: "istemek", nl: "willen", sv: "vilja", pl: "chcieć", vi: "muốn", id: "ingin", fi: "haluta", no: "ville" },
  "to eat": { ru: "есть", tr: "yemek", nl: "eten", sv: "äta", pl: "jeść", vi: "ăn", id: "makan", fi: "syödä", no: "spise" },
  "to drink": { ru: "пить", tr: "içmek", nl: "drinken", sv: "dricka", pl: "pić", vi: "uống", id: "minum", fi: "juoda", no: "drikke" },
  "to sleep": { ru: "спать", tr: "uyumak", nl: "slapen", sv: "sova", pl: "spać", vi: "ngủ", id: "tidur", fi: "nukkua", no: "sove" },
  "to walk": { ru: "ходить", tr: "yürümek", nl: "lopen", sv: "gå", pl: "chodzić", vi: "đi bộ", id: "berjalan", fi: "kävellä", no: "gå" },
  "to run": { ru: "бежать", tr: "koşmak", nl: "rennen", sv: "springa", pl: "biegać", vi: "chạy", id: "berlari", fi: "juosta", no: "løpe" },
  "to read": { ru: "читать", tr: "okumak", nl: "lezen", sv: "läsa", pl: "czytać", vi: "đọc", id: "membaca", fi: "lukea", no: "lese" },
  "to write": { ru: "писать", tr: "yazmak", nl: "schrijven", sv: "skriva", pl: "pisać", vi: "viết", id: "menulis", fi: "kirjoittaa", no: "skrive" },
  "to speak": { ru: "говорить", tr: "konuşmak", nl: "spreken", sv: "tala", pl: "mówić", vi: "nói", id: "berbicara", fi: "puhua", no: "snakke" },
  "to listen": { ru: "слушать", tr: "dinlemek", nl: "luisteren", sv: "lyssna", pl: "słuchać", vi: "nghe", id: "mendengarkan", fi: "kuunnella", no: "lytte" },
  "to understand": { ru: "понимать", tr: "anlamak", nl: "begrijpen", sv: "förstå", pl: "rozumieć", vi: "hiểu", id: "memahami", fi: "ymmärtää", no: "forstå" },
  "to give": { ru: "давать", tr: "vermek", nl: "geven", sv: "ge", pl: "dawać", vi: "cho", id: "memberi", fi: "antaa", no: "gi" },
  "to take": { ru: "брать", tr: "almak", nl: "nemen", sv: "ta", pl: "brać", vi: "lấy", id: "mengambil", fi: "ottaa", no: "ta" },
  "to buy": { ru: "покупать", tr: "satın almak", nl: "kopen", sv: "köpa", pl: "kupować", vi: "mua", id: "membeli", fi: "ostaa", no: "kjøpe" },
  "to sell": { ru: "продавать", tr: "satmak", nl: "verkopen", sv: "sälja", pl: "sprzedawać", vi: "bán", id: "menjual", fi: "myydä", no: "selge" },
  "to open": { ru: "открывать", tr: "açmak", nl: "openen", sv: "öppna", pl: "otwierać", vi: "mở", id: "membuka", fi: "avata", no: "åpne" },
  "to close": { ru: "закрывать", tr: "kapatmak", nl: "sluiten", sv: "stänga", pl: "zamykać", vi: "đóng", id: "menutup", fi: "sulkea", no: "lukke" },
  "to sit": { ru: "сидеть", tr: "oturmak", nl: "zitten", sv: "sitta", pl: "siedzieć", vi: "ngồi", id: "duduk", fi: "istua", no: "sitte" },
  "to stand": { ru: "стоять", tr: "ayakta durmak", nl: "staan", sv: "stå", pl: "stać", vi: "đứng", id: "berdiri", fi: "seistä", no: "stå" },
  "to love": { ru: "любить", tr: "sevmek", nl: "houden van", sv: "älska", pl: "kochać", vi: "yêu", id: "mencintai", fi: "rakastaa", no: "elske" },
  "to like": { ru: "нравиться", tr: "beğenmek", nl: "leuk vinden", sv: "gilla", pl: "lubić", vi: "thích", id: "suka", fi: "pitää", no: "like" },
  "to help": { ru: "помогать", tr: "yardım etmek", nl: "helpen", sv: "hjälpa", pl: "pomagać", vi: "giúp", id: "membantu", fi: "auttaa", no: "hjelpe" },
  "to learn": { ru: "учиться", tr: "öğrenmek", nl: "leren", sv: "lära sig", pl: "uczyć się", vi: "học", id: "belajar", fi: "oppia", no: "lære" },
  "to teach": { ru: "учить", tr: "öğretmek", nl: "onderwijzen", sv: "lära", pl: "uczyć", vi: "dạy", id: "mengajar", fi: "opettaa", no: "undervise" },
  "to work": { ru: "работать", tr: "çalışmak", nl: "werken", sv: "arbeta", pl: "pracować", vi: "làm việc", id: "bekerja", fi: "työskennellä", no: "jobbe" },
  "to play": { ru: "играть", tr: "oynamak", nl: "spelen", sv: "spela", pl: "grać", vi: "chơi", id: "bermain", fi: "pelata", no: "spille" },
  "to sing": { ru: "петь", tr: "şarkı söylemek", nl: "zingen", sv: "sjunga", pl: "śpiewać", vi: "hát", id: "bernyanyi", fi: "laulaa", no: "synge" },
  "to dance": { ru: "танцевать", tr: "dans etmek", nl: "dansen", sv: "dansa", pl: "tańczyć", vi: "nhảy", id: "menari", fi: "tanssia", no: "danse" },
  "to swim": { ru: "плавать", tr: "yüzmek", nl: "zwemmen", sv: "simma", pl: "pływać", vi: "bơi", id: "berenang", fi: "uida", no: "svømme" },
  "to fly": { ru: "летать", tr: "uçmak", nl: "vliegen", sv: "flyga", pl: "latać", vi: "bay", id: "terbang", fi: "lentää", no: "fly" },
  "to wait": { ru: "ждать", tr: "beklemek", nl: "wachten", sv: "vänta", pl: "czekać", vi: "đợi", id: "menunggu", fi: "odottaa", no: "vente" },
  "to find": { ru: "находить", tr: "bulmak", nl: "vinden", sv: "hitta", pl: "znajdować", vi: "tìm", id: "menemukan", fi: "löytää", no: "finne" },
  "to make": { ru: "делать", tr: "yapmak", nl: "maken", sv: "göra", pl: "robić", vi: "làm", id: "membuat", fi: "tehdä", no: "lage" },
  "to put": { ru: "класть", tr: "koymak", nl: "zetten", sv: "lägga", pl: "kłaść", vi: "đặt", id: "meletakkan", fi: "laittaa", no: "legge" },
  "to use": { ru: "использовать", tr: "kullanmak", nl: "gebruiken", sv: "använda", pl: "używać", vi: "sử dụng", id: "menggunakan", fi: "käyttää", no: "bruke" },
  "to try": { ru: "пробовать", tr: "denemek", nl: "proberen", sv: "försöka", pl: "próbować", vi: "thử", id: "mencoba", fi: "yrittää", no: "prøve" },
  "to begin": { ru: "начинать", tr: "başlamak", nl: "beginnen", sv: "börja", pl: "zaczynać", vi: "bắt đầu", id: "mulai", fi: "aloittaa", no: "begynne" },
  "to finish": { ru: "заканчивать", tr: "bitirmek", nl: "afmaken", sv: "avsluta", pl: "kończyć", vi: "kết thúc", id: "menyelesaikan", fi: "lopettaa", no: "fullføre" },
  "to send": { ru: "отправлять", tr: "göndermek", nl: "sturen", sv: "skicka", pl: "wysyłać", vi: "gửi", id: "mengirim", fi: "lähettää", no: "sende" },
  "to receive": { ru: "получать", tr: "almak", nl: "ontvangen", sv: "ta emot", pl: "otrzymywać", vi: "nhận", id: "menerima", fi: "vastaanottaa", no: "motta" },
  "to remember": { ru: "помнить", tr: "hatırlamak", nl: "onthouden", sv: "minnas", pl: "pamiętać", vi: "nhớ", id: "mengingat", fi: "muistaa", no: "huske" },
  "big": { ru: "большой", tr: "büyük", nl: "groot", sv: "stor", pl: "duży", vi: "lớn", id: "besar", fi: "suuri", no: "stor" },
  "small": { ru: "маленький", tr: "küçük", nl: "klein", sv: "liten", pl: "mały", vi: "nhỏ", id: "kecil", fi: "pieni", no: "liten" },
  "long": { ru: "длинный", tr: "uzun", nl: "lang", sv: "lång", pl: "długi", vi: "dài", id: "panjang", fi: "pitkä", no: "lang" },
  "short": { ru: "короткий", tr: "kısa", nl: "kort", sv: "kort", pl: "krótki", vi: "ngắn", id: "pendek", fi: "lyhyt", no: "kort" },
  "tall": { ru: "высокий", tr: "uzun boylu", nl: "lang", sv: "lång", pl: "wysoki", vi: "cao", id: "tinggi", fi: "pitkä", no: "høy" },
  "new": { ru: "новый", tr: "yeni", nl: "nieuw", sv: "ny", pl: "nowy", vi: "mới", id: "baru", fi: "uusi", no: "ny" },
  "old": { ru: "старый", tr: "eski", nl: "oud", sv: "gammal", pl: "stary", vi: "cũ", id: "lama", fi: "vanha", no: "gammel" },
  "good": { ru: "хороший", tr: "iyi", nl: "goed", sv: "bra", pl: "dobry", vi: "tốt", id: "baik", fi: "hyvä", no: "god" },
  "bad": { ru: "плохой", tr: "kötü", nl: "slecht", sv: "dålig", pl: "zły", vi: "xấu", id: "buruk", fi: "huono", no: "dårlig" },
  "beautiful": { ru: "красивый", tr: "güzel", nl: "mooi", sv: "vacker", pl: "piękny", vi: "đẹp", id: "cantik", fi: "kaunis", no: "vakker" },
  "ugly": { ru: "некрасивый", tr: "çirkin", nl: "lelijk", sv: "ful", pl: "brzydki", vi: "xấu xí", id: "jelek", fi: "ruma", no: "stygg" },
  "fast": { ru: "быстрый", tr: "hızlı", nl: "snel", sv: "snabb", pl: "szybki", vi: "nhanh", id: "cepat", fi: "nopea", no: "rask" },
  "slow": { ru: "медленный", tr: "yavaş", nl: "langzaam", sv: "långsam", pl: "wolny", vi: "chậm", id: "lambat", fi: "hidas", no: "langsom" },
  "heavy": { ru: "тяжёлый", tr: "ağır", nl: "zwaar", sv: "tung", pl: "ciężki", vi: "nặng", id: "berat", fi: "raskas", no: "tung" },
  "easy": { ru: "лёгкий", tr: "kolay", nl: "makkelijk", sv: "lätt", pl: "łatwy", vi: "dễ", id: "mudah", fi: "helppo", no: "lett" },
  "difficult": { ru: "трудный", tr: "zor", nl: "moeilijk", sv: "svår", pl: "trudny", vi: "khó", id: "sulit", fi: "vaikea", no: "vanskelig" },
  "clean": { ru: "чистый", tr: "temiz", nl: "schoon", sv: "ren", pl: "czysty", vi: "sạch", id: "bersih", fi: "puhdas", no: "ren" },
  "dirty": { ru: "грязный", tr: "kirli", nl: "vies", sv: "smutsig", pl: "brudny", vi: "bẩn", id: "kotor", fi: "likainen", no: "skitten" },
  "rich": { ru: "богатый", tr: "zengin", nl: "rijk", sv: "rik", pl: "bogaty", vi: "giàu", id: "kaya", fi: "rikas", no: "rik" },
  "poor": { ru: "бедный", tr: "fakir", nl: "arm", sv: "fattig", pl: "biedny", vi: "nghèo", id: "miskin", fi: "köyhä", no: "fattig" },
  "full": { ru: "полный", tr: "dolu", nl: "vol", sv: "full", pl: "pełny", vi: "đầy", id: "penuh", fi: "täysi", no: "full" },
  "empty": { ru: "пустой", tr: "boş", nl: "leeg", sv: "tom", pl: "pusty", vi: "trống", id: "kosong", fi: "tyhjä", no: "tom" },
  "strong": { ru: "сильный", tr: "güçlü", nl: "sterk", sv: "stark", pl: "silny", vi: "mạnh", id: "kuat", fi: "vahva", no: "sterk" },
  "weak": { ru: "слабый", tr: "zayıf", nl: "zwak", sv: "svag", pl: "słaby", vi: "yếu", id: "lemah", fi: "heikko", no: "svak" },
  "young": { ru: "молодой", tr: "genç", nl: "jong", sv: "ung", pl: "młody", vi: "trẻ", id: "muda", fi: "nuori", no: "ung" },
  "right": { ru: "правильный", tr: "doğru", nl: "juist", sv: "rätt", pl: "prawidłowy", vi: "đúng", id: "benar", fi: "oikea", no: "riktig" },
  "wrong": { ru: "неправильный", tr: "yanlış", nl: "fout", sv: "fel", pl: "błędny", vi: "sai", id: "salah", fi: "väärä", no: "galt" },
  "happy": { ru: "счастливый", tr: "mutlu", nl: "gelukkig", sv: "lycklig", pl: "szczęśliwy", vi: "hạnh phúc", id: "bahagia", fi: "onnellinen", no: "lykkelig" },
  "sad": { ru: "грустный", tr: "üzgün", nl: "verdrietig", sv: "ledsen", pl: "smutny", vi: "buồn", id: "sedih", fi: "surullinen", no: "trist" },
  "important": { ru: "важный", tr: "önemli", nl: "belangrijk", sv: "viktig", pl: "ważny", vi: "quan trọng", id: "penting", fi: "tärkeä", no: "viktig" },
  "angry": { ru: "злой", tr: "kızgın", nl: "boos", sv: "arg", pl: "zły", vi: "tức giận", id: "marah", fi: "vihainen", no: "sint" },
  "scared": { ru: "испуганный", tr: "korkmuş", nl: "bang", sv: "rädd", pl: "przestraszony", vi: "sợ", id: "takut", fi: "pelokas", no: "redd" },
  "tired": { ru: "усталый", tr: "yorgun", nl: "moe", sv: "trött", pl: "zmęczony", vi: "mệt", id: "lelah", fi: "väsynyt", no: "trøtt" },
  "hungry": { ru: "голодный", tr: "aç", nl: "hongerig", sv: "hungrig", pl: "głodny", vi: "đói", id: "lapar", fi: "nälkäinen", no: "sulten" },
  "thirsty": { ru: "жаждущий", tr: "susamış", nl: "dorstig", sv: "törstig", pl: "spragniony", vi: "khát", id: "haus", fi: "janoinen", no: "tørst" },
  "surprised": { ru: "удивлённый", tr: "şaşırmış", nl: "verrast", sv: "förvånad", pl: "zaskoczony", vi: "ngạc nhiên", id: "terkejut", fi: "yllättynyt", no: "overrasket" },
  "excited": { ru: "взволнованный", tr: "heyecanlı", nl: "opgewonden", sv: "upprymd", pl: "podekscytowany", vi: "phấn khích", id: "bersemangat", fi: "innostunut", no: "spent" },
  "bored": { ru: "скучающий", tr: "sıkılmış", nl: "verveeld", sv: "uttråkad", pl: "znudzony", vi: "chán", id: "bosan", fi: "tylsistynyt", no: "kjed" },
  "nervous": { ru: "нервный", tr: "gergin", nl: "nerveus", sv: "nervös", pl: "nerwowy", vi: "lo lắng", id: "gugup", fi: "hermostunut", no: "nervøs" },
  "proud": { ru: "гордый", tr: "gururlu", nl: "trots", sv: "stolt", pl: "dumny", vi: "tự hào", id: "bangga", fi: "ylpeä", no: "stolt" },
  "lonely": { ru: "одинокий", tr: "yalnız", nl: "eenzaam", sv: "ensam", pl: "samotny", vi: "cô đơn", id: "kesepian", fi: "yksinäinen", no: "ensom" },
  "jealous": { ru: "ревнивый", tr: "kıskanç", nl: "jaloers", sv: "svartsjuk", pl: "zazdrosny", vi: "ghen tị", id: "cemburu", fi: "mustasukkainen", no: "sjalu" },
  "calm": { ru: "спокойный", tr: "sakin", nl: "kalm", sv: "lugn", pl: "spokojny", vi: "bình tĩnh", id: "tenang", fi: "rauhallinen", no: "rolig" },
  "confident": { ru: "уверенный", tr: "kendinden emin", nl: "zelfverzekerd", sv: "självsäker", pl: "pewny siebie", vi: "tự tin", id: "percaya diri", fi: "itsevarma", no: "selvsikker" },
  "grateful": { ru: "благодарный", tr: "minnettar", nl: "dankbaar", sv: "tacksam", pl: "wdzięczny", vi: "biết ơn", id: "bersyukur", fi: "kiitollinen", no: "takknemlig" },
  "city": { ru: "город", tr: "şehir", nl: "stad", sv: "stad", pl: "miasto", vi: "thành phố", id: "kota", fi: "kaupunki", no: "by" },
  "country": { ru: "страна", tr: "ülke", nl: "land", sv: "land", pl: "kraj", vi: "quốc gia", id: "negara", fi: "maa", no: "land" },
  "school": { ru: "школа", tr: "okul", nl: "school", sv: "skola", pl: "szkoła", vi: "trường học", id: "sekolah", fi: "koulu", no: "skole" },
  "hospital": { ru: "больница", tr: "hastane", nl: "ziekenhuis", sv: "sjukhus", pl: "szpital", vi: "bệnh viện", id: "rumah sakit", fi: "sairaala", no: "sykehus" },
  "church": { ru: "церковь", tr: "kilise", nl: "kerk", sv: "kyrka", pl: "kościół", vi: "nhà thờ", id: "gereja", fi: "kirkko", no: "kirke" },
  "store": { ru: "магазин", tr: "mağaza", nl: "winkel", sv: "butik", pl: "sklep", vi: "cửa hàng", id: "toko", fi: "kauppa", no: "butikk" },
  "restaurant": { ru: "ресторан", tr: "restoran", nl: "restaurant", sv: "restaurang", pl: "restauracja", vi: "nhà hàng", id: "restoran", fi: "ravintola", no: "restaurant" },
  "park": { ru: "парк", tr: "park", nl: "park", sv: "park", pl: "park", vi: "công viên", id: "taman", fi: "puisto", no: "park" },
  "library": { ru: "библиотека", tr: "kütüphane", nl: "bibliotheek", sv: "bibliotek", pl: "biblioteka", vi: "thư viện", id: "perpustakaan", fi: "kirjasto", no: "bibliotek" },
  "museum": { ru: "музей", tr: "müze", nl: "museum", sv: "museum", pl: "muzeum", vi: "bảo tàng", id: "museum", fi: "museo", no: "museum" },
  "bank": { ru: "банк", tr: "banka", nl: "bank", sv: "bank", pl: "bank", vi: "ngân hàng", id: "bank", fi: "pankki", no: "bank" },
  "airport": { ru: "аэропорт", tr: "havalimanı", nl: "luchthaven", sv: "flygplats", pl: "lotnisko", vi: "sân bay", id: "bandara", fi: "lentokenttä", no: "flyplass" },
  "station": { ru: "станция", tr: "istasyon", nl: "station", sv: "station", pl: "stacja", vi: "ga", id: "stasiun", fi: "asema", no: "stasjon" },
  "market": { ru: "рынок", tr: "pazar", nl: "markt", sv: "marknad", pl: "rynek", vi: "chợ", id: "pasar", fi: "tori", no: "marked" },
  "hotel": { ru: "гостиница", tr: "otel", nl: "hotel", sv: "hotell", pl: "hotel", vi: "khách sạn", id: "hotel", fi: "hotelli", no: "hotell" },
  "beach": { ru: "пляж", tr: "plaj", nl: "strand", sv: "strand", pl: "plaża", vi: "bãi biển", id: "pantai", fi: "ranta", no: "strand" },
  "office": { ru: "офис", tr: "ofis", nl: "kantoor", sv: "kontor", pl: "biuro", vi: "văn phòng", id: "kantor", fi: "toimisto", no: "kontor" },
  "street": { ru: "улица", tr: "sokak", nl: "straat", sv: "gata", pl: "ulica", vi: "đường phố", id: "jalan", fi: "katu", no: "gate" },
  "book": { ru: "книга", tr: "kitap", nl: "boek", sv: "bok", pl: "książka", vi: "sách", id: "buku", fi: "kirja", no: "bok" },
  "pen": { ru: "ручка", tr: "kalem", nl: "pen", sv: "penna", pl: "długopis", vi: "bút", id: "pena", fi: "kynä", no: "penn" },
  "paper": { ru: "бумага", tr: "kâğıt", nl: "papier", sv: "papper", pl: "papier", vi: "giấy", id: "kertas", fi: "paperi", no: "papir" },
  "pencil": { ru: "карандаш", tr: "kurşun kalem", nl: "potlood", sv: "blyertspenna", pl: "ołówek", vi: "bút chì", id: "pensil", fi: "lyijykynä", no: "blyant" },
  "computer": { ru: "компьютер", tr: "bilgisayar", nl: "computer", sv: "dator", pl: "komputer", vi: "máy tính", id: "komputer", fi: "tietokone", no: "datamaskin" },
  "class": { ru: "класс", tr: "sınıf", nl: "klas", sv: "klass", pl: "klasa", vi: "lớp học", id: "kelas", fi: "luokka", no: "klasse" },
  "exam": { ru: "экзамен", tr: "sınav", nl: "examen", sv: "prov", pl: "egzamin", vi: "kỳ thi", id: "ujian", fi: "koe", no: "eksamen" },
  "homework": { ru: "домашнее задание", tr: "ödev", nl: "huiswerk", sv: "läxa", pl: "zadanie domowe", vi: "bài tập về nhà", id: "pekerjaan rumah", fi: "kotitehtävä", no: "lekser" },
  "question": { ru: "вопрос", tr: "soru", nl: "vraag", sv: "fråga", pl: "pytanie", vi: "câu hỏi", id: "pertanyaan", fi: "kysymys", no: "spørsmål" },
  "answer": { ru: "ответ", tr: "cevap", nl: "antwoord", sv: "svar", pl: "odpowiedź", vi: "câu trả lời", id: "jawaban", fi: "vastaus", no: "svar" },
  "money": { ru: "деньги", tr: "para", nl: "geld", sv: "pengar", pl: "pieniądze", vi: "tiền", id: "uang", fi: "raha", no: "penger" },
  "job": { ru: "работа", tr: "iş", nl: "baan", sv: "jobb", pl: "praca", vi: "công việc", id: "pekerjaan", fi: "työ", no: "jobb" },
  "meeting": { ru: "собрание", tr: "toplantı", nl: "vergadering", sv: "möte", pl: "spotkanie", vi: "cuộc họp", id: "rapat", fi: "kokous", no: "møte" },
  "idea": { ru: "идея", tr: "fikir", nl: "idee", sv: "idé", pl: "pomysł", vi: "ý tưởng", id: "ide", fi: "idea", no: "idé" },
  "problem": { ru: "проблема", tr: "sorun", nl: "probleem", sv: "problem", pl: "problem", vi: "vấn đề", id: "masalah", fi: "ongelma", no: "problem" },
  "language": { ru: "язык", tr: "dil", nl: "taal", sv: "språk", pl: "język", vi: "ngôn ngữ", id: "bahasa", fi: "kieli", no: "språk" },
  "word": { ru: "слово", tr: "kelime", nl: "woord", sv: "ord", pl: "słowo", vi: "từ", id: "kata", fi: "sana", no: "ord" },
  "letter": { ru: "письмо", tr: "mektup", nl: "brief", sv: "brev", pl: "list", vi: "thư", id: "surat", fi: "kirje", no: "brev" },
  "number": { ru: "номер", tr: "numara", nl: "nummer", sv: "nummer", pl: "numer", vi: "số", id: "nomor", fi: "numero", no: "nummer" },
  "name": { ru: "имя", tr: "isim", nl: "naam", sv: "namn", pl: "imię", vi: "tên", id: "nama", fi: "nimi", no: "navn" },
  "sick": { ru: "больной", tr: "hasta", nl: "ziek", sv: "sjuk", pl: "chory", vi: "ốm", id: "sakit", fi: "sairas", no: "syk" },
  "healthy": { ru: "здоровый", tr: "sağlıklı", nl: "gezond", sv: "frisk", pl: "zdrowy", vi: "khỏe mạnh", id: "sehat", fi: "terve", no: "frisk" },
  "medicine": { ru: "лекарство", tr: "ilaç", nl: "medicijn", sv: "medicin", pl: "lekarstwo", vi: "thuốc", id: "obat", fi: "lääke", no: "medisin" },
  "pain": { ru: "боль", tr: "ağrı", nl: "pijn", sv: "smärta", pl: "ból", vi: "đau", id: "sakit", fi: "kipu", no: "smerte" },
  "fever": { ru: "лихорадка", tr: "ateş", nl: "koorts", sv: "feber", pl: "gorączka", vi: "sốt", id: "demam", fi: "kuume", no: "feber" },
  "cough": { ru: "кашель", tr: "öksürük", nl: "hoest", sv: "hosta", pl: "kaszel", vi: "ho", id: "batuk", fi: "yskä", no: "hoste" },
  "cold (illness)": { ru: "простуда", tr: "soğuk algınlığı", nl: "verkoudheid", sv: "förkylning", pl: "przeziębienie", vi: "cảm lạnh", id: "pilek", fi: "vilustuminen", no: "forkjølelse" },
  "headache": { ru: "головная боль", tr: "baş ağrısı", nl: "hoofdpijn", sv: "huvudvärk", pl: "ból głowy", vi: "đau đầu", id: "sakit kepala", fi: "päänsärky", no: "hodepine" },
  "exercise": { ru: "упражнение", tr: "egzersiz", nl: "oefening", sv: "övning", pl: "ćwiczenie", vi: "tập thể dục", id: "olahraga", fi: "harjoitus", no: "trening" },
  "rest": { ru: "отдых", tr: "dinlenme", nl: "rust", sv: "vila", pl: "odpoczynek", vi: "nghỉ ngơi", id: "istirahat", fi: "lepo", no: "hvile" },
  "breath": { ru: "дыхание", tr: "nefes", nl: "adem", sv: "andning", pl: "oddech", vi: "hơi thở", id: "napas", fi: "hengitys", no: "pust" },
  "life": { ru: "жизнь", tr: "hayat", nl: "leven", sv: "liv", pl: "życie", vi: "cuộc sống", id: "hidup", fi: "elämä", no: "liv" },
  "death": { ru: "смерть", tr: "ölüm", nl: "dood", sv: "död", pl: "śmierć", vi: "cái chết", id: "kematian", fi: "kuolema", no: "død" },
  "alive": { ru: "живой", tr: "canlı", nl: "levend", sv: "levande", pl: "żywy", vi: "sống", id: "hidup", fi: "elossa", no: "levende" },
  "i don't understand": { ru: "я не понимаю", tr: "anlamıyorum", nl: "ik begrijp het niet", sv: "jag förstår inte", pl: "nie rozumiem", vi: "tôi không hiểu", id: "saya tidak mengerti", fi: "en ymmärrä", no: "jeg forstår ikke" },
  "i don't know": { ru: "я не знаю", tr: "bilmiyorum", nl: "ik weet het niet", sv: "jag vet inte", pl: "nie wiem", vi: "tôi không biết", id: "saya tidak tahu", fi: "en tiedä", no: "jeg vet ikke" },
  "i need help": { ru: "мне нужна помощь", tr: "yardıma ihtiyacım var", nl: "ik heb hulp nodig", sv: "jag behöver hjälp", pl: "potrzebuję pomocy", vi: "tôi cần giúp đỡ", id: "saya butuh bantuan", fi: "tarvitsen apua", no: "jeg trenger hjelp" },
  "how much?": { ru: "сколько?", tr: "ne kadar?", nl: "hoeveel?", sv: "hur mycket?", pl: "ile?", vi: "bao nhiêu?", id: "berapa?", fi: "kuinka paljon?", no: "hvor mye?" },
  "i like it": { ru: "мне нравится", tr: "beğendim", nl: "ik vind het leuk", sv: "jag gillar det", pl: "podoba mi się", vi: "tôi thích nó", id: "saya suka", fi: "pidän siitä", no: "jeg liker det" },
  "i'm lost": { ru: "я заблудился", tr: "kayboldum", nl: "ik ben verdwaald", sv: "jag har gått vilse", pl: "zgubiłem się", vi: "tôi bị lạc", id: "saya tersesat", fi: "olen eksyksissä", no: "jeg har gått meg bort" },
  "wait a moment": { ru: "подождите минутку", tr: "bir dakika", nl: "wacht even", sv: "vänta lite", pl: "chwileczkę", vi: "đợi một chút", id: "tunggu sebentar", fi: "odota hetki", no: "vent litt" },
  "let's go": { ru: "пойдём", tr: "hadi gidelim", nl: "laten we gaan", sv: "låt oss gå", pl: "chodźmy", vi: "đi thôi", id: "ayo pergi", fi: "mennään", no: "la oss gå" },
  "of course": { ru: "конечно", tr: "tabii ki", nl: "natuurlijk", sv: "självklart", pl: "oczywiście", vi: "tất nhiên", id: "tentu saja", fi: "tietenkin", no: "selvfølgelig" },
  "no problem": { ru: "нет проблем", tr: "sorun değil", nl: "geen probleem", sv: "inga problem", pl: "nie ma problemu", vi: "không sao", id: "tidak masalah", fi: "ei ongelmaa", no: "ikke noe problem" },
  "congratulations": { ru: "поздравляю", tr: "tebrikler", nl: "gefeliciteerd", sv: "grattis", pl: "gratulacje", vi: "xin chúc mừng", id: "selamat", fi: "onnittelut", no: "gratulerer" },
  "happy birthday": { ru: "с днём рождения", tr: "doğum günün kutlu olsun", nl: "gefeliciteerd met je verjaardag", sv: "grattis på födelsedagen", pl: "wszystkiego najlepszego", vi: "chúc mừng sinh nhật", id: "selamat ulang tahun", fi: "hyvää syntymäpäivää", no: "gratulerer med dagen" },
  "i'm sorry": { ru: "мне жаль", tr: "özür dilerim", nl: "het spijt me", sv: "jag är ledsen", pl: "przepraszam", vi: "tôi xin lỗi", id: "saya minta maaf", fi: "olen pahoillani", no: "jeg beklager" },
  "cheers": { ru: "за здоровье", tr: "şerefe", nl: "proost", sv: "skål", pl: "na zdrowie", vi: "chúc sức khỏe", id: "bersulang", fi: "kippis", no: "skål" },
  "good luck": { ru: "удачи", tr: "iyi şanslar", nl: "veel succes", sv: "lycka till", pl: "powodzenia", vi: "chúc may mắn", id: "semoga berhasil", fi: "onnea", no: "lykke til" },
  "i agree": { ru: "я согласен", tr: "katılıyorum", nl: "ik ben het eens", sv: "jag håller med", pl: "zgadzam się", vi: "tôi đồng ý", id: "saya setuju", fi: "olen samaa mieltä", no: "jeg er enig" },
  "maybe": { ru: "может быть", tr: "belki", nl: "misschien", sv: "kanske", pl: "może", vi: "có lẽ", id: "mungkin", fi: "ehkä", no: "kanskje" },
  "very": { ru: "очень", tr: "çok", nl: "zeer", sv: "mycket", pl: "bardzo", vi: "rất", id: "sangat", fi: "hyvin", no: "veldig" },
  "also": { ru: "тоже", tr: "da", nl: "ook", sv: "också", pl: "także", vi: "cũng", id: "juga", fi: "myös", no: "også" },
  "already": { ru: "уже", tr: "zaten", nl: "al", sv: "redan", pl: "już", vi: "đã", id: "sudah", fi: "jo", no: "allerede" },
  "phone": { ru: "телефон", tr: "telefon", nl: "telefoon", sv: "telefon", pl: "telefon", vi: "điện thoại", id: "telepon", fi: "puhelin", no: "telefon" },
  "camera": { ru: "камера", tr: "kamera", nl: "camera", sv: "kamera", pl: "aparat", vi: "máy ảnh", id: "kamera", fi: "kamera", no: "kamera" },
  "television": { ru: "телевизор", tr: "televizyon", nl: "televisie", sv: "television", pl: "telewizor", vi: "ti vi", id: "televisi", fi: "televisio", no: "fjernsyn" },
  "bottle": { ru: "бутылка", tr: "şişe", nl: "fles", sv: "flaska", pl: "butelka", vi: "chai", id: "botol", fi: "pullo", no: "flaske" },
  "cup": { ru: "чашка", tr: "fincan", nl: "kopje", sv: "kopp", pl: "filiżanka", vi: "cốc", id: "cangkir", fi: "kuppi", no: "kopp" },
  "plate": { ru: "тарелка", tr: "tabak", nl: "bord", sv: "tallrik", pl: "talerz", vi: "đĩa", id: "piring", fi: "lautanen", no: "tallerken" },
  "knife": { ru: "нож", tr: "bıçak", nl: "mes", sv: "kniv", pl: "nóż", vi: "dao", id: "pisau", fi: "veitsi", no: "kniv" },
  "fork": { ru: "вилка", tr: "çatal", nl: "vork", sv: "gaffel", pl: "widelec", vi: "nĩa", id: "garpu", fi: "haarukka", no: "gaffel" },
  "spoon": { ru: "ложка", tr: "kaşık", nl: "lepel", sv: "sked", pl: "łyżka", vi: "thìa", id: "sendok", fi: "lusikka", no: "skje" },
  "box": { ru: "коробка", tr: "kutu", nl: "doos", sv: "låda", pl: "pudełko", vi: "hộp", id: "kotak", fi: "laatikko", no: "eske" },
  "scissors": { ru: "ножницы", tr: "makas", nl: "schaar", sv: "sax", pl: "nożyczki", vi: "kéo", id: "gunting", fi: "sakset", no: "saks" },
  "needle": { ru: "игла", tr: "iğne", nl: "naald", sv: "nål", pl: "igła", vi: "kim", id: "jarum", fi: "neula", no: "nål" },
  "rope": { ru: "верёвка", tr: "ip", nl: "touw", sv: "rep", pl: "lina", vi: "dây thừng", id: "tali", fi: "köysi", no: "tau" },
  "candle": { ru: "свеча", tr: "mum", nl: "kaars", sv: "ljus", pl: "świeca", vi: "nến", id: "lilin", fi: "kynttilä", no: "stearinlys" },
  "soap": { ru: "мыло", tr: "sabun", nl: "zeep", sv: "tvål", pl: "mydło", vi: "xà phòng", id: "sabun", fi: "saippua", no: "såpe" },
  "towel": { ru: "полотенце", tr: "havlu", nl: "handdoek", sv: "handduk", pl: "ręcznik", vi: "khăn tắm", id: "handuk", fi: "pyyhe", no: "håndkle" },
  "brush": { ru: "щётка", tr: "fırça", nl: "borstel", sv: "borste", pl: "szczotka", vi: "bàn chải", id: "sikat", fi: "harja", no: "børste" },
  "gift": { ru: "подарок", tr: "hediye", nl: "cadeau", sv: "present", pl: "prezent", vi: "quà tặng", id: "hadiah", fi: "lahja", no: "gave" },
  "toy": { ru: "игрушка", tr: "oyuncak", nl: "speelgoed", sv: "leksak", pl: "zabawka", vi: "đồ chơi", id: "mainan", fi: "lelu", no: "leke" },
  "picture": { ru: "картинка", tr: "resim", nl: "foto", sv: "bild", pl: "zdjęcie", vi: "hình ảnh", id: "gambar", fi: "kuva", no: "bilde" },
  "coin": { ru: "монета", tr: "madeni para", nl: "munt", sv: "mynt", pl: "moneta", vi: "đồng xu", id: "koin", fi: "kolikko", no: "mynt" },
  "ring": { ru: "кольцо", tr: "yüzük", nl: "ring", sv: "ring", pl: "pierścionek", vi: "nhẫn", id: "cincin", fi: "sormus", no: "ring" },
  "watch": { ru: "часы", tr: "kol saati", nl: "horloge", sv: "klocka", pl: "zegarek", vi: "đồng hồ đeo tay", id: "jam tangan", fi: "rannekello", no: "klokke" },
  "glasses": { ru: "очки", tr: "gözlük", nl: "bril", sv: "glasögon", pl: "okulary", vi: "kính", id: "kacamata", fi: "silmälasit", no: "briller" },
  "wheel": { ru: "колесо", tr: "tekerlek", nl: "wiel", sv: "hjul", pl: "koło", vi: "bánh xe", id: "roda", fi: "pyörä", no: "hjul" },
  "flag": { ru: "флаг", tr: "bayrak", nl: "vlag", sv: "flagga", pl: "flaga", vi: "cờ", id: "bendera", fi: "lippu", no: "flagg" },
  "ball": { ru: "мяч", tr: "top", nl: "bal", sv: "boll", pl: "piłka", vi: "quả bóng", id: "bola", fi: "pallo", no: "ball" },
  "music": { ru: "музыка", tr: "müzik", nl: "muziek", sv: "musik", pl: "muzyka", vi: "âm nhạc", id: "musik", fi: "musiikki", no: "musikk" },
  "game": { ru: "игра", tr: "oyun", nl: "spel", sv: "spel", pl: "gra", vi: "trò chơi", id: "permainan", fi: "peli", no: "spill" },
  "movie": { ru: "фильм", tr: "film", nl: "film", sv: "film", pl: "film", vi: "phim", id: "film", fi: "elokuva", no: "film" },
  "song": { ru: "песня", tr: "şarkı", nl: "lied", sv: "sång", pl: "piosenka", vi: "bài hát", id: "lagu", fi: "laulu", no: "sang" },
  "story": { ru: "история", tr: "hikâye", nl: "verhaal", sv: "berättelse", pl: "historia", vi: "câu chuyện", id: "cerita", fi: "tarina", no: "historie" },
  "news": { ru: "новости", tr: "haber", nl: "nieuws", sv: "nyheter", pl: "wiadomości", vi: "tin tức", id: "berita", fi: "uutiset", no: "nyheter" },
  "dream": { ru: "мечта", tr: "rüya", nl: "droom", sv: "dröm", pl: "sen", vi: "giấc mơ", id: "mimpi", fi: "unelma", no: "drøm" },
  "truth": { ru: "правда", tr: "gerçek", nl: "waarheid", sv: "sanning", pl: "prawda", vi: "sự thật", id: "kebenaran", fi: "totuus", no: "sannhet" }
};

CATEGORIES.forEach(function(cat) {
  cat.words.forEach(function(word) {
    var extra = BATCH1[word.en.toLowerCase()];
    if (extra) Object.assign(word, extra);
  });
});

// Transliterations for Russian (Cyrillic → romanized)
var BATCH1_TR = {
  "hello": { ru: "privet" },
  "goodbye": { ru: "do svidaniya" },
  "please": { ru: "pozhaluysta" },
  "thank you": { ru: "spasibo" },
  "yes": { ru: "da" },
  "no": { ru: "net" },
  "sorry": { ru: "izvinite" },
  "excuse me": { ru: "prostite" },
  "good morning": { ru: "dobroye utro" },
  "good night": { ru: "spokoynoy nochi" },
  "how are you": { ru: "kak dela" },
  "nice to meet you": { ru: "priyatno poznakomitsya" },
  "see you later": { ru: "uvidimsya pozzhe" },
  "welcome": { ru: "dobro pozhalovat" },
  "i": { ru: "ya" },
  "you": { ru: "ty" },
  "he": { ru: "on" },
  "she": { ru: "ona" },
  "we": { ru: "my" },
  "they": { ru: "oni" },
  "this": { ru: "eto" },
  "that": { ru: "to" },
  "what": { ru: "chto" },
  "where": { ru: "gde" },
  "when": { ru: "kogda" },
  "why": { ru: "pochemu" },
  "how": { ru: "kak" },
  "who": { ru: "kto" },
  "zero": { ru: "nol" },
  "one": { ru: "odin" },
  "two": { ru: "dva" },
  "three": { ru: "tri" },
  "four": { ru: "chetyre" },
  "five": { ru: "pyat" },
  "six": { ru: "shest" },
  "seven": { ru: "sem" },
  "eight": { ru: "vosem" },
  "nine": { ru: "devyat" },
  "ten": { ru: "desyat" },
  "eleven": { ru: "odinnadtsat" },
  "twelve": { ru: "dvenadtsat" },
  "twenty": { ru: "dvadtsat" },
  "thirty": { ru: "tridtsat" },
  "forty": { ru: "sorok" },
  "fifty": { ru: "pyatdesyat" },
  "hundred": { ru: "sto" },
  "thousand": { ru: "tysyacha" },
  "million": { ru: "million" },
  "first": { ru: "pervyy" },
  "second": { ru: "vtoroy" },
  "third": { ru: "tretiy" },
  "half": { ru: "polovina" },
  "pair": { ru: "para" },
  "red": { ru: "krasnyy" },
  "blue": { ru: "siniy" },
  "green": { ru: "zelyonyy" },
  "yellow": { ru: "zholtyy" },
  "orange": { ru: "oranzhevyy" },
  "purple": { ru: "fioletovyy" },
  "pink": { ru: "rozovyy" },
  "black": { ru: "chyornyy" },
  "white": { ru: "belyy" },
  "brown": { ru: "korichnevyy" },
  "gray": { ru: "seryy" },
  "gold": { ru: "zolotoy" },
  "silver": { ru: "serebryanyy" },
  "light": { ru: "svetlyy" },
  "dark": { ru: "tyomnyy" },
  "dog": { ru: "sobaka" },
  "cat": { ru: "koshka" },
  "bird": { ru: "ptitsa" },
  "fish": { ru: "ryba" },
  "horse": { ru: "loshad" },
  "cow": { ru: "korova" },
  "pig": { ru: "svinya" },
  "sheep": { ru: "ovtsa" },
  "chicken": { ru: "kuritsa" },
  "duck": { ru: "utka" },
  "rabbit": { ru: "krolik" },
  "mouse": { ru: "mysh" },
  "elephant": { ru: "slon" },
  "lion": { ru: "lev" },
  "tiger": { ru: "tigr" },
  "bear": { ru: "medved" },
  "monkey": { ru: "obezyana" },
  "snake": { ru: "zmeya" },
  "frog": { ru: "lyagushka" },
  "turtle": { ru: "cherepakha" },
  "whale": { ru: "kit" },
  "dolphin": { ru: "delfin" },
  "butterfly": { ru: "babochka" },
  "bee": { ru: "pchela" },
  "ant": { ru: "muravey" },
  "spider": { ru: "pauk" },
  "wolf": { ru: "volk" },
  "fox": { ru: "lisa" },
  "deer": { ru: "olen" },
  "eagle": { ru: "oryol" },
  "water": { ru: "voda" },
  "bread": { ru: "khleb" },
  "rice": { ru: "ris" },
  "meat": { ru: "myaso" },
  "egg": { ru: "yaytso" },
  "milk": { ru: "moloko" },
  "cheese": { ru: "syr" },
  "butter": { ru: "maslo" },
  "sugar": { ru: "sakhar" },
  "salt": { ru: "sol" },
  "apple": { ru: "yabloko" },
  "banana": { ru: "banan" },
  "orange (fruit)": { ru: "apelsin" },
  "grape": { ru: "vinograd" },
  "strawberry": { ru: "klubnika" },
  "tomato": { ru: "pomidor" },
  "potato": { ru: "kartofel" },
  "onion": { ru: "luk" },
  "carrot": { ru: "morkov" },
  "pepper": { ru: "perets" },
  "coffee": { ru: "kofe" },
  "tea": { ru: "chay" },
  "juice": { ru: "sok" },
  "soup": { ru: "sup" },
  "salad": { ru: "salat" },
  "cake": { ru: "tort" },
  "chocolate": { ru: "shokolad" },
  "ice cream": { ru: "morozhenoye" },
  "oil": { ru: "maslo" },
  "flour": { ru: "muka" },
  "noodle": { ru: "lapsha" },
  "bean": { ru: "fasol" },
  "mushroom": { ru: "grib" },
  "garlic": { ru: "chesnok" },
  "lemon": { ru: "limon" },
  "mother": { ru: "mat" },
  "father": { ru: "otets" },
  "sister": { ru: "sestra" },
  "brother": { ru: "brat" },
  "son": { ru: "syn" },
  "daughter": { ru: "doch" },
  "grandmother": { ru: "babushka" },
  "grandfather": { ru: "dedushka" },
  "baby": { ru: "rebyonok" },
  "child": { ru: "rebyonok" },
  "husband": { ru: "muzh" },
  "wife": { ru: "zhena" },
  "uncle": { ru: "dyadya" },
  "aunt": { ru: "tyotya" },
  "cousin": { ru: "dvoyurodnyy brat" },
  "friend": { ru: "drug" },
  "neighbor": { ru: "sosed" },
  "family": { ru: "semya" },
  "person": { ru: "chelovek" },
  "man": { ru: "muzhchina" },
  "woman": { ru: "zhenshchina" },
  "head": { ru: "golova" },
  "hair": { ru: "volosy" },
  "face": { ru: "litso" },
  "eye": { ru: "glaz" },
  "ear": { ru: "ukho" },
  "nose": { ru: "nos" },
  "mouth": { ru: "rot" },
  "tooth": { ru: "zub" },
  "tongue": { ru: "yazyk" },
  "neck": { ru: "sheya" },
  "shoulder": { ru: "plecho" },
  "arm": { ru: "ruka" },
  "hand": { ru: "ruka" },
  "finger": { ru: "palets" },
  "chest": { ru: "grud" },
  "back": { ru: "spina" },
  "stomach": { ru: "zhivot" },
  "leg": { ru: "noga" },
  "knee": { ru: "koleno" },
  "foot": { ru: "stopa" },
  "heart": { ru: "serdtse" },
  "blood": { ru: "krov" },
  "bone": { ru: "kost" },
  "skin": { ru: "kozha" },
  "shirt": { ru: "rubashka" },
  "pants": { ru: "bryuki" },
  "dress": { ru: "platye" },
  "skirt": { ru: "yubka" },
  "jacket": { ru: "kurtka" },
  "coat": { ru: "palto" },
  "shoes": { ru: "obuv" },
  "boots": { ru: "sapogi" },
  "hat": { ru: "shlyapa" },
  "socks": { ru: "noski" },
  "gloves": { ru: "perchatki" },
  "scarf": { ru: "sharf" },
  "belt": { ru: "remen" },
  "bag": { ru: "sumka" },
  "umbrella": { ru: "zont" },
  "today": { ru: "segodnya" },
  "tomorrow": { ru: "zavtra" },
  "yesterday": { ru: "vchera" },
  "morning": { ru: "utro" },
  "afternoon": { ru: "den" },
  "evening": { ru: "vecher" },
  "night": { ru: "noch" },
  "monday": { ru: "ponedelnik" },
  "tuesday": { ru: "vtornik" },
  "wednesday": { ru: "sreda" },
  "thursday": { ru: "chetverg" },
  "friday": { ru: "pyatnitsa" },
  "saturday": { ru: "subbota" },
  "sunday": { ru: "voskresenye" },
  "january": { ru: "yanvar" },
  "february": { ru: "fevral" },
  "march": { ru: "mart" },
  "april": { ru: "aprel" },
  "may": { ru: "may" },
  "june": { ru: "iyun" },
  "year": { ru: "god" },
  "month": { ru: "mesyats" },
  "week": { ru: "nedelya" },
  "day": { ru: "den" },
  "hour": { ru: "chas" },
  "minute": { ru: "minuta" },
  "now": { ru: "seychas" },
  "always": { ru: "vsegda" },
  "never": { ru: "nikogda" },
  "sun": { ru: "solntse" },
  "moon": { ru: "luna" },
  "star": { ru: "zvezda" },
  "sky": { ru: "nebo" },
  "cloud": { ru: "oblako" },
  "rain": { ru: "dozhd" },
  "snow": { ru: "sneg" },
  "wind": { ru: "veter" },
  "storm": { ru: "burya" },
  "hot": { ru: "zharko" },
  "cold": { ru: "kholodno" },
  "tree": { ru: "derevo" },
  "flower": { ru: "tsvetok" },
  "grass": { ru: "trava" },
  "mountain": { ru: "gora" },
  "river": { ru: "reka" },
  "sea": { ru: "more" },
  "lake": { ru: "ozero" },
  "forest": { ru: "les" },
  "island": { ru: "ostrov" },
  "earth": { ru: "zemlya" },
  "fire": { ru: "ogon" },
  "ice": { ru: "lyod" },
  "stone": { ru: "kamen" },
  "sand": { ru: "pesok" },
  "house": { ru: "dom" },
  "door": { ru: "dver" },
  "window": { ru: "okno" },
  "room": { ru: "komnata" },
  "kitchen": { ru: "kukhnya" },
  "bathroom": { ru: "vannaya" },
  "bedroom": { ru: "spalnya" },
  "table": { ru: "stol" },
  "chair": { ru: "stul" },
  "bed": { ru: "krovat" },
  "mirror": { ru: "zerkalo" },
  "lamp": { ru: "lampa" },
  "stairs": { ru: "lestnitsa" },
  "wall": { ru: "stena" },
  "floor": { ru: "pol" },
  "roof": { ru: "krysha" },
  "garden": { ru: "sad" },
  "key": { ru: "klyuch" },
  "clock": { ru: "chasy" },
  "telephone": { ru: "telefon" },
  "car": { ru: "mashina" },
  "bus": { ru: "avtobus" },
  "train": { ru: "poyezd" },
  "airplane": { ru: "samolyot" },
  "bicycle": { ru: "velosiped" },
  "boat": { ru: "lodka" },
  "ship": { ru: "korabl" },
  "taxi": { ru: "taksi" },
  "motorcycle": { ru: "mototsikl" },
  "truck": { ru: "gruzovik" },
  "subway": { ru: "metro" },
  "road": { ru: "doroga" },
  "bridge": { ru: "most" },
  "ticket": { ru: "bilet" },
  "map": { ru: "karta" },
  "teacher": { ru: "uchitel" },
  "doctor": { ru: "vrach" },
  "nurse": { ru: "medsestra" },
  "engineer": { ru: "inzhener" },
  "student": { ru: "student" },
  "police": { ru: "politsiya" },
  "farmer": { ru: "fermer" },
  "cook": { ru: "povar" },
  "driver": { ru: "voditel" },
  "lawyer": { ru: "advokat" },
  "artist": { ru: "khudozhnik" },
  "musician": { ru: "muzykant" },
  "writer": { ru: "pisatel" },
  "pilot": { ru: "pilot" },
  "soldier": { ru: "soldat" },
  "to be": { ru: "byt" },
  "to have": { ru: "imet" },
  "to do": { ru: "delat" },
  "to go": { ru: "idti" },
  "to come": { ru: "prikhodit" },
  "to say": { ru: "govorit" },
  "to see": { ru: "videt" },
  "to know": { ru: "znat" },
  "to think": { ru: "dumat" },
  "to want": { ru: "khotet" },
  "to eat": { ru: "yest" },
  "to drink": { ru: "pit" },
  "to sleep": { ru: "spat" },
  "to walk": { ru: "khodit" },
  "to run": { ru: "bezhat" },
  "to read": { ru: "chitat" },
  "to write": { ru: "pisat" },
  "to speak": { ru: "govorit" },
  "to listen": { ru: "slushat" },
  "to understand": { ru: "ponimat" },
  "to give": { ru: "davat" },
  "to take": { ru: "brat" },
  "to buy": { ru: "pokupat" },
  "to sell": { ru: "prodavat" },
  "to open": { ru: "otkryvat" },
  "to close": { ru: "zakryvat" },
  "to sit": { ru: "sidet" },
  "to stand": { ru: "stoyat" },
  "to love": { ru: "lyubit" },
  "to like": { ru: "nravitsya" },
  "to help": { ru: "pomogat" },
  "to learn": { ru: "uchitsya" },
  "to teach": { ru: "uchit" },
  "to work": { ru: "rabotat" },
  "to play": { ru: "igrat" },
  "to sing": { ru: "pet" },
  "to dance": { ru: "tantsevat" },
  "to swim": { ru: "plavat" },
  "to fly": { ru: "letat" },
  "to wait": { ru: "zhdat" },
  "to find": { ru: "nakhodit" },
  "to make": { ru: "delat" },
  "to put": { ru: "klast" },
  "to use": { ru: "ispolzovat" },
  "to try": { ru: "probovat" },
  "to begin": { ru: "nachinat" },
  "to finish": { ru: "zakanchivat" },
  "to send": { ru: "otpravlyat" },
  "to receive": { ru: "poluchat" },
  "to remember": { ru: "pomnit" },
  "big": { ru: "bolshoy" },
  "small": { ru: "malenkiy" },
  "long": { ru: "dlinnyy" },
  "short": { ru: "korotkiy" },
  "tall": { ru: "vysokiy" },
  "new": { ru: "novyy" },
  "old": { ru: "staryy" },
  "good": { ru: "khoroshiy" },
  "bad": { ru: "plokhoy" },
  "beautiful": { ru: "krasivyy" },
  "ugly": { ru: "nekrasivyy" },
  "fast": { ru: "bystryy" },
  "slow": { ru: "medlennyy" },
  "heavy": { ru: "tyazholyy" },
  "easy": { ru: "lyogkiy" },
  "difficult": { ru: "trudnyy" },
  "clean": { ru: "chistyy" },
  "dirty": { ru: "gryaznyy" },
  "rich": { ru: "bogatyy" },
  "poor": { ru: "bednyy" },
  "full": { ru: "polnyy" },
  "empty": { ru: "pustoy" },
  "strong": { ru: "silnyy" },
  "weak": { ru: "slabyy" },
  "young": { ru: "molodoy" },
  "right": { ru: "pravilnyy" },
  "wrong": { ru: "nepravilnyy" },
  "happy": { ru: "schastlivyy" },
  "sad": { ru: "grustnyy" },
  "important": { ru: "vazhnyy" },
  "angry": { ru: "zloy" },
  "scared": { ru: "ispugannyy" },
  "tired": { ru: "ustalyy" },
  "hungry": { ru: "golodnyy" },
  "thirsty": { ru: "zhazhdushchiy" },
  "surprised": { ru: "udivlyonnyy" },
  "excited": { ru: "vzvolnovannyy" },
  "bored": { ru: "skuchayushchiy" },
  "nervous": { ru: "nervnyy" },
  "proud": { ru: "gordyy" },
  "lonely": { ru: "odinokiy" },
  "jealous": { ru: "revnivyy" },
  "calm": { ru: "spokoynyy" },
  "confident": { ru: "uverennyy" },
  "grateful": { ru: "blagodarnyy" },
  "city": { ru: "gorod" },
  "country": { ru: "strana" },
  "school": { ru: "shkola" },
  "hospital": { ru: "bolnitsa" },
  "church": { ru: "tserkov" },
  "store": { ru: "magazin" },
  "restaurant": { ru: "restoran" },
  "park": { ru: "park" },
  "library": { ru: "biblioteka" },
  "museum": { ru: "muzey" },
  "bank": { ru: "bank" },
  "airport": { ru: "aeroport" },
  "station": { ru: "stantsiya" },
  "market": { ru: "rynok" },
  "hotel": { ru: "gostinitsa" },
  "beach": { ru: "plyazh" },
  "office": { ru: "ofis" },
  "street": { ru: "ulitsa" },
  "book": { ru: "kniga" },
  "pen": { ru: "ruchka" },
  "paper": { ru: "bumaga" },
  "pencil": { ru: "karandash" },
  "computer": { ru: "kompyuter" },
  "class": { ru: "klass" },
  "exam": { ru: "ekzamen" },
  "homework": { ru: "domashneye zadaniye" },
  "question": { ru: "vopros" },
  "answer": { ru: "otvet" },
  "money": { ru: "dengi" },
  "job": { ru: "rabota" },
  "meeting": { ru: "sobraniye" },
  "idea": { ru: "ideya" },
  "problem": { ru: "problema" },
  "language": { ru: "yazyk" },
  "word": { ru: "slovo" },
  "letter": { ru: "pismo" },
  "number": { ru: "nomer" },
  "name": { ru: "imya" },
  "sick": { ru: "bolnoy" },
  "healthy": { ru: "zdorovyy" },
  "medicine": { ru: "lekarstvo" },
  "pain": { ru: "bol" },
  "fever": { ru: "likhoradka" },
  "cough": { ru: "kashel" },
  "cold (illness)": { ru: "prostuda" },
  "headache": { ru: "golovnaya bol" },
  "exercise": { ru: "uprazhneniye" },
  "rest": { ru: "otdykh" },
  "breath": { ru: "dykhaniye" },
  "life": { ru: "zhizn" },
  "death": { ru: "smert" },
  "alive": { ru: "zhivoy" },
  "i don't understand": { ru: "ya ne ponimayu" },
  "i don't know": { ru: "ya ne znayu" },
  "i need help": { ru: "mne nuzhna pomoshch" },
  "how much?": { ru: "skolko?" },
  "i like it": { ru: "mne nravitsya" },
  "i'm lost": { ru: "ya zabludilsya" },
  "wait a moment": { ru: "podozhdite minutku" },
  "let's go": { ru: "poydyom" },
  "of course": { ru: "konechno" },
  "no problem": { ru: "net problem" },
  "congratulations": { ru: "pozdravlyayu" },
  "happy birthday": { ru: "s dnyom rozhdeniya" },
  "i'm sorry": { ru: "mne zhal" },
  "cheers": { ru: "za zdorovye" },
  "good luck": { ru: "udachi" },
  "i agree": { ru: "ya soglasen" },
  "maybe": { ru: "mozhet byt" },
  "very": { ru: "ochen" },
  "also": { ru: "tozhe" },
  "already": { ru: "uzhe" },
  "phone": { ru: "telefon" },
  "camera": { ru: "kamera" },
  "television": { ru: "televizor" },
  "bottle": { ru: "butylka" },
  "cup": { ru: "chashka" },
  "plate": { ru: "tarelka" },
  "knife": { ru: "nozh" },
  "fork": { ru: "vilka" },
  "spoon": { ru: "lozhka" },
  "box": { ru: "korobka" },
  "scissors": { ru: "nozhnitsy" },
  "needle": { ru: "igla" },
  "rope": { ru: "veryovka" },
  "candle": { ru: "svecha" },
  "soap": { ru: "mylo" },
  "towel": { ru: "polotentse" },
  "brush": { ru: "shchyotka" },
  "gift": { ru: "podarok" },
  "toy": { ru: "igrushka" },
  "picture": { ru: "kartinka" },
  "coin": { ru: "moneta" },
  "ring": { ru: "koltso" },
  "watch": { ru: "chasy" },
  "glasses": { ru: "ochki" },
  "wheel": { ru: "koleso" },
  "flag": { ru: "flag" },
  "ball": { ru: "myach" },
  "music": { ru: "muzyka" },
  "game": { ru: "igra" },
  "movie": { ru: "film" },
  "song": { ru: "pesnya" },
  "story": { ru: "istoriya" },
  "news": { ru: "novosti" },
  "dream": { ru: "mechta" },
  "truth": { ru: "pravda" }
};

for (var word in BATCH1_TR) {
  if (!TRANSLIT[word]) TRANSLIT[word] = {};
  Object.assign(TRANSLIT[word], BATCH1_TR[word]);
}
