// Romanized transliterations for non-Latin script languages
// ja = Japanese (Romaji), ko = Korean (Revised Romanization), zh = Chinese (Pinyin), ar = Arabic
const TRANSLIT = {
  // ── Greetings & Basics ──
  "hello": { ja: "konnichiwa", ko: "annyeonghaseyo", zh: "nǐ hǎo", ar: "marhaba" },
  "goodbye": { ja: "sayōnara", ko: "annyeonghi gaseyo", zh: "zàijiàn", ar: "maʿa as-salāma" },
  "please": { ja: "onegaishimasu", ko: "jebal", zh: "qǐng", ar: "min faḍlak" },
  "thank you": { ja: "arigatō", ko: "gamsahamnida", zh: "xièxie", ar: "shukran" },
  "yes": { ja: "hai", ko: "ne", zh: "shì", ar: "naʿam" },
  "no": { ja: "iie", ko: "aniyo", zh: "bù", ar: "lā" },
  "sorry": { ja: "sumimasen", ko: "mianhamnida", zh: "duìbuqǐ", ar: "āsif" },
  "excuse me": { ja: "sumimasen", ko: "sillyehamnida", zh: "dǎrǎo yīxià", ar: "ʿafwan" },
  "good morning": { ja: "ohayō gozaimasu", ko: "joeun achim", zh: "zǎoshang hǎo", ar: "ṣabāḥ al-khayr" },
  "good night": { ja: "oyasuminasai", ko: "annyeonghi jumuseyo", zh: "wǎn'ān", ar: "tuṣbiḥ ʿalā khayr" },
  "how are you": { ja: "ogenki desu ka", ko: "eotteoke jinaeseyo", zh: "nǐ hǎo ma", ar: "kayfa ḥālak" },
  "nice to meet you": { ja: "hajimemashite", ko: "mannaseo bangapseumnida", zh: "hěn gāoxìng rènshi nǐ", ar: "saʿīd biliqā'ik" },
  "see you later": { ja: "mata atode", ko: "najunge bwayo", zh: "huítóu jiàn", ar: "arāka lāḥiqan" },
  "welcome": { ja: "yōkoso", ko: "hwanyeonghamnida", zh: "huānyíng", ar: "ahlan wa sahlan" },
  "i": { ja: "watashi", ko: "na", zh: "wǒ", ar: "anā" },
  "you": { ja: "anata", ko: "dangsin", zh: "nǐ", ar: "anta" },
  "he": { ja: "kare", ko: "geu", zh: "tā", ar: "huwa" },
  "she": { ja: "kanojo", ko: "geunyeo", zh: "tā", ar: "hiya" },
  "we": { ja: "watashitachi", ko: "uri", zh: "wǒmen", ar: "naḥnu" },
  "they": { ja: "karera", ko: "geudeul", zh: "tāmen", ar: "hum" },
  "this": { ja: "kore", ko: "igeot", zh: "zhè", ar: "hādhā" },
  "that": { ja: "sore", ko: "jeogeot", zh: "nà", ar: "dhālik" },
  "what": { ja: "nani", ko: "mueot", zh: "shénme", ar: "mādhā" },
  "where": { ja: "doko", ko: "eodi", zh: "nǎlǐ", ar: "ayna" },
  "when": { ja: "itsu", ko: "eonje", zh: "shénme shíhou", ar: "matā" },
  "why": { ja: "naze", ko: "wae", zh: "wèishénme", ar: "limādhā" },
  "how": { ja: "dō", ko: "eotteoke", zh: "zěnme", ar: "kayfa" },
  "who": { ja: "dare", ko: "nugu", zh: "shéi", ar: "man" },

  // ── Numbers ──
  "zero": { ja: "rei", ko: "yeong", zh: "líng", ar: "ṣifr" },
  "one": { ja: "ichi", ko: "il / hana", zh: "yī", ar: "wāḥid" },
  "two": { ja: "ni", ko: "i / dul", zh: "èr", ar: "ithnān" },
  "three": { ja: "san", ko: "sam / set", zh: "sān", ar: "thalātha" },
  "four": { ja: "shi / yon", ko: "sa / net", zh: "sì", ar: "arbaʿa" },
  "five": { ja: "go", ko: "o / daseot", zh: "wǔ", ar: "khamsa" },
  "six": { ja: "roku", ko: "yuk / yeoseot", zh: "liù", ar: "sitta" },
  "seven": { ja: "shichi / nana", ko: "chil / ilgop", zh: "qī", ar: "sabʿa" },
  "eight": { ja: "hachi", ko: "pal / yeodeol", zh: "bā", ar: "thamāniya" },
  "nine": { ja: "kyū", ko: "gu / ahop", zh: "jiǔ", ar: "tisʿa" },
  "ten": { ja: "jū", ko: "sip / yeol", zh: "shí", ar: "ʿashara" },
  "eleven": { ja: "jūichi", ko: "sibil", zh: "shíyī", ar: "aḥada ʿashar" },
  "twelve": { ja: "jūni", ko: "sibi", zh: "shí'èr", ar: "ithnā ʿashar" },
  "twenty": { ja: "nijū", ko: "isip / seumul", zh: "èrshí", ar: "ʿishrūn" },
  "thirty": { ja: "sanjū", ko: "samsip / seoreun", zh: "sānshí", ar: "thalāthūn" },
  "forty": { ja: "yonjū", ko: "sasip / maheun", zh: "sìshí", ar: "arbaʿūn" },
  "fifty": { ja: "gojū", ko: "osip / swin", zh: "wǔshí", ar: "khamsūn" },
  "hundred": { ja: "hyaku", ko: "baek", zh: "bǎi", ar: "mi'a" },
  "thousand": { ja: "sen", ko: "cheon", zh: "qiān", ar: "alf" },
  "million": { ja: "hyakuman", ko: "baengman", zh: "bǎi wàn", ar: "milyūn" },
  "first": { ja: "saisho", ko: "cheot beonjjae", zh: "dì yī", ar: "awwal" },
  "second": { ja: "nibanme", ko: "du beonjjae", zh: "dì èr", ar: "thānī" },
  "third": { ja: "sanbanme", ko: "se beonjjae", zh: "dì sān", ar: "thālith" },
  "half": { ja: "hanbun", ko: "ban", zh: "yī bàn", ar: "niṣf" },
  "pair": { ja: "hitokumi", ko: "han ssang", zh: "yī duì", ar: "zawj" },

  // ── Colors ──
  "red": { ja: "aka", ko: "ppalgansaek", zh: "hóngsè", ar: "aḥmar" },
  "blue": { ja: "ao", ko: "paransaek", zh: "lánsè", ar: "azraq" },
  "green": { ja: "midori", ko: "choroksaek", zh: "lǜsè", ar: "akhḍar" },
  "yellow": { ja: "kiiro", ko: "noransaek", zh: "huángsè", ar: "aṣfar" },
  "orange": { ja: "orenji", ko: "juhwangsaek", zh: "chéngsè", ar: "burtuqālī" },
  "purple": { ja: "murasaki", ko: "borasaek", zh: "zǐsè", ar: "banafsajī" },
  "pink": { ja: "pinku", ko: "bunhongsaek", zh: "fěnsè", ar: "wardī" },
  "black": { ja: "kuro", ko: "geomeunsaek", zh: "hēisè", ar: "aswad" },
  "white": { ja: "shiro", ko: "huinsaek", zh: "báisè", ar: "abyaḍ" },
  "brown": { ja: "chairo", ko: "galsaek", zh: "zōngsè", ar: "bunnī" },
  "gray": { ja: "haiiro", ko: "hoesaek", zh: "huīsè", ar: "ramādī" },
  "gold": { ja: "kin'iro", ko: "geumsaek", zh: "jīnsè", ar: "dhahabī" },
  "silver": { ja: "gin'iro", ko: "eunsaek", zh: "yínsè", ar: "fiḍḍī" },
  "light": { ja: "akarui", ko: "balgeun", zh: "qiǎn", ar: "fātiḥ" },
  "dark": { ja: "kurai", ko: "eoduun", zh: "shēn", ar: "ghāmiq" },

  // ── Animals ──
  "dog": { ja: "inu", ko: "gae", zh: "gǒu", ar: "kalb" },
  "cat": { ja: "neko", ko: "goyangi", zh: "māo", ar: "qiṭṭa" },
  "bird": { ja: "tori", ko: "sae", zh: "niǎo", ar: "ṭā'ir" },
  "fish": { ja: "sakana", ko: "mulgogi", zh: "yú", ar: "samaka" },
  "horse": { ja: "uma", ko: "mal", zh: "mǎ", ar: "ḥiṣān" },
  "cow": { ja: "ushi", ko: "so", zh: "niú", ar: "baqara" },
  "pig": { ja: "buta", ko: "dwaeji", zh: "zhū", ar: "khinzīr" },
  "sheep": { ja: "hitsuji", ko: "yang", zh: "yáng", ar: "kharūf" },
  "chicken": { ja: "niwatori", ko: "dak", zh: "jī", ar: "dajāja" },
  "duck": { ja: "ahiru", ko: "ori", zh: "yā", ar: "baṭṭa" },
  "rabbit": { ja: "usagi", ko: "tokki", zh: "tùzi", ar: "arnab" },
  "mouse": { ja: "nezumi", ko: "jwi", zh: "lǎoshǔ", ar: "fa'r" },
  "elephant": { ja: "zō", ko: "kokkiri", zh: "dà xiàng", ar: "fīl" },
  "lion": { ja: "raion", ko: "saja", zh: "shīzi", ar: "asad" },
  "tiger": { ja: "tora", ko: "horangi", zh: "lǎohǔ", ar: "namir" },
  "bear": { ja: "kuma", ko: "gom", zh: "xióng", ar: "dubb" },
  "monkey": { ja: "saru", ko: "wonsungi", zh: "hóuzi", ar: "qird" },
  "snake": { ja: "hebi", ko: "baem", zh: "shé", ar: "thuʿbān" },
  "frog": { ja: "kaeru", ko: "gaeguri", zh: "qīngwā", ar: "ḍifdaʿ" },
  "turtle": { ja: "kame", ko: "geobuki", zh: "wūguī", ar: "sulḥafāt" },
  "whale": { ja: "kujira", ko: "gorae", zh: "jīngyú", ar: "ḥūt" },
  "dolphin": { ja: "iruka", ko: "dolgorae", zh: "hǎitún", ar: "dalfīn" },
  "butterfly": { ja: "chō", ko: "nabi", zh: "húdié", ar: "farāsha" },
  "bee": { ja: "hachi", ko: "beol", zh: "mìfēng", ar: "naḥla" },
  "ant": { ja: "ari", ko: "gaemi", zh: "mǎyǐ", ar: "namla" },
  "spider": { ja: "kumo", ko: "geomi", zh: "zhīzhū", ar: "ʿankabūt" },
  "wolf": { ja: "ōkami", ko: "neukdae", zh: "láng", ar: "dhi'b" },
  "fox": { ja: "kitsune", ko: "yeou", zh: "húli", ar: "thaʿlab" },
  "deer": { ja: "shika", ko: "saseum", zh: "lù", ar: "ghazāl" },
  "eagle": { ja: "washi", ko: "doksuri", zh: "yīng", ar: "nasr" },

  // ── Food & Drinks ──
  "water": { ja: "mizu", ko: "mul", zh: "shuǐ", ar: "mā'" },
  "bread": { ja: "pan", ko: "ppang", zh: "miànbāo", ar: "khubz" },
  "rice": { ja: "gohan", ko: "bap", zh: "mǐfàn", ar: "aruzz" },
  "meat": { ja: "niku", ko: "gogi", zh: "ròu", ar: "laḥm" },
  "egg": { ja: "tamago", ko: "dalgyal", zh: "jīdàn", ar: "bayḍa" },
  "milk": { ja: "gyūnyū", ko: "uyu", zh: "niúnǎi", ar: "ḥalīb" },
  "cheese": { ja: "chīzu", ko: "chijeu", zh: "nǎilào", ar: "jubn" },
  "butter": { ja: "batā", ko: "beoteo", zh: "huángyóu", ar: "zubda" },
  "sugar": { ja: "satō", ko: "seoltang", zh: "táng", ar: "sukkar" },
  "salt": { ja: "shio", ko: "sogeum", zh: "yán", ar: "milḥ" },
  "apple": { ja: "ringo", ko: "sagwa", zh: "píngguǒ", ar: "tuffāḥa" },
  "banana": { ja: "banana", ko: "banana", zh: "xiāngjiāo", ar: "mawz" },
  "orange (fruit)": { ja: "orenji", ko: "orenji", zh: "chéngzi", ar: "burtuqāl" },
  "grape": { ja: "budō", ko: "podo", zh: "pútao", ar: "ʿinab" },
  "strawberry": { ja: "ichigo", ko: "ttalgi", zh: "cǎoméi", ar: "farāwla" },
  "tomato": { ja: "tomato", ko: "tomato", zh: "fānqié", ar: "ṭamāṭim" },
  "potato": { ja: "jagaimo", ko: "gamja", zh: "tǔdòu", ar: "baṭāṭā" },
  "onion": { ja: "tamanegi", ko: "yangpa", zh: "yángcōng", ar: "baṣal" },
  "carrot": { ja: "ninjin", ko: "danggeun", zh: "húluóbo", ar: "jazar" },
  "pepper": { ja: "pīman", ko: "gochu", zh: "làjiāo", ar: "fulful" },
  "coffee": { ja: "kōhī", ko: "keopi", zh: "kāfēi", ar: "qahwa" },
  "tea": { ja: "ocha", ko: "cha", zh: "chá", ar: "shāy" },
  "juice": { ja: "jūsu", ko: "juseu", zh: "guǒzhī", ar: "ʿaṣīr" },
  "soup": { ja: "sūpu", ko: "supeu", zh: "tāng", ar: "ḥasā'" },
  "salad": { ja: "sarada", ko: "saelleodeu", zh: "shālā", ar: "salaṭa" },
  "cake": { ja: "kēki", ko: "keikeu", zh: "dàngāo", ar: "kaʿka" },
  "chocolate": { ja: "chokorēto", ko: "chokollit", zh: "qiǎokèlì", ar: "shūkūlāta" },
  "ice cream": { ja: "aisukurīmu", ko: "aiseukeulim", zh: "bīngqílín", ar: "āys krīm" },
  "oil": { ja: "abura", ko: "gireum", zh: "yóu", ar: "zayt" },
  "flour": { ja: "komugiko", ko: "milgaru", zh: "miànfěn", ar: "daqīq" },
  "noodle": { ja: "men", ko: "guksu", zh: "miàntiáo", ar: "maʿkarūna" },
  "bean": { ja: "mame", ko: "kong", zh: "dòu", ar: "fāṣūlyā" },
  "mushroom": { ja: "kinoko", ko: "beoseot", zh: "mógu", ar: "fiṭr" },
  "garlic": { ja: "ninniku", ko: "maneul", zh: "dàsuàn", ar: "thūm" },
  "lemon": { ja: "remon", ko: "remon", zh: "níngméng", ar: "laymūn" },

  // ── Family ──
  "mother": { ja: "haha", ko: "eomeoni", zh: "mǔqīn", ar: "umm" },
  "father": { ja: "chichi", ko: "abeoji", zh: "fùqīn", ar: "ab" },
  "sister": { ja: "shimai", ko: "jamae", zh: "jiěmèi", ar: "ukht" },
  "brother": { ja: "kyōdai", ko: "hyeongje", zh: "xiōngdì", ar: "akh" },
  "son": { ja: "musuko", ko: "adeul", zh: "érzi", ar: "ibn" },
  "daughter": { ja: "musume", ko: "ttal", zh: "nǚ'ér", ar: "ibna" },
  "grandmother": { ja: "sobo", ko: "halmeoni", zh: "zǔmǔ", ar: "jadda" },
  "grandfather": { ja: "sofu", ko: "harabeoji", zh: "zǔfù", ar: "jadd" },
  "baby": { ja: "akachan", ko: "agi", zh: "yīng'ér", ar: "ṭifl raḍīʿ" },
  "child": { ja: "kodomo", ko: "ai", zh: "háizi", ar: "ṭifl" },
  "husband": { ja: "otto", ko: "nampyeon", zh: "zhàngfu", ar: "zawj" },
  "wife": { ja: "tsuma", ko: "anae", zh: "qīzi", ar: "zawja" },
  "uncle": { ja: "oji", ko: "samchon", zh: "shūshu", ar: "ʿamm" },
  "aunt": { ja: "oba", ko: "imo / gomo", zh: "āyí", ar: "ʿamma" },
  "cousin": { ja: "itoko", ko: "sachon", zh: "biǎo xiōngdì", ar: "ibn ʿamm" },
  "friend": { ja: "tomodachi", ko: "chingu", zh: "péngyou", ar: "ṣadīq" },
  "neighbor": { ja: "rinjin", ko: "iut", zh: "línjū", ar: "jār" },
  "family": { ja: "kazoku", ko: "gajok", zh: "jiātíng", ar: "ʿā'ila" },
  "person": { ja: "hito", ko: "saram", zh: "rén", ar: "shakhs" },
  "man": { ja: "otoko", ko: "namja", zh: "nánrén", ar: "rajul" },
  "woman": { ja: "onna", ko: "yeoja", zh: "nǚrén", ar: "imra'a" },

  // ── Body Parts ──
  "head": { ja: "atama", ko: "meori", zh: "tóu", ar: "ra's" },
  "hair": { ja: "kami", ko: "meorikarak", zh: "tóufa", ar: "shaʿr" },
  "face": { ja: "kao", ko: "eolgul", zh: "liǎn", ar: "wajh" },
  "eye": { ja: "me", ko: "nun", zh: "yǎnjīng", ar: "ʿayn" },
  "ear": { ja: "mimi", ko: "gwi", zh: "ěrduo", ar: "udhun" },
  "nose": { ja: "hana", ko: "ko", zh: "bízi", ar: "anf" },
  "mouth": { ja: "kuchi", ko: "ip", zh: "zuǐ", ar: "fam" },
  "tooth": { ja: "ha", ko: "i", zh: "yáchǐ", ar: "sinn" },
  "tongue": { ja: "shita", ko: "hyeo", zh: "shétou", ar: "lisān" },
  "neck": { ja: "kubi", ko: "mok", zh: "bózi", ar: "raqaba" },
  "shoulder": { ja: "kata", ko: "eokkae", zh: "jiānbǎng", ar: "katif" },
  "arm": { ja: "ude", ko: "pal", zh: "shǒubì", ar: "dhirāʿ" },
  "hand": { ja: "te", ko: "son", zh: "shǒu", ar: "yad" },
  "finger": { ja: "yubi", ko: "songarak", zh: "shǒuzhǐ", ar: "iṣbaʿ" },
  "chest": { ja: "mune", ko: "gaseum", zh: "xiōng", ar: "ṣadr" },
  "back": { ja: "senaka", ko: "deung", zh: "bèi", ar: "ẓahr" },
  "stomach": { ja: "onaka", ko: "bae", zh: "wèi", ar: "maʿida" },
  "leg": { ja: "ashi", ko: "dari", zh: "tuǐ", ar: "sāq" },
  "knee": { ja: "hiza", ko: "mureup", zh: "xīgài", ar: "rukba" },
  "foot": { ja: "ashi", ko: "bal", zh: "jiǎo", ar: "qadam" },
  "heart": { ja: "shinzō", ko: "simjang", zh: "xīnzàng", ar: "qalb" },
  "blood": { ja: "chi", ko: "pi", zh: "xuè", ar: "damm" },
  "bone": { ja: "hone", ko: "ppyeo", zh: "gǔtou", ar: "ʿaẓm" },
  "skin": { ja: "hada", ko: "pibu", zh: "pífū", ar: "jild" },

  // ── Clothing ──
  "shirt": { ja: "shatsu", ko: "syeocheu", zh: "chènshān", ar: "qamīṣ" },
  "pants": { ja: "zubon", ko: "baji", zh: "kùzi", ar: "banṭalūn" },
  "dress": { ja: "doresu", ko: "deureseu", zh: "qúnzi", ar: "fustān" },
  "skirt": { ja: "sukāto", ko: "chima", zh: "duǎnqún", ar: "tannūra" },
  "jacket": { ja: "jaketto", ko: "jaekit", zh: "jiākè", ar: "sutra" },
  "coat": { ja: "kōto", ko: "koteu", zh: "dàyī", ar: "miʿṭaf" },
  "shoes": { ja: "kutsu", ko: "sinbal", zh: "xiézi", ar: "aḥdhiya" },
  "boots": { ja: "būtsu", ko: "bucheu", zh: "xuēzi", ar: "jizma" },
  "hat": { ja: "bōshi", ko: "moja", zh: "màozi", ar: "qubbaʿa" },
  "socks": { ja: "kutsushita", ko: "yangmal", zh: "wàzi", ar: "jawārib" },
  "gloves": { ja: "tebukuro", ko: "janggap", zh: "shǒutào", ar: "quffāzāt" },
  "scarf": { ja: "mafurā", ko: "seukapeu", zh: "wéijīn", ar: "wishāḥ" },
  "belt": { ja: "beruto", ko: "belteu", zh: "yāodài", ar: "ḥizām" },
  "bag": { ja: "kaban", ko: "gabang", zh: "bāo", ar: "ḥaqība" },
  "umbrella": { ja: "kasa", ko: "usan", zh: "yǔsǎn", ar: "miẓalla" },

  // ── Time & Calendar ──
  "today": { ja: "kyō", ko: "oneul", zh: "jīntiān", ar: "al-yawm" },
  "tomorrow": { ja: "ashita", ko: "naeil", zh: "míngtiān", ar: "ghadan" },
  "yesterday": { ja: "kinō", ko: "eoje", zh: "zuótiān", ar: "ams" },
  "morning": { ja: "asa", ko: "achim", zh: "zǎoshang", ar: "ṣabāḥ" },
  "afternoon": { ja: "gogo", ko: "ohu", zh: "xiàwǔ", ar: "baʿd aẓ-ẓuhr" },
  "evening": { ja: "yūgata", ko: "jeonyeok", zh: "bàngwǎn", ar: "masā'" },
  "night": { ja: "yoru", ko: "bam", zh: "yèwǎn", ar: "layl" },
  "monday": { ja: "getsuyōbi", ko: "woryoil", zh: "xīngqī yī", ar: "al-ithnayn" },
  "tuesday": { ja: "kayōbi", ko: "hwayoil", zh: "xīngqī èr", ar: "ath-thulāthā'" },
  "wednesday": { ja: "suiyōbi", ko: "suyoil", zh: "xīngqī sān", ar: "al-arbiʿā'" },
  "thursday": { ja: "mokuyōbi", ko: "mogyoil", zh: "xīngqī sì", ar: "al-khamīs" },
  "friday": { ja: "kin'yōbi", ko: "geumyoil", zh: "xīngqī wǔ", ar: "al-jumʿa" },
  "saturday": { ja: "doyōbi", ko: "toyoil", zh: "xīngqī liù", ar: "as-sabt" },
  "sunday": { ja: "nichiyōbi", ko: "iryoil", zh: "xīngqī rì", ar: "al-aḥad" },
  "january": { ja: "ichigatsu", ko: "irwol", zh: "yī yuè", ar: "yanāyir" },
  "february": { ja: "nigatsu", ko: "iwol", zh: "èr yuè", ar: "fibrāyir" },
  "march": { ja: "sangatsu", ko: "samwol", zh: "sān yuè", ar: "māris" },
  "april": { ja: "shigatsu", ko: "sawol", zh: "sì yuè", ar: "abrīl" },
  "may": { ja: "gogatsu", ko: "owol", zh: "wǔ yuè", ar: "māyū" },
  "june": { ja: "rokugatsu", ko: "yuwol", zh: "liù yuè", ar: "yūnyū" },
  "year": { ja: "nen / toshi", ko: "nyeon", zh: "nián", ar: "sana" },
  "month": { ja: "tsuki", ko: "dal", zh: "yuè", ar: "shahr" },
  "week": { ja: "shū", ko: "ju", zh: "zhōu", ar: "usbūʿ" },
  "day": { ja: "hi", ko: "il", zh: "tiān", ar: "yawm" },
  "hour": { ja: "jikan", ko: "sigan", zh: "xiǎoshí", ar: "sāʿa" },
  "minute": { ja: "fun / pun", ko: "bun", zh: "fēnzhōng", ar: "daqīqa" },
  "now": { ja: "ima", ko: "jigeum", zh: "xiànzài", ar: "al-ān" },
  "always": { ja: "itsumo", ko: "hangsang", zh: "zǒngshì", ar: "dā'iman" },
  "never": { ja: "kesshite", ko: "jeoldae", zh: "cóng bù", ar: "abadan" },

  // ── Weather & Nature ──
  "sun": { ja: "taiyō", ko: "taeyang", zh: "tàiyáng", ar: "shams" },
  "moon": { ja: "tsuki", ko: "dal", zh: "yuèliang", ar: "qamar" },
  "star": { ja: "hoshi", ko: "byeol", zh: "xīngxing", ar: "najma" },
  "sky": { ja: "sora", ko: "haneul", zh: "tiānkōng", ar: "samā'" },
  "cloud": { ja: "kumo", ko: "gureum", zh: "yún", ar: "saḥāba" },
  "rain": { ja: "ame", ko: "bi", zh: "yǔ", ar: "maṭar" },
  "snow": { ja: "yuki", ko: "nun", zh: "xuě", ar: "thalj" },
  "wind": { ja: "kaze", ko: "baram", zh: "fēng", ar: "riyāḥ" },
  "storm": { ja: "arashi", ko: "pokpung", zh: "bàofēngyǔ", ar: "ʿāṣifa" },
  "hot": { ja: "atsui", ko: "deoun", zh: "rè", ar: "ḥārr" },
  "cold": { ja: "samui", ko: "chuun", zh: "lěng", ar: "bārid" },
  "tree": { ja: "ki", ko: "namu", zh: "shù", ar: "shajara" },
  "flower": { ja: "hana", ko: "kkot", zh: "huā", ar: "zahra" },
  "grass": { ja: "kusa", ko: "pul", zh: "cǎo", ar: "ʿushb" },
  "mountain": { ja: "yama", ko: "san", zh: "shān", ar: "jabal" },
  "river": { ja: "kawa", ko: "gang", zh: "hé", ar: "nahr" },
  "sea": { ja: "umi", ko: "bada", zh: "hǎi", ar: "baḥr" },
  "lake": { ja: "mizuumi", ko: "hosu", zh: "hú", ar: "buḥayra" },
  "forest": { ja: "mori", ko: "sup", zh: "sēnlín", ar: "ghāba" },
  "island": { ja: "shima", ko: "seom", zh: "dǎo", ar: "jazīra" },
  "earth": { ja: "chikyū", ko: "jigu", zh: "dìqiú", ar: "arḍ" },
  "fire": { ja: "hi", ko: "bul", zh: "huǒ", ar: "nār" },
  "ice": { ja: "kōri", ko: "eoreum", zh: "bīng", ar: "jalīd" },
  "stone": { ja: "ishi", ko: "dol", zh: "shítou", ar: "ḥajar" },
  "sand": { ja: "suna", ko: "morae", zh: "shā", ar: "raml" },

  // ── House & Home ──
  "house": { ja: "ie", ko: "jip", zh: "fángzi", ar: "manzil" },
  "door": { ja: "doa", ko: "mun", zh: "mén", ar: "bāb" },
  "window": { ja: "mado", ko: "changmun", zh: "chuānghu", ar: "nāfidha" },
  "room": { ja: "heya", ko: "bang", zh: "fángjiān", ar: "ghurfa" },
  "kitchen": { ja: "daidokoro", ko: "bueok", zh: "chúfáng", ar: "maṭbakh" },
  "bathroom": { ja: "yokushitsu", ko: "yoksil", zh: "yùshì", ar: "ḥammām" },
  "bedroom": { ja: "shinshitsu", ko: "chimsil", zh: "wòshì", ar: "ghurfat nawm" },
  "table": { ja: "tēburu", ko: "takja", zh: "zhuōzi", ar: "ṭāwila" },
  "chair": { ja: "isu", ko: "uija", zh: "yǐzi", ar: "kursī" },
  "bed": { ja: "beddo", ko: "chimdae", zh: "chuáng", ar: "sarīr" },
  "mirror": { ja: "kagami", ko: "geoul", zh: "jìngzi", ar: "mir'āt" },
  "lamp": { ja: "ranpu", ko: "raempeu", zh: "dēng", ar: "miṣbāḥ" },
  "stairs": { ja: "kaidan", ko: "gyedan", zh: "lóutī", ar: "daraj" },
  "wall": { ja: "kabe", ko: "byeok", zh: "qiáng", ar: "jidār" },
  "floor": { ja: "yuka", ko: "badak", zh: "dìbǎn", ar: "arḍiyya" },
  "roof": { ja: "yane", ko: "jibung", zh: "wūdǐng", ar: "saqf" },
  "garden": { ja: "niwa", ko: "jeongwon", zh: "huāyuán", ar: "ḥadīqa" },
  "key": { ja: "kagi", ko: "yeolsoe", zh: "yàoshi", ar: "miftāḥ" },
  "clock": { ja: "tokei", ko: "sigye", zh: "shízhōng", ar: "sāʿat ḥā'iṭ" },
  "telephone": { ja: "denwa", ko: "jeonhwa", zh: "diànhuà", ar: "hātif" },

  // ── Transportation ──
  "car": { ja: "kuruma", ko: "jadongcha", zh: "qìchē", ar: "sayyāra" },
  "bus": { ja: "basu", ko: "beoseu", zh: "gōnggòng qìchē", ar: "ḥāfila" },
  "train": { ja: "densha", ko: "gicha", zh: "huǒchē", ar: "qiṭār" },
  "airplane": { ja: "hikōki", ko: "bihaenggi", zh: "fēijī", ar: "ṭā'ira" },
  "bicycle": { ja: "jitensha", ko: "jajeongeo", zh: "zìxíngchē", ar: "darrāja" },
  "boat": { ja: "fune", ko: "bae", zh: "chuán", ar: "qārib" },
  "ship": { ja: "fune", ko: "bae", zh: "chuán", ar: "safīna" },
  "taxi": { ja: "takushī", ko: "taeksi", zh: "chūzū chē", ar: "sayyārat ujra" },
  "motorcycle": { ja: "baiku", ko: "otobai", zh: "mótuōchē", ar: "darrāja nāriyya" },
  "truck": { ja: "torakku", ko: "teureok", zh: "kǎchē", ar: "shāḥina" },
  "subway": { ja: "chikatetsu", ko: "jihacheol", zh: "dìtiě", ar: "metrō" },
  "road": { ja: "michi", ko: "gil", zh: "lù", ar: "ṭarīq" },
  "bridge": { ja: "hashi", ko: "dari", zh: "qiáo", ar: "jisr" },
  "ticket": { ja: "kippu", ko: "pyo", zh: "piào", ar: "tadhkira" },
  "map": { ja: "chizu", ko: "jido", zh: "dìtú", ar: "kharīṭa" },

  // ── Occupations ──
  "teacher": { ja: "sensei", ko: "seonsaengnim", zh: "lǎoshī", ar: "muʿallim" },
  "doctor": { ja: "isha", ko: "uisa", zh: "yīshēng", ar: "ṭabīb" },
  "nurse": { ja: "kangoshi", ko: "ganhosa", zh: "hùshi", ar: "mumarriḍ" },
  "engineer": { ja: "enjinia", ko: "enjinieo", zh: "gōngchéngshī", ar: "muhandis" },
  "student": { ja: "gakusei", ko: "haksaeng", zh: "xuéshēng", ar: "ṭālib" },
  "police": { ja: "keisatsu", ko: "gyeongchal", zh: "jǐngchá", ar: "shurṭa" },
  "farmer": { ja: "nōka", ko: "nongbu", zh: "nóngmín", ar: "muzāriʿ" },
  "cook": { ja: "ryōrinin", ko: "yorisa", zh: "chúshī", ar: "ṭabbākh" },
  "driver": { ja: "untenshu", ko: "unjeonsa", zh: "sījī", ar: "sā'iq" },
  "lawyer": { ja: "bengoshi", ko: "byeonhosa", zh: "lǜshī", ar: "muḥāmī" },
  "artist": { ja: "geijutsuka", ko: "yesulga", zh: "yìshùjiā", ar: "fannān" },
  "musician": { ja: "ongakuka", ko: "eumakga", zh: "yīnyuèjiā", ar: "mūsīqī" },
  "writer": { ja: "sakka", ko: "jakga", zh: "zuòjiā", ar: "kātib" },
  "pilot": { ja: "pairotto", ko: "jojongsa", zh: "fēixíngyuán", ar: "ṭayyār" },
  "soldier": { ja: "heishi", ko: "gunin", zh: "shìbīng", ar: "jundī" },

  // ── Common Verbs ──
  "to be": { ja: "desu / iru", ko: "ida / itda", zh: "shì", ar: "yakūn" },
  "to have": { ja: "motsu", ko: "gajida", zh: "yǒu", ar: "yamlik" },
  "to do": { ja: "suru", ko: "hada", zh: "zuò", ar: "yafʿal" },
  "to go": { ja: "iku", ko: "gada", zh: "qù", ar: "yadhhab" },
  "to come": { ja: "kuru", ko: "oda", zh: "lái", ar: "ya'tī" },
  "to say": { ja: "iu", ko: "malhada", zh: "shuō", ar: "yaqūl" },
  "to see": { ja: "miru", ko: "boda", zh: "kàn", ar: "yarā" },
  "to know": { ja: "shiru", ko: "alda", zh: "zhīdào", ar: "yaʿrif" },
  "to think": { ja: "omou", ko: "saenggakhada", zh: "xiǎng", ar: "yufakkir" },
  "to want": { ja: "hoshii", ko: "wonhada", zh: "xiǎng yào", ar: "yurīd" },
  "to eat": { ja: "taberu", ko: "meokda", zh: "chī", ar: "ya'kul" },
  "to drink": { ja: "nomu", ko: "masida", zh: "hē", ar: "yashrab" },
  "to sleep": { ja: "neru", ko: "jada", zh: "shuìjiào", ar: "yanām" },
  "to walk": { ja: "aruku", ko: "geotda", zh: "zǒu", ar: "yamshī" },
  "to run": { ja: "hashiru", ko: "dallida", zh: "pǎo", ar: "yarkuḍ" },
  "to read": { ja: "yomu", ko: "ikda", zh: "dú", ar: "yaqra'" },
  "to write": { ja: "kaku", ko: "sseuda", zh: "xiě", ar: "yaktub" },
  "to speak": { ja: "hanasu", ko: "malhada", zh: "shuō", ar: "yatakallam" },
  "to listen": { ja: "kiku", ko: "deutda", zh: "tīng", ar: "yastamiʿ" },
  "to understand": { ja: "wakaru", ko: "ihaehada", zh: "lǐjiě", ar: "yafham" },
  "to give": { ja: "ageru", ko: "juda", zh: "gěi", ar: "yuʿṭī" },
  "to take": { ja: "toru", ko: "gajyeogada", zh: "ná", ar: "ya'khudh" },
  "to buy": { ja: "kau", ko: "sada", zh: "mǎi", ar: "yashtarī" },
  "to sell": { ja: "uru", ko: "palda", zh: "mài", ar: "yabīʿ" },
  "to open": { ja: "akeru", ko: "yeolda", zh: "kāi", ar: "yaftaḥ" },
  "to close": { ja: "shimeru", ko: "datda", zh: "guān", ar: "yughlik" },
  "to sit": { ja: "suwaru", ko: "anda", zh: "zuò", ar: "yajlis" },
  "to stand": { ja: "tatsu", ko: "seoda", zh: "zhàn", ar: "yaqif" },
  "to love": { ja: "ai suru", ko: "saranghada", zh: "ài", ar: "yuḥibb" },
  "to like": { ja: "suki", ko: "joahada", zh: "xǐhuan", ar: "yuʿjib" },
  "to help": { ja: "tasukeru", ko: "dopda", zh: "bāngzhù", ar: "yusāʿid" },
  "to learn": { ja: "manabu", ko: "baeuda", zh: "xuéxí", ar: "yataʿallam" },
  "to teach": { ja: "oshieru", ko: "gareuchida", zh: "jiāo", ar: "yuʿallim" },
  "to work": { ja: "hataraku", ko: "ilhada", zh: "gōngzuò", ar: "yaʿmal" },
  "to play": { ja: "asobu", ko: "nolda", zh: "wán", ar: "yalʿab" },
  "to sing": { ja: "utau", ko: "noraehada", zh: "chàng", ar: "yughannī" },
  "to dance": { ja: "odoru", ko: "chumchuda", zh: "tiàowǔ", ar: "yarquṣ" },
  "to swim": { ja: "oyogu", ko: "suyeonghada", zh: "yóuyǒng", ar: "yasbaḥ" },
  "to fly": { ja: "tobu", ko: "nalda", zh: "fēi", ar: "yaṭīr" },
  "to wait": { ja: "matsu", ko: "gidarida", zh: "děng", ar: "yantaẓir" },
  "to find": { ja: "mitsukeru", ko: "chatda", zh: "zhǎodào", ar: "yajid" },
  "to make": { ja: "tsukuru", ko: "mandeulda", zh: "zuò", ar: "yaṣnaʿ" },
  "to put": { ja: "oku", ko: "nohda", zh: "fàng", ar: "yaḍaʿ" },
  "to use": { ja: "tsukau", ko: "sayonghada", zh: "yòng", ar: "yastakhdim" },
  "to try": { ja: "tamesu", ko: "sidohada", zh: "shì", ar: "yuḥāwil" },
  "to begin": { ja: "hajimeru", ko: "sijakhada", zh: "kāishǐ", ar: "yabda'" },
  "to finish": { ja: "owaru", ko: "kkeutnaeda", zh: "jiéshù", ar: "yunhī" },
  "to send": { ja: "okuru", ko: "bonaeda", zh: "fāsòng", ar: "yursil" },
  "to receive": { ja: "uketoru", ko: "batda", zh: "shōudào", ar: "yastlim" },
  "to remember": { ja: "oboeru", ko: "gieokhada", zh: "jìzhù", ar: "yatadhakkar" },

  // ── Common Adjectives ──
  "big": { ja: "ōkii", ko: "keun", zh: "dà", ar: "kabīr" },
  "small": { ja: "chiisai", ko: "jageun", zh: "xiǎo", ar: "ṣaghīr" },
  "long": { ja: "nagai", ko: "gin", zh: "cháng", ar: "ṭawīl" },
  "short": { ja: "mijikai", ko: "jjalbeun", zh: "duǎn", ar: "qaṣīr" },
  "tall": { ja: "takai", ko: "kiga keun", zh: "gāo", ar: "ṭawīl al-qāma" },
  "new": { ja: "atarashii", ko: "saeroun", zh: "xīn", ar: "jadīd" },
  "old": { ja: "furui", ko: "oraedoen", zh: "jiù", ar: "qadīm" },
  "good": { ja: "yoi", ko: "joeun", zh: "hǎo", ar: "jayyid" },
  "bad": { ja: "warui", ko: "nappeun", zh: "huài", ar: "sayyi'" },
  "beautiful": { ja: "utsukushii", ko: "areumdaun", zh: "měilì", ar: "jamīl" },
  "ugly": { ja: "minikui", ko: "motsaenggin", zh: "chǒu", ar: "qabīḥ" },
  "fast": { ja: "hayai", ko: "ppareun", zh: "kuài", ar: "sarīʿ" },
  "slow": { ja: "osoi", ko: "neurin", zh: "màn", ar: "baṭī'" },
  "heavy": { ja: "omoi", ko: "mugeoun", zh: "zhòng", ar: "thaqīl" },
  "easy": { ja: "kantan", ko: "swiun", zh: "róngyì", ar: "sahl" },
  "difficult": { ja: "muzukashii", ko: "eoryeoun", zh: "nán", ar: "ṣaʿb" },
  "clean": { ja: "kirei", ko: "kkaekkeuthan", zh: "gānjìng", ar: "naẓīf" },
  "dirty": { ja: "kitanai", ko: "deoreoun", zh: "zāng", ar: "qadhir" },
  "rich": { ja: "kanemochi", ko: "buyuhan", zh: "fùyǒu", ar: "ghanī" },
  "poor": { ja: "mazushii", ko: "gananhan", zh: "qióng", ar: "faqīr" },
  "full": { ja: "ippai", ko: "gadeuk chan", zh: "mǎn", ar: "mumtali'" },
  "empty": { ja: "kara", ko: "bin", zh: "kōng", ar: "fārigh" },
  "strong": { ja: "tsuyoi", ko: "ganghan", zh: "qiáng", ar: "qawī" },
  "weak": { ja: "yowai", ko: "yakhan", zh: "ruò", ar: "ḍaʿīf" },
  "young": { ja: "wakai", ko: "jeolmeun", zh: "niánqīng", ar: "shābb" },
  "right": { ja: "tadashii", ko: "olbareun", zh: "duì", ar: "ṣaḥīḥ" },
  "wrong": { ja: "machigai", ko: "teullin", zh: "cuò", ar: "khāṭi'" },
  "happy": { ja: "shiawase", ko: "haengbokhan", zh: "kuàilè", ar: "saʿīd" },
  "sad": { ja: "kanashii", ko: "seulpeun", zh: "shāngxīn", ar: "ḥazīn" },
  "important": { ja: "taisetsu", ko: "jungyohan", zh: "zhòngyào", ar: "muhimm" },

  // ── Emotions & Feelings ──
  "angry": { ja: "okotteiru", ko: "hwanan", zh: "shēngqì", ar: "ghāḍib" },
  "scared": { ja: "kowai", ko: "museoun", zh: "hàipà", ar: "khā'if" },
  "tired": { ja: "tsukareta", ko: "pigonhan", zh: "lèi", ar: "mutʿab" },
  "hungry": { ja: "onaka ga suita", ko: "baegopeun", zh: "è", ar: "jā'iʿ" },
  "thirsty": { ja: "nodo ga kawaita", ko: "mongmareun", zh: "kě", ar: "ʿaṭshān" },
  "surprised": { ja: "odoroita", ko: "nollan", zh: "jīngyà", ar: "mundahish" },
  "excited": { ja: "wakuwaku shita", ko: "sinnaneun", zh: "xīngfèn", ar: "mutaḥammis" },
  "bored": { ja: "taikutsu", ko: "jiruhan", zh: "wúliáo", ar: "malal" },
  "nervous": { ja: "kinchō shita", ko: "ginjanhan", zh: "jǐnzhāng", ar: "mutawattir" },
  "proud": { ja: "hokori ni omou", ko: "jarangseureon", zh: "jiāo'ào", ar: "fakhūr" },
  "lonely": { ja: "sabishii", ko: "oeroun", zh: "gūdú", ar: "waḥīd" },
  "jealous": { ja: "shitto shita", ko: "jiltuhaneun", zh: "jídù", ar: "ghayūr" },
  "calm": { ja: "odayaka", ko: "chabunhan", zh: "píngjìng", ar: "hādi'" },
  "confident": { ja: "jishin ga aru", ko: "jasingam inneun", zh: "zìxìn", ar: "wāthiq" },
  "grateful": { ja: "kansha shiteiru", ko: "gamsahaneun", zh: "gǎnjī", ar: "mumtann" },

  // ── Places ──
  "city": { ja: "toshi", ko: "dosi", zh: "chéngshì", ar: "madīna" },
  "country": { ja: "kuni", ko: "nara", zh: "guójiā", ar: "balad" },
  "school": { ja: "gakkō", ko: "hakgyo", zh: "xuéxiào", ar: "madrasa" },
  "hospital": { ja: "byōin", ko: "byeongwon", zh: "yīyuàn", ar: "mustashfā" },
  "church": { ja: "kyōkai", ko: "gyohoe", zh: "jiàotáng", ar: "kanīsa" },
  "store": { ja: "mise", ko: "gage", zh: "shāngdiàn", ar: "matjar" },
  "restaurant": { ja: "resutoran", ko: "sikdang", zh: "cāntīng", ar: "maṭʿam" },
  "park": { ja: "kōen", ko: "gongwon", zh: "gōngyuán", ar: "ḥadīqat ʿāmma" },
  "library": { ja: "toshokan", ko: "doseogwan", zh: "túshūguǎn", ar: "maktaba" },
  "museum": { ja: "hakubutsukan", ko: "bangmulgwan", zh: "bówùguǎn", ar: "matḥaf" },
  "bank": { ja: "ginkō", ko: "eunhaeng", zh: "yínháng", ar: "bank" },
  "airport": { ja: "kūkō", ko: "gonghang", zh: "jīchǎng", ar: "maṭār" },
  "station": { ja: "eki", ko: "yeok", zh: "zhàn", ar: "maḥaṭṭa" },
  "market": { ja: "ichiba", ko: "sijang", zh: "shìchǎng", ar: "sūq" },
  "hotel": { ja: "hoteru", ko: "hotel", zh: "jiǔdiàn", ar: "funduq" },
  "beach": { ja: "bīchi", ko: "haebyeon", zh: "hǎitān", ar: "shāṭi'" },
  "office": { ja: "jimusho", ko: "samusil", zh: "bàngōngshì", ar: "maktab" },
  "street": { ja: "tōri", ko: "geori", zh: "jiēdào", ar: "shāriʿ" },

  // ── School & Work ──
  "book": { ja: "hon", ko: "chaek", zh: "shū", ar: "kitāb" },
  "pen": { ja: "pen", ko: "pen", zh: "bǐ", ar: "qalam" },
  "paper": { ja: "kami", ko: "jongi", zh: "zhǐ", ar: "waraqa" },
  "pencil": { ja: "enpitsu", ko: "yeonpil", zh: "qiānbǐ", ar: "qalam raṣāṣ" },
  "computer": { ja: "konpyūta", ko: "keompyuteo", zh: "diànnǎo", ar: "ḥāsūb" },
  "class": { ja: "jugyō", ko: "sueop", zh: "kè", ar: "ṣaff" },
  "exam": { ja: "shiken", ko: "siheom", zh: "kǎoshì", ar: "imtiḥān" },
  "homework": { ja: "shukudai", ko: "sukje", zh: "zuòyè", ar: "wājib manzilī" },
  "question": { ja: "shitsumon", ko: "jilmun", zh: "wèntí", ar: "su'āl" },
  "answer": { ja: "kotae", ko: "daedap", zh: "huídá", ar: "jawāb" },
  "money": { ja: "okane", ko: "don", zh: "qián", ar: "māl" },
  "job": { ja: "shigoto", ko: "jigeop", zh: "gōngzuò", ar: "waẓīfa" },
  "meeting": { ja: "kaigi", ko: "hoeui", zh: "huìyì", ar: "ijtimāʿ" },
  "idea": { ja: "aidea", ko: "aidieo", zh: "zhǔyi", ar: "fikra" },
  "problem": { ja: "mondai", ko: "munje", zh: "wèntí", ar: "mushkila" },
  "language": { ja: "gengo", ko: "eoneo", zh: "yǔyán", ar: "lugha" },
  "word": { ja: "kotoba", ko: "daneo", zh: "cí", ar: "kalima" },
  "letter": { ja: "tegami", ko: "pyeonji", zh: "xìn", ar: "risāla" },
  "number": { ja: "bangō", ko: "beonho", zh: "hàomǎ", ar: "raqam" },
  "name": { ja: "namae", ko: "ireum", zh: "míngzi", ar: "ism" },

  // ── Health & Body ──
  "sick": { ja: "byōki", ko: "apeun", zh: "shēngbìng", ar: "marīḍ" },
  "healthy": { ja: "kenkō", ko: "geonganhan", zh: "jiànkāng", ar: "ṣiḥḥī" },
  "medicine": { ja: "kusuri", ko: "yak", zh: "yào", ar: "dawā'" },
  "pain": { ja: "itami", ko: "tongjeung", zh: "téngtòng", ar: "alam" },
  "fever": { ja: "netsu", ko: "yeol", zh: "fāshāo", ar: "ḥummā" },
  "cough": { ja: "seki", ko: "gichim", zh: "késou", ar: "suʿāl" },
  "cold (illness)": { ja: "kaze", ko: "gamgi", zh: "gǎnmào", ar: "zukām" },
  "headache": { ja: "zutsū", ko: "dutong", zh: "tóutòng", ar: "ṣudāʿ" },
  "exercise": { ja: "undō", ko: "undong", zh: "yùndòng", ar: "tamrīn" },
  "rest": { ja: "yasumi", ko: "hyusik", zh: "xiūxi", ar: "rāḥa" },
  "breath": { ja: "iki", ko: "sum", zh: "hūxī", ar: "nafas" },
  "life": { ja: "inochi", ko: "saengmyeong", zh: "shēngmìng", ar: "ḥayāt" },
  "death": { ja: "shi", ko: "jugeum", zh: "sǐwáng", ar: "mawt" },
  "alive": { ja: "ikiteiru", ko: "sarainneun", zh: "huózhe", ar: "ḥayy" },

  // ── Common Phrases ──
  "i don't understand": { ja: "wakarimasen", ko: "ihae mothaeyo", zh: "wǒ bù míngbai", ar: "lā afham" },
  "i don't know": { ja: "shirimasen", ko: "moreugessoyo", zh: "wǒ bù zhīdào", ar: "lā aʿrif" },
  "i need help": { ja: "tasukete kudasai", ko: "dowajuseyo", zh: "wǒ xūyào bāngzhù", ar: "aḥtāj musāʿada" },
  "how much?": { ja: "ikura desu ka", ko: "eolmayeyo", zh: "duōshǎo qián", ar: "bikam" },
  "i like it": { ja: "suki desu", ko: "joahaeyo", zh: "wǒ xǐhuan", ar: "anā uḥibbuhu" },
  "i'm lost": { ja: "mayotte imasu", ko: "gireul ireossoyo", zh: "wǒ mílù le", ar: "anā ḍā'iʿ" },
  "wait a moment": { ja: "chotto matte", ko: "jamkkanmanyo", zh: "děng yīxià", ar: "intaẓir laḥẓa" },
  "let's go": { ja: "ikimashō", ko: "gaja", zh: "zǒu ba", ar: "hayya binā" },
  "of course": { ja: "mochiron", ko: "mullon ijyo", zh: "dāngrán", ar: "biṭ-ṭabʿ" },
  "no problem": { ja: "mondai nai desu", ko: "munje eopsoyo", zh: "méi wèntí", ar: "lā mushkila" },
  "congratulations": { ja: "omedetō gozaimasu", ko: "chukahamnida", zh: "gōngxǐ", ar: "mabrūk" },
  "happy birthday": { ja: "otanjōbi omedetō", ko: "saengil chukahamnida", zh: "shēngrì kuàilè", ar: "ʿīd mīlād saʿīd" },
  "i'm sorry": { ja: "gomen nasai", ko: "joesonghamnida", zh: "duìbuqǐ", ar: "anā āsif" },
  "cheers": { ja: "kanpai", ko: "geonbae", zh: "gānbēi", ar: "fī ṣiḥḥatik" },
  "good luck": { ja: "ganbatte", ko: "haenguneul bimnida", zh: "zhù nǐ hǎoyùn", ar: "ḥaẓẓ saʿīd" },
  "i agree": { ja: "dōi shimasu", ko: "donguihaeyo", zh: "wǒ tóngyì", ar: "anā muwāfiq" },
  "maybe": { ja: "tabun", ko: "amado", zh: "yěxǔ", ar: "rubbamā" },
  "very": { ja: "totemo", ko: "maeu", zh: "hěn", ar: "jiddan" },
  "also": { ja: "mo", ko: "ttohan", zh: "yě", ar: "ayḍan" },
  "already": { ja: "mō", ko: "imi", zh: "yǐjīng", ar: "bilfiʿl" },

  // ── Everyday Objects ──
  "phone": { ja: "keitai", ko: "haendeupon", zh: "shǒujī", ar: "hātif maḥmūl" },
  "camera": { ja: "kamera", ko: "kamera", zh: "xiàngjī", ar: "kāmīrā" },
  "television": { ja: "terebi", ko: "tellebijeon", zh: "diànshì", ar: "tilifziyūn" },
  "bottle": { ja: "botoru", ko: "byeong", zh: "píngzi", ar: "zujāja" },
  "cup": { ja: "kappu", ko: "keop", zh: "bēizi", ar: "kūb" },
  "plate": { ja: "sara", ko: "jeopsi", zh: "pánzi", ar: "ṭabaq" },
  "knife": { ja: "naifu", ko: "kal", zh: "dāo", ar: "sikkīn" },
  "fork": { ja: "fōku", ko: "pokeu", zh: "chāzi", ar: "shawka" },
  "spoon": { ja: "supūn", ko: "sutgarak", zh: "sháozi", ar: "milʿaqa" },
  "box": { ja: "hako", ko: "sangja", zh: "hézi", ar: "ṣundūq" },
  "scissors": { ja: "hasami", ko: "gawi", zh: "jiǎndāo", ar: "miqaṣṣ" },
  "needle": { ja: "hari", ko: "baneul", zh: "zhēn", ar: "ibra" },
  "rope": { ja: "rōpu", ko: "batjul", zh: "shéngzi", ar: "ḥabl" },
  "candle": { ja: "rōsoku", ko: "yangcho", zh: "làzhú", ar: "shamʿa" },
  "soap": { ja: "sekken", ko: "binu", zh: "féizào", ar: "ṣābūn" },
  "towel": { ja: "taoru", ko: "sugeon", zh: "máojīn", ar: "minshafa" },
  "brush": { ja: "burashi", ko: "beureosi", zh: "shuāzi", ar: "furshāt" },
  "gift": { ja: "purezento", ko: "seonmul", zh: "lǐwù", ar: "hadiyya" },
  "toy": { ja: "omocha", ko: "jangnangam", zh: "wánjù", ar: "luʿba" },
  "picture": { ja: "shashin", ko: "sajin", zh: "zhàopiàn", ar: "ṣūra" },
  "coin": { ja: "koin", ko: "dongjeon", zh: "yìngbì", ar: "ʿumla" },
  "ring": { ja: "yubiwa", ko: "banji", zh: "jièzhǐ", ar: "khātam" },
  "watch": { ja: "udedokei", ko: "sigye", zh: "shǒubiǎo", ar: "sāʿat yad" },
  "glasses": { ja: "megane", ko: "angyeong", zh: "yǎnjìng", ar: "naẓẓārāt" },
  "wheel": { ja: "sharin", ko: "bakwi", zh: "lúnzi", ar: "ʿajala" },
  "flag": { ja: "hata", ko: "gitbal", zh: "qízhì", ar: "ʿalam" },
  "ball": { ja: "bōru", ko: "gong", zh: "qiú", ar: "kura" },
  "music": { ja: "ongaku", ko: "eumak", zh: "yīnyuè", ar: "mūsīqā" },
  "game": { ja: "gēmu", ko: "geim", zh: "yóuxì", ar: "luʿba" },
  "movie": { ja: "eiga", ko: "yeonghwa", zh: "diànyǐng", ar: "fīlm" },
  "song": { ja: "uta", ko: "norae", zh: "gēqǔ", ar: "ughniya" },
  "story": { ja: "monogatari", ko: "iyagi", zh: "gùshi", ar: "qiṣṣa" },
  "news": { ja: "nyūsu", ko: "nyuseu", zh: "xīnwén", ar: "akhbār" },
  "dream": { ja: "yume", ko: "kkum", zh: "mèng", ar: "ḥulm" },
  "truth": { ja: "shinjitsu", ko: "jinsil", zh: "zhēnxiàng", ar: "ḥaqīqa" }
};
